# Exploración inicial de fuentes

Este notebook revisa cada archivo CSV disponible en `data/raw/`. Su propósito es documentar de manera reproducible la estructura, los tipos de datos, una muestra inicial y los valores faltantes de cada fuente.

## 1. Configuración

Los datos originales se leen desde una ruta relativa al proyecto. No se modifican los archivos de origen.

In [4]:
from pathlib import Path
import pandas as pd
from IPython.display import display

PROJECT_DIR = Path.cwd().resolve().parent
RAW_DIR = PROJECT_DIR / 'data' / 'raw'
CSV_FILES = sorted(RAW_DIR.glob('*.csv'))

print(f'Carpeta de datos: {RAW_DIR}')
print(f'Archivos CSV encontrados: {len(CSV_FILES)}')
[file.name for file in CSV_FILES]

Carpeta de datos: C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\003_d1_vs_tiendas\data\raw
Archivos CSV encontrados: 5

['establecimientos_de_indus.csv',
 'Estructura_empresarial_Medellín_según_comunas_y_divisiones_de_la_CIIU_20260831.csv',
 'Módulo de características del micronegocio.csv',
 'Módulo de identificación.csv',
 'variables-08-31-26-044626.csv']

## 2. Función de carga

Se prueban las codificaciones más frecuentes en las fuentes disponibles. `sep=None` permite a pandas inferir el separador.

In [6]:
def read_csv_with_fallback(file_path: Path) -> tuple[pd.DataFrame, str]:
    """Carga un CSV probando codificaciones frecuentes."""
    last_error = None
    for encoding in ('utf-8', 'latin-1'):
        try:
            dataframe = pd.read_csv(file_path, encoding=encoding, sep=None, engine='python')
            return dataframe, encoding
        except (UnicodeDecodeError, pd.errors.ParserError) as error:
            last_error = error
    raise last_error

## 3. Exploración por archivo

Para cada archivo se muestran: `df.shape`, `df.columns`, `df.dtypes`, `df.head()`, `df.info()` y `df.isna().sum()`.

In [7]:
if not CSV_FILES:
    raise FileNotFoundError(f'No se encontraron archivos CSV en {RAW_DIR}')

for file_path in CSV_FILES:
    df, encoding = read_csv_with_fallback(file_path)

    print('═' * 100)
    print(f'ARCHIVO: {file_path.name}')
    print(f'Codificación usada: {encoding}')

    print('\n1. df.shape')
    print(df.shape)

    print('\n2. df.columns')
    print(df.columns.tolist())

    print('\n3. df.dtypes')
    display(df.dtypes.to_frame(name='dtype'))

    print('\n4. df.head()')
    display(df.head())

    print('\n5. df.info()')
    df.info()

    print('\n6. df.isna().sum()')
    display(df.isna().sum().to_frame(name='valores_faltantes'))

════════════════════════════════════════════════════════════════════════════════════════════════════
ARCHIVO: establecimientos_de_indus.csv
Codificación usada: utf-8

1. df.shape
(22, 15)

2. df.columns
['OBJECTID', 'Shape', 'id_contrato', 'nombre_establecimiento', 'corregimiento', 'codigociiu', 'grupo_actividad', 'comuna', 'nombre_comuna', 'codigo_barrio', 'nombre_barrio', 'longitud', 'latitud', 'x_origen_nacional', 'y_origen_nacional']

3. df.dtypes

                          dtype
OBJECTID                  int64
Shape                       str
id_contrato               int64
nombre_establecimiento      str
corregimiento               str
codigociiu                int64
grupo_actividad           int64
comuna                    int64
nombre_comuna               str
codigo_barrio             int64
nombre_barrio               str
longitud                float64
latitud                 float64
x_origen_nacional       float64
y_origen_nacional       float64

4. df.head()

,OBJECTID,Shape,id_contrato,nombre_establecimiento,corregimiento,codigociiu,grupo_actividad,comuna,nombre_comuna,codigo_barrio,nombre_barrio,longitud,latitud,x_origen_nacional,y_origen_nacional
0,1,"(4717209.6725, 2251359.9559000023)",1808778,MONIK BELLEZA INTEGRAL,04,9602,3,12,00,0,0000,-75.556739,6.268619,4.717210e+06,2.251360e+06
1,2,"(4713352.0796, 2248887.0945999995)",1808779,NO POSEE ESTABLECIMIENTOS,,1410,1,11,00,0,0000,-75.591482,6.246092,4.713352e+06,2.248887e+06
2,3,"(4710436.2309, 2249998.7957999986)",1808811,NO POSEE ESTABLECIMIENTOS,,4719,2,13,San Javier,1309,San Javier No.1,-75.617874,6.256011,4.710436e+06,2.249999e+06
3,4,"(4715197.411400001, 2246060.634200001)",1808816,NO POSEE ESTABLECIMIENTOS,,6201,3,14,El Poblado,1403,Villa Carlota,-75.574685,6.220620,4.715197e+06,2.246061e+06
4,5,"(4712710.769600001, 2247337.7101000026)",1808810,NO POSEE ESTABLECIMIENTOS,,5619,3,16,Belén,1603,Belén,-75.597206,6.232056,4.712711e+06,2.247338e+06

5. df.info()
<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   OBJECTID                22 non-null     int64
 1   Shape                   22 non-null     str
 2   id_contrato             22 non-null     int64
 3   nombre_establecimiento  22 non-null     str
 4   corregimiento           22 non-null     str
 5   codigociiu              22 non-null     int64
 6   grupo_actividad         22 non-null     int64
 7   comuna                  22 non-null     int64
 8   nombre_comuna           22 non-null     str
 9   codigo_barrio           22 non-null     int64
 10  nombre_barrio           22 non-null     str
 11  longitud                22 non-null     float64
 12  latitud                 22 non-null     float64
 13  x_origen_nacional       22 non-null     float64
 14  y_origen_nacional       22 non-null     float64
dtypes: float64(4), int64(6), str(5)
memory usage: 4.4 KB

6. df.isna().sum()

                        valores_faltantes
OBJECTID                                0
Shape                                   0
id_contrato                             0
nombre_establecimiento                  0
corregimiento                           0
codigociiu                              0
grupo_actividad                         0
comuna                                  0
nombre_comuna                           0
codigo_barrio                           0
nombre_barrio                           0
longitud                                0
latitud                                 0
x_origen_nacional                       0
y_origen_nacional                       0

════════════════════════════════════════════════════════════════════════════════════════════════════
ARCHIVO: Estructura_empresarial_Medellín_según_comunas_y_divisiones_de_la_CIIU_20260831.csv
Codificación usada: utf-8

1. df.shape
(439, 25)

2. df.columns
['AÑO', 'División', 'Descripción', 'ALTAVISTA', 'ARANJUEZ', 'BELEN', 'BUENOS AIRES', 'CASTILLA', 'DOCE DE OCTUBRE', 'EL POBLADO', 'GUAYABAL', 'LA AMERICA', 'LA CANDELARIA', 'LAURELES-ESTADIO', 'MANRIQUE', 'PALMITAS', 'POPULAR', 'ROBLEDO', 'SAN CRISTOBAL', 'SAN ANTONIO DE PRADO', 'SAN JAVIER', 'SANTA CRUZ', 'SANTA ELENA', 'VILLA HERMOSA', 'Sin georreferenciar']

3. df.dtypes

                      dtype
AÑO                   int64
División              int64
Descripción             str
ALTAVISTA             int64
ARANJUEZ                str
BELEN                   str
BUENOS AIRES            str
CASTILLA                str
DOCE DE OCTUBRE       int64
EL POBLADO              str
GUAYABAL                str
LA AMERICA              str
LA CANDELARIA           str
LAURELES-ESTADIO        str
MANRIQUE              int64
PALMITAS              int64
POPULAR               int64
ROBLEDO                 str
SAN CRISTOBAL         int64
SAN ANTONIO DE PRADO  int64
SAN JAVIER            int64
SANTA CRUZ            int64
SANTA ELENA           int64
VILLA HERMOSA         int64
Sin georreferenciar     str

4. df.head()

,AÑO,División,Descripción,ALTAVISTA,ARANJUEZ,BELEN,BUENOS AIRES,CASTILLA,DOCE DE OCTUBRE,EL POBLADO,...,PALMITAS,POPULAR,ROBLEDO,SAN CRISTOBAL,SAN ANTONIO DE PRADO,SAN JAVIER,SANTA CRUZ,SANTA ELENA,VILLA HERMOSA,Sin georreferenciar
0,2018,0,Sin CIIU,0,2,4,1,0,0,19,...,0,0,2,0,0,1,1,0,2,"3,027"
1,2018,1,"Agricultura, ganadería, caza y actividades de ...",0,14,110,20,21,2,689,...,0,0,24,0,0,9,2,0,10,316
2,2018,2,Silvicultura y extracción de madera,0,3,8,1,1,1,45,...,0,0,5,0,0,1,0,0,3,29
3,2018,3,Pesca y acuicultura,0,0,2,0,0,0,7,...,0,0,0,0,0,0,0,0,0,9
4,2018,5,Extracción de carbón de piedra y lignito,0,0,2,0,0,0,7,...,0,0,0,0,0,0,0,0,0,2

5. df.info()
<class 'pandas.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AÑO                   439 non-null    int64
 1   División              439 non-null    int64
 2   Descripción           439 non-null    str
 3   ALTAVISTA             439 non-null    int64
 4   ARANJUEZ              439 non-null    str
 5   BELEN                 439 non-null    str
 6   BUENOS AIRES          439 non-null    str
 7   CASTILLA              439 non-null    str
 8   DOCE DE OCTUBRE       439 non-null    int64
 9   EL POBLADO            439 non-null    str
 10  GUAYABAL              439 non-null    str
 11  LA AMERICA            439 non-null    str
 12  LA CANDELARIA         439 non-null    str
 13  LAURELES-ESTADIO      439 non-null    str
 14  MANRIQUE              439 non-null    int64
 15  PALMITAS              439 non-null    int64
 16  POPULAR               439 non-null    int64
 17  ROBLEDO               439 non-null    str
 18  SAN CRISTOBAL         439 non-null    int64
 19  SAN ANTONIO DE PRADO  439 non-null    int64
 20  SAN JAVIER            439 non-null    int64
 21  SANTA CRUZ            439 non-null    int64
 22  SANTA ELENA           439 non-null    int64
 23  VILLA HERMOSA         439 non-null    int64
 24  Sin georreferenciar   439 non-null    str
dtypes: int64(13), str(12)
memory usage: 120.0 KB

6. df.isna().sum()

                      valores_faltantes
AÑO                                   0
División                              0
Descripción                           0
ALTAVISTA                             0
ARANJUEZ                              0
BELEN                                 0
BUENOS AIRES                          0
CASTILLA                              0
DOCE DE OCTUBRE                       0
EL POBLADO                            0
GUAYABAL                              0
LA AMERICA                            0
LA CANDELARIA                         0
LAURELES-ESTADIO                      0
MANRIQUE                              0
PALMITAS                              0
POPULAR                               0
ROBLEDO                               0
SAN CRISTOBAL                         0
SAN ANTONIO DE PRADO                  0
SAN JAVIER                            0
SANTA CRUZ                            0
SANTA ELENA                           0
VILLA HERMOSA                         0
Sin georreferenciar                   0

════════════════════════════════════════════════════════════════════════════════════════════════════
ARCHIVO: Módulo de características del micronegocio.csv
Codificación usada: utf-8

1. df.shape
(78501, 19)

2. df.columns
['DIRECTORIO', 'SECUENCIA_P', 'SECUENCIA_ENCUESTA', 'P1633', 'P986', 'P640', 'P4000', 'P1055', 'P1056', 'P661', 'P1057', 'P4004', 'P2991', 'P2992', 'P2993', 'CLASE_TE', 'COD_DEPTO', 'AREA', 'F_EXP']

3. df.dtypes

                      dtype
DIRECTORIO            int64
SECUENCIA_P           int64
SECUENCIA_ENCUESTA    int64
P1633                 int64
P986                float64
P640                  int64
P4000               float64
P1055                 int64
P1056               float64
P661                float64
P1057               float64
P4004               float64
P2991               float64
P2992               float64
P2993               float64
CLASE_TE              int64
COD_DEPTO             int64
AREA                float64
F_EXP               float64

4. df.head()

,DIRECTORIO,SECUENCIA_P,SECUENCIA_ENCUESTA,P1633,P986,P640,P4000,P1055,P1056,P661,P1057,P4004,P2991,P2992,P2993,CLASE_TE,COD_DEPTO,AREA,F_EXP
0,7627444,1,1,2,NaN,5,1.0,2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,44,NaN,60.050515
1,7627446,1,1,2,NaN,5,1.0,2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,44,NaN,86.341075
2,7627449,1,1,2,NaN,3,NaN,2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,68,NaN,139.884518
3,7627453,1,2,2,NaN,3,NaN,2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,68,NaN,168.635440
4,7627456,1,3,2,NaN,5,1.0,2,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1,68,NaN,64.659273

5. df.info()
<class 'pandas.DataFrame'>
RangeIndex: 78501 entries, 0 to 78500
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DIRECTORIO          78501 non-null  int64
 1   SECUENCIA_P         78501 non-null  int64
 2   SECUENCIA_ENCUESTA  78501 non-null  int64
 3   P1633               78501 non-null  int64
 4   P986                18149 non-null  float64
 5   P640                78501 non-null  int64
 6   P4000               52800 non-null  float64
 7   P1055               78501 non-null  int64
 8   P1056               8559 non-null   float64
 9   P661                8559 non-null   float64
 10  P1057               69942 non-null  float64
 11  P4004               1484 non-null   float64
 12  P2991               18149 non-null  float64
 13  P2992               18149 non-null  float64
 14  P2993               18149 non-null  float64
 15  CLASE_TE            78501 non-null  int64
 16  COD_DEPTO           78501 non-null  int64
 17  AREA                52430 non-null  float64
 18  F_EXP               78501 non-null  float64
dtypes: float64(11), int64(8)
memory usage: 11.4 MB

6. df.isna().sum()

                    valores_faltantes
DIRECTORIO                          0
SECUENCIA_P                         0
SECUENCIA_ENCUESTA                  0
P1633                               0
P986                            60352
P640                                0
P4000                           25701
P1055                               0
P1056                           69942
P661                            69942
P1057                            8559
P4004                           77017
P2991                           60352
P2992                           60352
P2993                           60352
CLASE_TE                            0
COD_DEPTO                           0
AREA                            26071
F_EXP                               0

════════════════════════════════════════════════════════════════════════════════════════════════════
ARCHIVO: Módulo de identificación.csv
Codificación usada: utf-8

1. df.shape
(78501, 20)

2. df.columns
['DIRECTORIO', 'SECUENCIA_P', 'SECUENCIA_ENCUESTA', 'COD_DEPTO', 'AREA', 'CLASE_TE', 'P35', 'P241', 'MES_REF', 'P3031', 'P3032_1', 'P3032_2', 'P3032_3', 'P3033', 'P3034', 'P3035', 'P3000', 'GRUPOS4', 'GRUPOS12', 'F_EXP']

3. df.dtypes

                      dtype
DIRECTORIO            int64
SECUENCIA_P           int64
SECUENCIA_ENCUESTA    int64
COD_DEPTO             int64
AREA                float64
CLASE_TE              int64
P35                   int64
P241                  int64
MES_REF                 str
P3031                 int64
P3032_1             float64
P3032_2             float64
P3032_3             float64
P3033                 int64
P3034                 int64
P3035                 int64
P3000                 int64
GRUPOS4               int64
GRUPOS12              int64
F_EXP               float64

4. df.head()

,DIRECTORIO,SECUENCIA_P,SECUENCIA_ENCUESTA,COD_DEPTO,AREA,CLASE_TE,P35,P241,MES_REF,P3031,P3032_1,P3032_2,P3032_3,P3033,P3034,P3035,P3000,GRUPOS4,GRUPOS12,F_EXP
0,7627444,1,1,44,NaN,2,2,33,ENERO,2,NaN,NaN,NaN,2,240,2,2,2,3,60.050515
1,7627446,1,1,44,NaN,2,1,31,ENERO,2,NaN,NaN,NaN,2,166,2,2,1,1,86.341075
2,7627449,1,1,68,NaN,1,2,42,ENERO,2,NaN,NaN,NaN,2,60,2,2,3,5,139.884518
3,7627453,1,2,68,NaN,1,2,41,ENERO,2,NaN,NaN,NaN,2,60,2,2,4,7,168.635440
4,7627456,1,3,68,NaN,1,1,18,ENERO,2,NaN,NaN,NaN,2,9,2,2,4,6,64.659273

5. df.info()
<class 'pandas.DataFrame'>
RangeIndex: 78501 entries, 0 to 78500
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DIRECTORIO          78501 non-null  int64
 1   SECUENCIA_P         78501 non-null  int64
 2   SECUENCIA_ENCUESTA  78501 non-null  int64
 3   COD_DEPTO           78501 non-null  int64
 4   AREA                52430 non-null  float64
 5   CLASE_TE            78501 non-null  int64
 6   P35                 78501 non-null  int64
 7   P241                78501 non-null  int64
 8   MES_REF             78501 non-null  str
 9   P3031               78501 non-null  int64
 10  P3032_1             13225 non-null  float64
 11  P3032_2             13225 non-null  float64
 12  P3032_3             13225 non-null  float64
 13  P3033               78501 non-null  int64
 14  P3034               78501 non-null  int64
 15  P3035               78501 non-null  int64
 16  P3000               78501 non-null  int64
 17  GRUPOS4             78501 non-null  int64
 18  GRUPOS12            78501 non-null  int64
 19  F_EXP               78501 non-null  float64
dtypes: float64(5), int64(14), str(1)
memory usage: 12.5 MB

6. df.isna().sum()

                    valores_faltantes
DIRECTORIO                          0
SECUENCIA_P                         0
SECUENCIA_ENCUESTA                  0
COD_DEPTO                           0
AREA                            26071
CLASE_TE                            0
P35                                 0
P241                                0
MES_REF                             0
P3031                               0
P3032_1                         65276
P3032_2                         65276
P3032_3                         65276
P3033                               0
P3034                               0
P3035                               0
P3000                               0
GRUPOS4                             0
GRUPOS12                            0
F_EXP                               0

════════════════════════════════════════════════════════════════════════════════════════════════════
ARCHIVO: variables-08-31-26-044626.csv
Codificación usada: utf-8

1. df.shape
(1, 27)

2. df.columns
['\ufeffsurvey_idno', 'sid', 'file_id', 'vid', 'name', 'labl', 'var_intrvl', 'var_dcml', 'var_wgt', 'var_start_pos', 'var_end_pos', 'var_width', 'var_imputation', 'var_security', 'var_respunit', 'var_qstn_preqtxt', 'var_qstn_qstnlit', 'var_qstn_postqtxt', 'var_qstn_ivulnstr', 'var_universe', 'var_sumstat', 'var_txt', 'var_catgry', 'var_codinstr', 'var_concept', 'var_format', 'var_notes']

3. df.dtypes

                     dtype
﻿survey_idno           str
sid                  int64
file_id                str
vid                    str
name                   str
labl                   str
var_intrvl             str
var_dcml             int64
var_wgt            float64
var_start_pos      float64
var_end_pos        float64
var_width          float64
var_imputation     float64
var_security           str
var_respunit       float64
var_qstn_preqtxt   float64
var_qstn_qstnlit       str
var_qstn_postqtxt  float64
var_qstn_ivulnstr  float64
var_universe           str
var_sumstat            str
var_txt            float64
var_catgry             str
var_codinstr       float64
var_concept            str
var_format             str
var_notes          float64

4. df.head()

,﻿survey_idno,sid,file_id,vid,name,labl,var_intrvl,var_dcml,var_wgt,var_start_pos,...,var_qstn_postqtxt,var_qstn_ivulnstr,var_universe,var_sumstat,var_txt,var_catgry,var_codinstr,var_concept,var_format,var_notes
0,DANE-DIMPE-EMICRON-2024,875,F3,V37,P3096,Especifique cuál ¿,discrete,2,NaN,NaN,...,NaN,NaN,Está conformado por los propietarios(as) de mi...,"[{""value"":""10258"",""type"":""vald"",""wgtd"":null},{...",NaN,"[{""value"":""1"",""labl"":""Local - tienda"",""is_miss...",NaN,[],"{""type"":""numeric"",""schema"":""other"",""category"":...",NaN

5. df.info()
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ﻿survey_idno       1 non-null      str
 1   sid                1 non-null      int64
 2   file_id            1 non-null      str
 3   vid                1 non-null      str
 4   name               1 non-null      str
 5   labl               1 non-null      str
 6   var_intrvl         1 non-null      str
 7   var_dcml           1 non-null      int64
 8   var_wgt            0 non-null      float64
 9   var_start_pos      0 non-null      float64
 10  var_end_pos        0 non-null      float64
 11  var_width          0 non-null      float64
 12  var_imputation     0 non-null      float64
 13  var_security       1 non-null      str
 14  var_respunit       0 non-null      float64
 15  var_qstn_preqtxt   0 non-null      float64
 16  var_qstn_qstnlit   1 non-null      str
 17  var_qstn_postqtxt  0 non-null      float64
 18  var_qstn_ivulnstr  0 non-null      float64
 19  var_universe       1 non-null      str
 20  var_sumstat        1 non-null      str
 21  var_txt            0 non-null      float64
 22  var_catgry         1 non-null      str
 23  var_codinstr       0 non-null      float64
 24  var_concept        1 non-null      str
 25  var_format         1 non-null      str
 26  var_notes          0 non-null      float64
dtypes: float64(12), int64(2), str(13)
memory usage: 1.8 KB

6. df.isna().sum()

                   valores_faltantes
﻿survey_idno                       0
sid                                0
file_id                            0
vid                                0
name                               0
labl                               0
var_intrvl                         0
var_dcml                           0
var_wgt                            1
var_start_pos                      1
var_end_pos                        1
var_width                          1
var_imputation                     1
var_security                       0
var_respunit                       1
var_qstn_preqtxt                   1
var_qstn_qstnlit                   0
var_qstn_postqtxt                  1
var_qstn_ivulnstr                  1
var_universe                       0
var_sumstat                        0
var_txt                            1
var_catgry                         0
var_codinstr                       1
var_concept                        0
var_format                         0
var_notes                          1