# Exploración — anexo EMICRON: panaderías y tiendas de barrio, 2024

Este notebook explora exclusivamente el archivo `anex-EMICRON-PanaderiasTiendasBarrio-2024.xlsb`. Primero inventaría todas sus hojas y luego permite examinar una tabla a la vez.

## 1. Cargar el libro

El archivo está en formato Excel binario (`.xlsb`) y se lee con `pyxlsb`. Los datos originales no se modifican.

In [2]:
from pathlib import Path
import pandas as pd
from IPython.display import display
import subprocess

PROJECT_DIR = Path.cwd().resolve().parent
FILE_PATH = PROJECT_DIR / 'data' / 'raw' / 'anex-EMICRON-PanaderiasTiendasBarrio-2024.xlsb'

subprocess.check_call(['pip', 'install', 'pyxlsb'])

workbook = pd.ExcelFile(FILE_PATH, engine='pyxlsb')
SHEETS = workbook.sheet_names

print(f'Archivo: {FILE_PATH.name}')
print(f'Hojas encontradas: {len(SHEETS)}')
print(SHEETS)

Archivo: anex-EMICRON-PanaderiasTiendasBarrio-2024.xlsb
Hojas encontradas: 40
['Índice', 'Índice ', 'A.1', 'A.2', 'B.1', 'B.2', 'C.1', 'C.2', 'C.3', 'C.4', 'D.1', 'D.2', 'D.3', 'E.1.1', 'E.1.2', 'E.2', 'E.3', 'E.3.1.1', 'E.3.1.2', 'E.3.1.3', 'F.1', 'F.2', 'F.3', 'F.4', 'F.5', 'G.1', 'G.2', 'G.3', 'G.4', 'H.1', 'H.2', 'H.3', 'H.4', 'H.5', 'H.6', 'H.7', 'H.8', 'H.9', 'J.1', 'J.1_Errores']

## 2. Inventario de hojas

Las tablas se leen sin asumir encabezados: los anexos estadísticos suelen incluir títulos, notas y encabezados en varias filas.

In [ ]:
inventory = []

for sheet_name in SHEETS:
    sheet = pd.read_excel(FILE_PATH, sheet_name=sheet_name, header=None, engine='pyxlsb')
    non_empty = sheet.notna().sum().sum()
    first_values = sheet.stack().head(3).astype(str).tolist()
    inventory.append({
        'hoja': sheet_name,
        'filas': sheet.shape[0],
        'columnas': sheet.shape[1],
        'celdas_no_vacias': non_empty,
        'vista_previa': ' | '.join(first_values),
    })

inventory_df = pd.DataFrame(inventory)
display(inventory_df)

,hoja,filas,columnas,celdas_no_vacias,vista_previa
0,Índice,51,2,31,ENCUESTA DE MICRONEGOCIOS - VENDEDOR AMBULANTE...
1,Índice,64,2,56,ENCUESTA DE MICRONEGOCIOS - PANADERÍAS Y TIEN...
2,A.1,39,43,357,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
3,A.2,37,43,357,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
4,B.1,44,43,446,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
5,B.2,62,43,968,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
6,C.1,46,43,702,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
7,C.2,49,43,788,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
8,C.3,44,43,615,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
9,C.4,52,43,874,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
10,D.1,40,43,444,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
11,D.2,41,43,439,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
12,D.3,46,43,702,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
13,E.1.1,42,43,532,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
14,E.1.2,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
15,E.2,39,43,443,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
16,E.3,41,43,531,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
17,E.3.1.1,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
18,E.3.1.2,37,43,357,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
19,E.3.1.3,42,43,532,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
20,F.1,44,43,618,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
21,F.2,40,43,446,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
22,F.3,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
23,F.4,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
24,F.5,38,43,360,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
25,G.1,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
26,G.2,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
27,G.3,40,43,446,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
28,G.4,37,43,359,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
29,H.1,48,30,499,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
30,H.2,40,30,258,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
31,H.3,48,30,497,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
32,H.4,50,30,556,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
33,H.5,40,30,258,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
34,H.6,46,30,441,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
35,H.7,41,30,318,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
36,H.8,40,30,258,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
37,H.9,46,30,438,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
38,J.1,86,15,406,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...
39,J.1_Errores,86,43,1144,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...

## 3. Explorar una tabla

Cambie `SHEET_TO_EXPLORE` para revisar otra hoja del inventario. La lectura conserva títulos y notas para poder identificar después la fila correcta de encabezados.

In [ ]:
SHEET_TO_EXPLORE = 'A.1'

if SHEET_TO_EXPLORE not in SHEETS:
    raise ValueError(f'La hoja {SHEET_TO_EXPLORE!r} no existe. Opciones: {SHEETS}')

df = pd.read_excel(FILE_PATH, sheet_name=SHEET_TO_EXPLORE, header=None, engine='pyxlsb')

print(f'Hoja: {SHEET_TO_EXPLORE}')
print(f'df.shape: {df.shape}')
print('\ndf.columns:')
print(df.columns.tolist())
print('\ndf.dtypes:')
display(df.dtypes.to_frame(name='dtype'))
print('\ndf.head(12):')
display(df.head(12))
print('\ndf.info():')
df.info()

missingness = pd.DataFrame({
    'valores_faltantes': df.isna().sum(),
    'porcentaje_faltante': (df.isna().mean() * 100).round(2),
})
print('\ndf.isna().sum():')
display(missingness)

Hoja: A.1
df.shape: (39, 43)

df.columns:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]

df.dtypes:

      dtype
0    object
1    object
2    object
3    object
4    object
5    object
6   float64
7    object
8    object
9    object
10   object
11  float64
12   object
13   object
14   object
15   object
16  float64
17   object
18   object
19   object
20   object
21  float64
22   object
23   object
24   object
25   object
26  float64
27   object
28   object
29   object
30   object
31   object
32   object
33   object
34   object
35   object
36   object
37   object
38   object
39   object
40   object
41   object
42   object

df.head(12):

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ENCUESTA DE MICRONEGOCIOS -PANADERÍAS Y TIENDA...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Total Nacional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Cuadro A.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Cantidad de micronegocios de panaderías y tien...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Total Nacional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

df.info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 43 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       21 non-null     object
 1   1       10 non-null     object
 2   2       8 non-null      object
 3   3       8 non-null      object
 4   4       8 non-null      object
 5   5       8 non-null      object
 6   6       8 non-null      float64
 7   7       8 non-null      object
 8   8       8 non-null      object
 9   9       8 non-null      object
 10  10      8 non-null      object
 11  11      8 non-null      float64
 12  12      8 non-null      object
 13  13      8 non-null      object
 14  14      8 non-null      object
 15  15      8 non-null      object
 16  16      8 non-null      float64
 17  17      8 non-null      object
 18  18      8 non-null      object
 19  19      8 non-null      object
 20  20      8 non-null      object
 21  21      8 non-null      float64
 22  22      8 non-null      object
 23  23      8 non-null      object
 24  24      8 non-null      object
 25  25      8 non-null      object
 26  26      8 non-null      float64
 27  27      8 non-null      object
 28  28      8 non-null      object
 29  29      8 non-null      object
 30  30      8 non-null      object
 31  31      10 non-null     object
 32  32      7 non-null      object
 33  33      8 non-null      object
 34  34      8 non-null      object
 35  35      7 non-null      object
 36  36      8 non-null      object
 37  37      8 non-null      object
 38  38      7 non-null      object
 39  39      8 non-null      object
 40  40      8 non-null      object
 41  41      7 non-null      object
 42  42      8 non-null      object
dtypes: float64(5), object(38)
memory usage: 13.2+ KB

df.isna().sum():

    valores_faltantes  porcentaje_faltante
0                  18                46.15
1                  29                74.36
2                  31                79.49
3                  31                79.49
4                  31                79.49
5                  31                79.49
6                  31                79.49
7                  31                79.49
8                  31                79.49
9                  31                79.49
10                 31                79.49
11                 31                79.49
12                 31                79.49
13                 31                79.49
14                 31                79.49
15                 31                79.49
16                 31                79.49
17                 31                79.49
18                 31                79.49
19                 31                79.49
20                 31                79.49
21                 31                79.49
22                 31                79.49
23                 31                79.49
24                 31                79.49
25                 31                79.49
26                 31                79.49
27                 31                79.49
28                 31                79.49
29                 31                79.49
30                 31                79.49
31                 29                74.36
32                 32                82.05
33                 31                79.49
34                 31                79.49
35                 32                82.05
36                 31                79.49
37                 31                79.49
38                 32                82.05
39                 31                79.49
40                 31                79.49
41                 32                82.05
42                 31                79.49

## 4. Siguiente lectura

Una vez identificada la fila de encabezados y la unidad de análisis de cada tabla, se debe cargar esa hoja nuevamente con el `header` apropiado. Las notas metodológicas y los factores de expansión deben conservarse al producir estimaciones.