# Exploración inicial - Episodio 2: Chocó

Este cuaderno sirve como punto de partida para revisar los archivos del Chocó y definir el primer análisis.

Objetivos:
- Revisar la estructura de cada dataset
- Identificar columnas clave y tipos de datos
- Verificar nulos y duplicados
- Preparar la base para un análisis más profundo

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

# Raíz del repositorio
ROOT = Path.cwd()

while ROOT.name != "Colombia_en_datos" and ROOT.parent != ROOT:
    ROOT = ROOT.parent

# Datos específicos del episodio 002 — Chocó
EPISODIO = ROOT / "episodios" / "002_EL_chocó"

RAW = EPISODIO / "Data" / "raw"

print("ROOT:", ROOT)
print("EPISODIO:", EPISODIO)
print("RAW:", RAW)
print("Existe RAW:", RAW.exists())

ROOT: c:\Users\USUARIO\Desktop\Colombia_en_datos
EPISODIO: c:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó
RAW: c:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw
Existe RAW: True

In [3]:
archivos_raw = sorted(
    p for p in RAW.iterdir()
    if p.is_file()
)

for archivo in archivos_raw:
    print(archivo.name)

dataset_01_poblacion_territorio_choco.csv
dataset_01_poblacion_territorio_choco_definitivo.csv
dataset_02_conectividad_digital_choco_v2.csv
dataset_03_conectividad_fisica_choco_final.csv
dataset_05_condiciones_socioeconomicas_choco_final.csv
dataset_06_informacion_comunicacion_choco_v1.xlsx
dataset_07_emergencias_desastres_choco_final(1).xlsx
dataset_08_capacidad_institucional_choco_v1.xlsx
dataset_09_inversion_publica_infraestructura_choco_v1.xlsx
dataset_10_historia_evidencia_cualitativa_choco_v1.xlsx
Divipola_Serv_PuntosCentrosPoblados2013I.pitemx
Documento_Dataset_03_Conectividad_Fisica_Choco.docx
GiniMovilidad.csv
TerriData_Dim4.xlsx
TerriData_Dim5.xlsx
Visor-TCCN.xlsx

In [4]:
datasets = {
    "01_poblacion_territorio": (
        RAW / "dataset_01_poblacion_territorio_choco_definitivo.csv"
    ),

    "02_conectividad_digital": (
        RAW / "dataset_02_conectividad_digital_choco_v2.csv"
    ),

    "03_conectividad_fisica": (
        RAW / "dataset_03_conectividad_fisica_choco_final.csv"
    ),

    "05_condiciones_socioeconomicas": (
        RAW / "dataset_05_condiciones_socioeconomicas_choco_final.csv"
    ),

    "06_informacion_comunicacion": (
        RAW / "dataset_06_informacion_comunicacion_choco_v1.xlsx"
    ),

    "07_emergencias_desastres": (
        RAW / "dataset_07_emergencias_desastres_choco_final(1).xlsx"
    ),

    "08_capacidad_institucional": (
        RAW / "dataset_08_capacidad_institucional_choco_v1.xlsx"
    ),

    "09_inversion_publica": (
        RAW / "dataset_09_inversion_publica_infraestructura_choco_v1.xlsx"
    ),

    "10_historia_evidencia": (
        RAW / "dataset_10_historia_evidencia_cualitativa_choco_v1.xlsx"
    ),
}

for nombre, path in datasets.items():
    print(
        f"{nombre:35} | "
        f"{'OK' if path.exists() else 'FALTA':8} | "
        f"{path.name}"
    )

01_poblacion_territorio             | OK       | dataset_01_poblacion_territorio_choco_definitivo.csv
02_conectividad_digital             | OK       | dataset_02_conectividad_digital_choco_v2.csv
03_conectividad_fisica              | OK       | dataset_03_conectividad_fisica_choco_final.csv
05_condiciones_socioeconomicas      | OK       | dataset_05_condiciones_socioeconomicas_choco_final.csv
06_informacion_comunicacion         | OK       | dataset_06_informacion_comunicacion_choco_v1.xlsx
07_emergencias_desastres            | OK       | dataset_07_emergencias_desastres_choco_final(1).xlsx
08_capacidad_institucional          | OK       | dataset_08_capacidad_institucional_choco_v1.xlsx
09_inversion_publica                | OK       | dataset_09_inversion_publica_infraestructura_choco_v1.xlsx
10_historia_evidencia               | OK       | dataset_10_historia_evidencia_cualitativa_choco_v1.xlsx

inventario inicial

In [5]:
inventario = []

for nombre, path in datasets.items():

    registro = {
        "dataset": nombre,
        "archivo": path.name,
        "extension": path.suffix.lower(),
        "tamano_mb": round(path.stat().st_size / (1024**2), 2),
    }

    inventario.append(registro)

inventario = pd.DataFrame(inventario)

display(inventario)

,dataset,archivo,extension,tamano_mb
0,01_poblacion_territorio,dataset_01_poblacion_territorio_choco_definiti...,.csv,0.00
1,02_conectividad_digital,dataset_02_conectividad_digital_choco_v2.csv,.csv,0.01
2,03_conectividad_fisica,dataset_03_conectividad_fisica_choco_final.csv,.csv,0.01
3,05_condiciones_socioeconomicas,dataset_05_condiciones_socioeconomicas_choco_f...,.csv,0.00
4,06_informacion_comunicacion,dataset_06_informacion_comunicacion_choco_v1.xlsx,.xlsx,0.02
5,07_emergencias_desastres,dataset_07_emergencias_desastres_choco_final(1...,.xlsx,0.11
6,08_capacidad_institucional,dataset_08_capacidad_institucional_choco_v1.xlsx,.xlsx,0.01
7,09_inversion_publica,dataset_09_inversion_publica_infraestructura_c...,.xlsx,4.48
8,10_historia_evidencia,dataset_10_historia_evidencia_cualitativa_choc...,.xlsx,0.01

In [6]:
# Cargar únicamente el dataset oficial 01
path_01 = datasets["01_poblacion_territorio"]

df01 = pd.read_csv(path_01)

print("Shape:", df01.shape)
print("\nColumnas:")
for i, col in enumerate(df01.columns, start=1):
    print(f"{i:02d}. {col}")

Shape: (31, 20)

Columnas:
01. divipola
02. municipio
03. departamento
04. poblacion_total
05. poblacion_urbana_cabecera
06. poblacion_centros_poblados
07. poblacion_rural_disperso
08. porcentaje_poblacion_rural
09. indice_ruralidad_existente
10. proporcion_poblacion_10_19
11. poblacion_indigena
12. poblacion_afrodescendiente_narp
13. poblacion_negra_mulata_afro
14. poblacion_raizal
15. poblacion_palenquera
16. densidad_poblacional_km2
17. superficie_km2
18. centros_poblados
19. distancia_quibdo_km
20. observacion_fuente_2018

In [7]:
print("\nInformación estructural:")
df01.info()

Información estructural:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 20 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   divipola                         31 non-null     int64
 1   municipio                        31 non-null     object
 2   departamento                     31 non-null     object
 3   poblacion_total                  30 non-null     float64
 4   poblacion_urbana_cabecera        30 non-null     float64
 5   poblacion_centros_poblados       30 non-null     float64
 6   poblacion_rural_disperso         30 non-null     float64
 7   porcentaje_poblacion_rural       30 non-null     float64
 8   indice_ruralidad_existente       30 non-null     float64
 9   proporcion_poblacion_10_19       30 non-null     float64
 10  poblacion_indigena               30 non-null     float64
 11  poblacion_afrodescendiente_narp  30 non-null     float64
 12  poblacion_negra_mulata_afro      30 non-null     float64
 13  poblacion_raizal                 30 non-null     float64
 14  poblacion_palenquera             30 non-null     float64
 15  densidad_poblacional_km2         0 non-null      float64
 16  superficie_km2                   0 non-null      float64
 17  centros_poblados                 0 non-null      float64
 18  distancia_quibdo_km              0 non-null      float64
 19  observacion_fuente_2018          1 non-null      object
dtypes: float64(16), int64(1), object(3)
memory usage: 5.0+ KB

In [8]:
auditoria_01 = pd.DataFrame({
    "variable": df01.columns,
    "tipo": df01.dtypes.astype(str),
    "nulos": df01.isna().sum(),
    "nulos_pct": (df01.isna().mean() * 100).round(2),
    "unicos": df01.nunique(dropna=False)
})

display(auditoria_01)

,variable,tipo,nulos,nulos_pct,unicos
divipola,divipola,int64,0,0.00,31
municipio,municipio,object,0,0.00,31
departamento,departamento,object,0,0.00,1
poblacion_total,poblacion_total,float64,1,3.23,31
poblacion_urbana_cabecera,poblacion_urbana_cabecera,float64,1,3.23,31
poblacion_centros_poblados,poblacion_centros_poblados,float64,1,3.23,31
poblacion_rural_disperso,poblacion_rural_disperso,float64,1,3.23,31
porcentaje_poblacion_rural,porcentaje_poblacion_rural,float64,1,3.23,31
indice_ruralidad_existente,indice_ruralidad_existente,float64,1,3.23,31
proporcion_poblacion_10_19,proporcion_poblacion_10_19,float64,1,3.23,29
poblacion_indigena,poblacion_indigena,float64,1,3.23,31
poblacion_afrodescendiente_narp,poblacion_afrodescendiente_narp,float64,1,3.23,31
poblacion_negra_mulata_afro,poblacion_negra_mulata_afro,float64,1,3.23,31
poblacion_raizal,poblacion_raizal,float64,1,3.23,10
poblacion_palenquera,poblacion_palenquera,float64,1,3.23,13
densidad_poblacional_km2,densidad_poblacional_km2,float64,31,100.00,1
superficie_km2,superficie_km2,float64,31,100.00,1
centros_poblados,centros_poblados,float64,31,100.00,1
distancia_quibdo_km,distancia_quibdo_km,float64,31,100.00,1
observacion_fuente_2018,observacion_fuente_2018,object,30,96.77,2

In [9]:
print("Filas:", len(df01))

if "municipio" in df01.columns:
    print("Municipios únicos:", df01["municipio"].nunique())

if "divipola" in df01.columns:
    print("DIVIPOLA únicos:", df01["divipola"].nunique())

if "departamento" in df01.columns:
    print("\nDepartamentos:")
    display(df01["departamento"].value_counts(dropna=False))

Filas: 31
Municipios únicos: 31
DIVIPOLA únicos: 31

Departamentos:

departamento
Chocó    31
Name: count, dtype: int64

In [10]:
print("Duplicados exactos:", df01.duplicated().sum())

display(df01.head())

Duplicados exactos: 0

,divipola,municipio,departamento,poblacion_total,poblacion_urbana_cabecera,poblacion_centros_poblados,poblacion_rural_disperso,porcentaje_poblacion_rural,indice_ruralidad_existente,proporcion_poblacion_10_19,poblacion_indigena,poblacion_afrodescendiente_narp,poblacion_negra_mulata_afro,poblacion_raizal,poblacion_palenquera,densidad_poblacional_km2,superficie_km2,centros_poblados,distancia_quibdo_km,observacion_fuente_2018
0,27001,Quibdó,Chocó,120679.0,108450.0,3018.0,9211.0,10.133495,12.46,20.76,4752.0,109805.0,109740.0,47.0,18.0,NaN,NaN,NaN,NaN,NaN
1,27006,Acandí,Chocó,12095.0,6513.0,2188.0,3394.0,46.151302,50.71,21.38,118.0,10525.0,10521.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
2,27025,Alto Baudó,Chocó,23954.0,2958.0,1186.0,19810.0,87.651332,87.84,25.63,13138.0,7791.0,7779.0,3.0,9.0,NaN,NaN,NaN,NaN,NaN
3,27050,Atrato,Chocó,5519.0,2532.0,2701.0,286.0,54.122124,52.82,22.26,36.0,5304.0,5304.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
4,27073,Bagadó,Chocó,10583.0,2539.0,589.0,7455.0,76.008693,76.44,23.28,6209.0,3668.0,3666.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [11]:
columnas_base = [
    "poblacion_total",
    "poblacion_urbana_cabecera",
    "poblacion_centros_poblados",
    "poblacion_rural_disperso",
    "porcentaje_poblacion_rural",
    "indice_ruralidad_existente",
    "proporcion_poblacion_10_19",
    "poblacion_indigena",
    "poblacion_afrodescendiente_narp",
    "poblacion_negra_mulata_afro",
    "poblacion_raizal",
    "poblacion_palenquera",
]

faltantes = df01[df01[columnas_base].isna().any(axis=1)]

display(
    faltantes[
        ["divipola", "municipio"] + columnas_base
    ]
)

,divipola,municipio,poblacion_total,poblacion_urbana_cabecera,poblacion_centros_poblados,poblacion_rural_disperso,porcentaje_poblacion_rural,indice_ruralidad_existente,proporcion_poblacion_10_19,poblacion_indigena,poblacion_afrodescendiente_narp,poblacion_negra_mulata_afro,poblacion_raizal,poblacion_palenquera
21,27493,Nuevo Belén de Bajirá,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
columnas_vacias = [
    "densidad_poblacional_km2",
    "superficie_km2",
    "centros_poblados",
    "distancia_quibdo_km",
]

for col in columnas_vacias:
    print(f"\n{col}")
    print("Nulos:", df01[col].isna().sum())
    print("Valores únicos:", df01[col].dropna().unique())

densidad_poblacional_km2
Nulos: 31
Valores únicos: []

superficie_km2
Nulos: 31
Valores únicos: []

centros_poblados
Nulos: 31
Valores únicos: []

distancia_quibdo_km
Nulos: 31
Valores únicos: []

In [13]:
df01["suma_desagregada"] = (
    df01["poblacion_urbana_cabecera"]
    + df01["poblacion_centros_poblados"]
    + df01["poblacion_rural_disperso"]
)

df01["diferencia_poblacional"] = (
    df01["poblacion_total"]
    - df01["suma_desagregada"]
)

display(
    df01[
        [
            "divipola",
            "municipio",
            "poblacion_total",
            "suma_desagregada",
            "diferencia_poblacional"
        ]
    ]
)

,divipola,municipio,poblacion_total,suma_desagregada,diferencia_poblacional
0,27001,Quibdó,120679.0,120679.0,0.0
1,27006,Acandí,12095.0,12095.0,0.0
2,27025,Alto Baudó,23954.0,23954.0,0.0
3,27050,Atrato,5519.0,5519.0,0.0
4,27073,Bagadó,10583.0,10583.0,0.0
5,27075,Bahía Solano,9417.0,9417.0,0.0
6,27077,Bajo Baudó,18561.0,18561.0,0.0
7,27099,Bojayá,11933.0,11933.0,0.0
8,27135,El Cantón del San Pablo,5663.0,5663.0,0.0
9,27150,Carmen del Darién,13189.0,13189.0,0.0
10,27160,Cértegui,4683.0,4683.0,0.0
11,27205,Condoto,12251.0,12251.0,0.0
12,27245,El Carmen de Atrato,7900.0,7900.0,0.0
13,27250,El Litoral del San Juan,11579.0,11579.0,0.0
14,27361,Istmina,28087.0,28087.0,0.0
15,27372,Juradó,4108.0,4108.0,0.0
16,27413,Lloró,8928.0,8928.0,0.0
17,27425,Medio Atrato,10140.0,10140.0,0.0
18,27430,Medio Baudó,13423.0,13423.0,0.0
19,27450,Medio San Juan,9073.0,9073.0,0.0
20,27491,Nóvita,8164.0,8164.0,0.0
21,27493,Nuevo Belén de Bajirá,NaN,NaN,NaN
22,27495,Nuquí,3456.0,3456.0,0.0
23,27580,Río Iró,4525.0,4525.0,0.0
24,27600,Río Quito,7974.0,7974.0,0.0
25,27615,Riosucio,48257.0,48257.0,0.0
26,27660,San José del Palmar,4721.0,4721.0,0.0
27,27745,Sipí,2768.0,2768.0,0.0
28,27787,Tadó,17000.0,17000.0,0.0
29,27800,Unguía,12192.0,12192.0,0.0
30,27810,Unión Panamericana,6590.0,6590.0,0.0

In [14]:
display(
    df01[
        ["municipio", "observacion_fuente_2018"]
    ]
    .dropna()
)

                municipio                            observacion_fuente_2018
21  Nuevo Belén de Bajirá  Nuevo Belén de Bajirá no aparece como municipi...

In [15]:
print(df01["observacion_fuente_2018"].dropna().unique())

['Nuevo Belén de Bajirá no aparece como municipio en CNPV 2018; requiere fuente/criterio específico para serie actual.']

In [16]:
porcentajes = [
    "porcentaje_poblacion_rural",
    "proporcion_poblacion_10_19"
]

for col in porcentajes:
    print(f"\n{col}")
    print("mínimo:", df01[col].min())
    print("máximo:", df01[col].max())

porcentaje_poblacion_rural
mínimo: 10.133494642812751
máximo: 91.1439842209073

proporcion_poblacion_10_19
mínimo: 20.11
máximo: 26.01

Resultado de la auditoría

1. Universo territorial: 🟢

Tenemos exactamente:

31 municipios
31 DIVIPOLA
31 nombres de municipio
31 registros para Chocó
sin duplicados territoriales aparentes

Esto hace que el archivo sea una buena tabla maestra territorial.


2. Consistencia de población: 🟢

Para los 30 municipios con datos, se cumple exactamente.

Las diferencias son 0.0 en todos los casos observados.

Eso es una validación interna bastante fuerte.


3. Nuevo Belén de Bajirá: 🟡

Este es el único municipio con todos esos indicadores poblacionales en NaN.

No debemos imputarlo ni eliminarlo.

Tenemos:

DIVIPOLA: 27493
Municipio: Nuevo Belén de Bajirá

Además, por tratarse de un municipio relativamente reciente en términos administrativos, es especialmente importante no rellenarlo automáticamente con datos de otro municipio.

El problema de Nuevo Belén de Bajirá está documentado

No es un NaN accidental. El propio dataset registra:

“Nuevo Belén de Bajirá no aparece como municipio en CNPV 2018; requiere fuente/criterio específico para serie actual.”

4. Cuatro variables están completamente vacías: 🔴

densidad_poblacional_km2
superficie_km2
centros_poblados
distancia_quibdo_km

Esto significa que el Dataset 01 todavía no cumple completamente nuestro diseño original.

Pero no es motivo para descartarlo. Son variables que podemos buscar posteriormente en fuentes oficiales y agregar mediante DIVIPOLA.

Dataset 02

In [17]:
path_02 = datasets["02_conectividad_digital"]

df02 = pd.read_csv(path_02)

print("Shape:", df02.shape)

print("\nColumnas:")
for i, col in enumerate(df02.columns, start=1):
    print(f"{i:02d}. {col}")

Shape: (31, 41)

Columnas:
01. divipola
02. municipio
03. departamento
04. anio
05. cobertura_internet_fijo_pct
06. hogares_con_internet_pct
07. cobertura_movil_3g_4g_pct
08. suscriptores_moviles_por_100_hab
09. accesos_fijos
10. accesos_moviles
11. tecnologia_acceso_fijo
12. cobertura_2g_pct
13. cobertura_3g_pct
14. cobertura_4g_pct
15. cobertura_5g_pct
16. centros_digitales
17. zonas_comunitarias
18. infraestructura_fibra
19. operadores
20. interrupciones_fallas_relevantes
21. fuente_base
22. accesos_fijos_2025_t3
23. penetracion_internet_fijo_2025_t3_pct
24. accesos_cable_2025_t3
25. accesos_fiber_to_the_building_o_fiber_to_the_basement__fttb_2025_t3
26. accesos_fiber_to_the_home__ftth_2025_t3
27. accesos_fiber_to_the_premises_2025_t3
28. accesos_hybrid_fiber_coaxial__hfc_2025_t3
29. accesos_otras_tecnologías_de_fibra__antes_fttx_2025_t3
30. accesos_otras_tecnologías_inalámbricas_2025_t3
31. accesos_satelital_2025_t3
32. accesos_wifi_2025_t3
33. accesos_wimax_2025_t3
34. accesos_xdsl_2025_t3
35. operadores_movil_2025_t3
36. presencia_2g_2025_t3
37. presencia_3g_2025_t3
38. presencia_4g_2025_t3
39. presencia_5g_2025_t3
40. fuente_mintic_actualizacion
41. periodo_actualizacion

In [18]:
df02.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 41 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   divipola                                                             31 non-null     int64
 1   municipio                                                            31 non-null     object
 2   departamento                                                         31 non-null     object
 3   anio                                                                 31 non-null     int64
 4   cobertura_internet_fijo_pct                                          30 non-null     float64
 5   hogares_con_internet_pct                                             29 non-null     float64
 6   cobertura_movil_3g_4g_pct                                            30 non-null     float64
 7   suscriptores_moviles_por_100_hab                                     0 non-null      float64
 8   accesos_fijos                                                        0 non-null      float64
 9   accesos_moviles                                                      0 non-null      float64
 10  tecnologia_acceso_fijo                                               0 non-null      float64
 11  cobertura_2g_pct                                                     0 non-null      float64
 12  cobertura_3g_pct                                                     0 non-null      float64
 13  cobertura_4g_pct                                                     0 non-null      float64
 14  cobertura_5g_pct                                                     0 non-null      float64
 15  centros_digitales                                                    0 non-null      float64
 16  zonas_comunitarias                                                   0 non-null      float64
 17  infraestructura_fibra                                                0 non-null      float64
 18  operadores                                                           0 non-null      float64
 19  interrupciones_fallas_relevantes                                     0 non-null      float64
 20  fuente_base                                                          31 non-null     object
 21  accesos_fijos_2025_t3                                                31 non-null     int64
 22  penetracion_internet_fijo_2025_t3_pct                                30 non-null     float64
 23  accesos_cable_2025_t3                                                2 non-null      float64
 24  accesos_fiber_to_the_building_o_fiber_to_the_basement__fttb_2025_t3  1 non-null      float64
 25  accesos_fiber_to_the_home__ftth_2025_t3                              31 non-null     float64
 26  accesos_fiber_to_the_premises_2025_t3                                1 non-null      float64
 27  accesos_hybrid_fiber_coaxial__hfc_2025_t3                            1 non-null      float64
 28  accesos_otras_tecnologías_de_fibra__antes_fttx_2025_t3               4 non-null      float64
 29  accesos_otras_tecnologías_inalámbricas_2025_t3                       2 non-null      float64
 30  accesos_satelital_2025_t3                                            30 non-null     float64
 31  accesos_wifi_2025_t3                                                 5 non-null      float64
 32  accesos_wimax_2025_t3                                                6 non-null      float64
 33  accesos_xdsl_2025_t3                                                 2 non-null      float64
 34  operadores_movil_2025_t3                                             31 non-null     int64
 35  presencia_2g_2025_t3                                                 31 non-null     int64
 36  presencia_3g_2025_t3                                                 31 non-null     int64
 37  presencia_4g_2025_t3                                                 31 non-null     int64
 38  presencia_5g_2025_t3                                                 31 non-null     int64
 39  fuente_mintic_actualizacion                                          31 non-null     object
 40  periodo_actualizacion                                                31 non-null     object
dtypes: float64(28), int64(8), object(5)
memory usage: 10.1+ KB

In [19]:
auditoria_02 = pd.DataFrame({
    "variable": df02.columns,
    "tipo": df02.dtypes.astype(str),
    "nulos": df02.isna().sum(),
    "nulos_pct": (df02.isna().mean() * 100).round(2),
    "unicos": df02.nunique(dropna=False)
})

display(auditoria_02)

,variable,tipo,nulos,nulos_pct,unicos
divipola,divipola,int64,0,0.00,31
municipio,municipio,object,0,0.00,31
departamento,departamento,object,0,0.00,1
anio,anio,int64,0,0.00,1
cobertura_internet_fijo_pct,cobertura_internet_fijo_pct,float64,1,3.23,31
hogares_con_internet_pct,hogares_con_internet_pct,float64,2,6.45,30
cobertura_movil_3g_4g_pct,cobertura_movil_3g_4g_pct,float64,1,3.23,23
suscriptores_moviles_por_100_hab,suscriptores_moviles_por_100_hab,float64,31,100.00,1
accesos_fijos,accesos_fijos,float64,31,100.00,1
accesos_moviles,accesos_moviles,float64,31,100.00,1
tecnologia_acceso_fijo,tecnologia_acceso_fijo,float64,31,100.00,1
cobertura_2g_pct,cobertura_2g_pct,float64,31,100.00,1
cobertura_3g_pct,cobertura_3g_pct,float64,31,100.00,1
cobertura_4g_pct,cobertura_4g_pct,float64,31,100.00,1
cobertura_5g_pct,cobertura_5g_pct,float64,31,100.00,1
centros_digitales,centros_digitales,float64,31,100.00,1
zonas_comunitarias,zonas_comunitarias,float64,31,100.00,1
infraestructura_fibra,infraestructura_fibra,float64,31,100.00,1
operadores,operadores,float64,31,100.00,1
interrupciones_fallas_relevantes,interrupciones_fallas_relevantes,float64,31,100.00,1
fuente_base,fuente_base,object,0,0.00,1
accesos_fijos_2025_t3,accesos_fijos_2025_t3,int64,0,0.00,29
penetracion_internet_fijo_2025_t3_pct,penetracion_internet_fijo_2025_t3_pct,float64,1,3.23,31
accesos_cable_2025_t3,accesos_cable_2025_t3,float64,29,93.55,3
accesos_fiber_to_the_building_o_fiber_to_the_basement__fttb_2025_t3,accesos_fiber_to_the_building_o_fiber_to_the_b...,float64,30,96.77,2
accesos_fiber_to_the_home__ftth_2025_t3,accesos_fiber_to_the_home__ftth_2025_t3,float64,0,0.00,28
accesos_fiber_to_the_premises_2025_t3,accesos_fiber_to_the_premises_2025_t3,float64,30,96.77,2
accesos_hybrid_fiber_coaxial__hfc_2025_t3,accesos_hybrid_fiber_coaxial__hfc_2025_t3,float64,30,96.77,2
accesos_otras_tecnologías_de_fibra__antes_fttx_2025_t3,accesos_otras_tecnologías_de_fibra__antes_fttx...,float64,27,87.10,4
accesos_otras_tecnologías_inalámbricas_2025_t3,accesos_otras_tecnologías_inalámbricas_2025_t3,float64,29,93.55,3
accesos_satelital_2025_t3,accesos_satelital_2025_t3,float64,1,3.23,29
accesos_wifi_2025_t3,accesos_wifi_2025_t3,float64,26,83.87,6
accesos_wimax_2025_t3,accesos_wimax_2025_t3,float64,25,80.65,6
accesos_xdsl_2025_t3,accesos_xdsl_2025_t3,float64,29,93.55,3
operadores_movil_2025_t3,operadores_movil_2025_t3,int64,0,0.00,2
presencia_2g_2025_t3,presencia_2g_2025_t3,int64,0,0.00,1
presencia_3g_2025_t3,presencia_3g_2025_t3,int64,0,0.00,1
presencia_4g_2025_t3,presencia_4g_2025_t3,int64,0,0.00,1
presencia_5g_2025_t3,presencia_5g_2025_t3,int64,0,0.00,2
fuente_mintic_actualizacion,fuente_mintic_actualizacion,object,0,0.00,1
periodo_actualizacion,periodo_actualizacion,object,0,0.00,1

In [20]:
display(df02.head())

,divipola,municipio,departamento,anio,cobertura_internet_fijo_pct,hogares_con_internet_pct,cobertura_movil_3g_4g_pct,suscriptores_moviles_por_100_hab,accesos_fijos,accesos_moviles,...,accesos_wifi_2025_t3,accesos_wimax_2025_t3,accesos_xdsl_2025_t3,operadores_movil_2025_t3,presencia_2g_2025_t3,presencia_3g_2025_t3,presencia_4g_2025_t3,presencia_5g_2025_t3,fuente_mintic_actualizacion,periodo_actualizacion
0,27001,Quibdó,Chocó,2018,13.1238,NaN,9.68,NaN,NaN,NaN,...,37.0,96.0,29.0,4,1,1,1,1,MinTIC / Colombia TIC,2025-T3
1,27006,Acandí,Chocó,2018,0.2999,15.55,25.00,NaN,NaN,NaN,...,NaN,39.0,NaN,4,1,1,1,1,MinTIC / Colombia TIC,2025-T3
2,27025,Alto Baudó,Chocó,2018,0.0529,1.86,5.88,NaN,NaN,NaN,...,NaN,NaN,NaN,4,1,1,1,0,MinTIC / Colombia TIC,2025-T3
3,27050,Atrato,Chocó,2018,0.2232,2.20,13.33,NaN,NaN,NaN,...,NaN,NaN,NaN,4,1,1,1,0,MinTIC / Colombia TIC,2025-T3
4,27073,Bagadó,Chocó,2018,0.3150,9.06,7.69,NaN,NaN,NaN,...,NaN,NaN,NaN,4,1,1,1,0,MinTIC / Colombia TIC,2025-T3

In [21]:
variables_clave_02 = [
    "cobertura_internet_fijo_pct",
    "hogares_con_internet_pct",
    "cobertura_movil_3g_4g_pct",
    "accesos_fijos_2025_t3",
    "penetracion_internet_fijo_2025_t3_pct",
    "accesos_fiber_to_the_home__ftth_2025_t3",
    "operadores_movil_2025_t3",
    "presencia_5g_2025_t3",
]

display(
    df02[variables_clave_02].describe().T
)

,count,mean,std,min,25%,50%,75%,max
cobertura_internet_fijo_pct,30.0,1.427323,3.186192,0.043100,0.178725,0.269650,0.362100,13.123800
hogares_con_internet_pct,29.0,7.244138,7.467053,0.400000,1.920000,2.830000,13.560000,27.980000
cobertura_movil_3g_4g_pct,30.0,10.164333,5.572548,2.630000,6.505000,8.330000,13.122500,25.000000
accesos_fijos_2025_t3,31.0,826.774194,2263.515860,10.000000,101.500000,245.000000,632.000000,12699.000000
penetracion_internet_fijo_2025_t3_pct,30.0,3.463762,3.669589,0.267759,0.758623,1.455776,5.094237,13.596434
accesos_fiber_to_the_home__ftth_2025_t3,31.0,584.774194,1968.127362,2.000000,24.500000,43.000000,335.500000,10949.000000
operadores_movil_2025_t3,31.0,3.935484,0.359211,2.000000,4.000000,4.000000,4.000000,4.000000
presencia_5g_2025_t3,31.0,0.161290,0.373878,0.000000,0.000000,0.000000,0.000000,1.000000

In [22]:
display(
    df02[
        ["municipio"] + variables_clave_02
    ].sort_values(
        "cobertura_internet_fijo_pct",
        na_position="last"
    )
)

,municipio,cobertura_internet_fijo_pct,hogares_con_internet_pct,cobertura_movil_3g_4g_pct,accesos_fijos_2025_t3,penetracion_internet_fijo_2025_t3_pct,accesos_fiber_to_the_home__ftth_2025_t3,operadores_movil_2025_t3,presencia_5g_2025_t3
17,Medio Atrato,0.0431,0.56,10.00,138,1.053435,29.0,4,0
2,Alto Baudó,0.0529,1.86,5.88,85,0.267759,25.0,4,0
10,Cértegui,0.0883,1.53,16.67,293,4.649318,274.0,4,0
29,Unguía,0.1441,13.56,7.14,111,0.752236,2.0,4,0
19,Medio San Juan,0.1489,2.34,5.00,173,1.448305,65.0,4,0
30,Unión Panamericana,0.1490,20.42,20.00,1037,13.596434,944.0,4,0
12,El Carmen de Atrato,0.1557,27.98,14.29,662,7.032827,429.0,4,0
23,Río Iró,0.1762,0.40,14.29,41,0.685275,25.0,4,0
8,El Cantón del San Pablo,0.1863,2.08,10.00,259,3.691562,206.0,4,1
13,El Litoral del San Juan,0.2133,1.92,2.63,105,0.406756,4.0,4,0
3,Atrato,0.2232,2.20,13.33,42,0.603275,19.0,4,0
6,Bajo Baudó,0.2425,4.25,4.17,268,0.777781,48.0,4,0
7,Bojayá,0.2472,1.95,7.14,162,1.162540,32.0,4,0
5,Bahía Solano,0.2553,18.54,12.50,1333,11.421472,370.0,4,0
18,Medio Baudó,0.2686,0.71,17.65,98,0.571795,30.0,4,1
22,Nuquí,0.2707,15.03,22.22,348,1.880878,129.0,4,0
1,Acandí,0.2999,15.55,25.00,837,5.200050,369.0,4,1
16,Lloró,0.3054,2.18,7.69,59,0.549093,34.0,4,0
27,Sipí,0.3081,2.83,8.33,106,2.893013,24.0,4,0
15,Juradó,0.3087,12.80,11.11,106,1.387980,2.0,4,0
4,Bagadó,0.3150,9.06,7.69,68,0.568609,7.0,4,0
25,Riosucio,0.3174,2.77,6.45,878,1.360312,15.0,4,0
20,Nóvita,0.3770,15.58,7.14,504,4.776798,302.0,4,0
9,Carmen del Darién,0.4506,1.69,6.25,245,1.090537,100.0,4,0
26,San José del Palmar,1.0970,3.82,8.33,85,1.463247,43.0,4,0
28,Tadó,1.9778,5.70,4.35,515,2.515140,442.0,4,0
11,Condoto,2.7695,5.13,6.67,1461,10.301065,1374.0,4,0
14,Istmina,8.2956,15.89,5.00,2300,6.683327,1801.0,4,1
24,Río Quito,10.0086,1.75,8.33,602,6.475904,25.0,4,0
0,Quibdó,13.1238,NaN,9.68,12699,8.646128,10949.0,4,1
21,Nuevo Belén de Bajirá,NaN,NaN,NaN,10,NaN,10.0,2,0

In [23]:
for i, col in enumerate(df02.columns):
    print(f"{i:02d} | {col}")

00 | divipola
01 | municipio
02 | departamento
03 | anio
04 | cobertura_internet_fijo_pct
05 | hogares_con_internet_pct
06 | cobertura_movil_3g_4g_pct
07 | suscriptores_moviles_por_100_hab
08 | accesos_fijos
09 | accesos_moviles
10 | tecnologia_acceso_fijo
11 | cobertura_2g_pct
12 | cobertura_3g_pct
13 | cobertura_4g_pct
14 | cobertura_5g_pct
15 | centros_digitales
16 | zonas_comunitarias
17 | infraestructura_fibra
18 | operadores
19 | interrupciones_fallas_relevantes
20 | fuente_base
21 | accesos_fijos_2025_t3
22 | penetracion_internet_fijo_2025_t3_pct
23 | accesos_cable_2025_t3
24 | accesos_fiber_to_the_building_o_fiber_to_the_basement__fttb_2025_t3
25 | accesos_fiber_to_the_home__ftth_2025_t3
26 | accesos_fiber_to_the_premises_2025_t3
27 | accesos_hybrid_fiber_coaxial__hfc_2025_t3
28 | accesos_otras_tecnologías_de_fibra__antes_fttx_2025_t3
29 | accesos_otras_tecnologías_inalámbricas_2025_t3
30 | accesos_satelital_2025_t3
31 | accesos_wifi_2025_t3
32 | accesos_wimax_2025_t3
33 | accesos_xdsl_2025_t3
34 | operadores_movil_2025_t3
35 | presencia_2g_2025_t3
36 | presencia_3g_2025_t3
37 | presencia_4g_2025_t3
38 | presencia_5g_2025_t3
39 | fuente_mintic_actualizacion
40 | periodo_actualizacion

In [24]:
variables_clave_02 = [
    "cobertura_internet_fijo_pct",
    "hogares_con_internet_pct",
    "cobertura_movil_3g_4g_pct",
    "accesos_fijos_2025_t3",
    "penetracion_internet_fijo_2025_t3_pct",
    "accesos_fiber_to_the_home__ftth_2025_t3",
    "operadores_movil_2025_t3",
    "presencia_5g_2025_t3",
]

existentes = [
    col for col in variables_clave_02
    if col in df02.columns
]

faltantes = [
    col for col in variables_clave_02
    if col not in df02.columns
]

print("Variables encontradas:")
print(*existentes, sep="\n")

print("\nVariables no encontradas:")
print(*faltantes, sep="\n")

Variables encontradas:
cobertura_internet_fijo_pct
hogares_con_internet_pct
cobertura_movil_3g_4g_pct
accesos_fijos_2025_t3
penetracion_internet_fijo_2025_t3_pct
accesos_fiber_to_the_home__ftth_2025_t3
operadores_movil_2025_t3
presencia_5g_2025_t3

Variables no encontradas:

In [25]:
variables_2025 = [
    "accesos_fijos_2025_t3",
    "penetracion_internet_fijo_2025_t3_pct",
    "accesos_fiber_to_the_home__ftth_2025_t3",
    "operadores_movil_2025_t3",
    "presencia_5g_2025_t3"
]

display(
    df02[variables_2025].describe().T
)

,count,mean,std,min,25%,50%,75%,max
accesos_fijos_2025_t3,31.0,826.774194,2263.515860,10.000000,101.500000,245.000000,632.000000,12699.000000
penetracion_internet_fijo_2025_t3_pct,30.0,3.463762,3.669589,0.267759,0.758623,1.455776,5.094237,13.596434
accesos_fiber_to_the_home__ftth_2025_t3,31.0,584.774194,1968.127362,2.000000,24.500000,43.000000,335.500000,10949.000000
operadores_movil_2025_t3,31.0,3.935484,0.359211,2.000000,4.000000,4.000000,4.000000,4.000000
presencia_5g_2025_t3,31.0,0.161290,0.373878,0.000000,0.000000,0.000000,0.000000,1.000000

In [26]:
for col in variables_2025:
    print(f"\n{col}")
    print("Nulos:", df02[col].isna().sum())
    print("Mínimo:", df02[col].min())
    print("Máximo:", df02[col].max())

accesos_fijos_2025_t3
Nulos: 0
Mínimo: 10
Máximo: 12699

penetracion_internet_fijo_2025_t3_pct
Nulos: 1
Mínimo: 0.2677587021578201
Máximo: 13.596433722302349

accesos_fiber_to_the_home__ftth_2025_t3
Nulos: 0
Mínimo: 2.0
Máximo: 10949.0

operadores_movil_2025_t3
Nulos: 0
Mínimo: 2
Máximo: 4

presencia_5g_2025_t3
Nulos: 0
Mínimo: 0
Máximo: 1

In [27]:
print("Duplicados DIVIPOLA:", df02["divipola"].duplicated().sum())
print("\nAño histórico:")
print(df02["anio"].unique())

print("\nPeriodo actualización:")
print(df02["periodo_actualizacion"].unique())

Duplicados DIVIPOLA: 0

Año histórico:
[2018]

Periodo actualización:
['2025-T3']

Dataset 03

In [28]:
path_03 = datasets["03_conectividad_fisica"]
df03 = pd.read_csv(path_03)
print("shape:",df03.shape)

print("\nColumnas:")
for i,col in enumerate(df03.columns, start=1):
    print(f"{i:02d} | {col}")

shape: (30, 13)

Columnas:
01 | divipola
02 | brecha_componente_carretero
03 | brecha_componente_fluvial
04 | indice_brecha_conectividad_fisica
05 | categoria_o_ciudad_referencia
06 | gini_movilidad
07 | gini_movilidad_valido
08 | fuente_brecha
09 | fuente_gini_movilidad
10 | estado_brecha
11 | estado_gini
12 | observacion_brecha
13 | observacion_gini

In [29]:
df03.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   divipola                           30 non-null     int64
 1   brecha_componente_carretero        30 non-null     float64
 2   brecha_componente_fluvial          30 non-null     float64
 3   indice_brecha_conectividad_fisica  30 non-null     float64
 4   categoria_o_ciudad_referencia      30 non-null     object
 5   gini_movilidad                     29 non-null     float64
 6   gini_movilidad_valido              30 non-null     bool
 7   fuente_brecha                      30 non-null     object
 8   fuente_gini_movilidad              30 non-null     object
 9   estado_brecha                      30 non-null     object
 10  estado_gini                        30 non-null     object
 11  observacion_brecha                 30 non-null     object
 12  observacion_gini                   1 non-null      object
dtypes: bool(1), float64(4), int64(1), object(7)
memory usage: 3.0+ KB

In [30]:
auditoria_03 = pd.DataFrame({
    "variable": df03.columns,
    "tipo": df03.dtypes.astype(str),
    "nulos": df03.isna().sum(),
    "nulos_pct": (df03.isna().mean() * 100).round(2),
    "unicos": df03.nunique(dropna=False)
})

display(auditoria_03)

,variable,tipo,nulos,nulos_pct,unicos
divipola,divipola,int64,0,0.00,30
brecha_componente_carretero,brecha_componente_carretero,float64,0,0.00,18
brecha_componente_fluvial,brecha_componente_fluvial,float64,0,0.00,2
indice_brecha_conectividad_fisica,indice_brecha_conectividad_fisica,float64,0,0.00,19
categoria_o_ciudad_referencia,categoria_o_ciudad_referencia,object,0,0.00,5
gini_movilidad,gini_movilidad,float64,1,3.33,30
gini_movilidad_valido,gini_movilidad_valido,bool,0,0.00,2
fuente_brecha,fuente_brecha,object,0,0.00,1
fuente_gini_movilidad,fuente_gini_movilidad,object,0,0.00,1
estado_brecha,estado_brecha,object,0,0.00,1
estado_gini,estado_gini,object,0,0.00,1
observacion_brecha,observacion_brecha,object,0,0.00,1
observacion_gini,observacion_gini,object,29,96.67,2

In [31]:
display(df03.head(10))

,divipola,brecha_componente_carretero,brecha_componente_fluvial,indice_brecha_conectividad_fisica,categoria_o_ciudad_referencia,gini_movilidad,gini_movilidad_valido,fuente_brecha,fuente_gini_movilidad,estado_brecha,estado_gini,observacion_brecha,observacion_gini
0,27001,0.000000,0.1,0.100000,Ciudad Principal,0.477117,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
1,27006,0.900000,0.0,0.900000,Desconectado,0.446825,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
2,27025,0.746875,0.1,0.846875,SAN FRANCISCO DE QUIBDÓ,0.681551,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
3,27050,0.063142,0.1,0.163142,SAN FRANCISCO DE QUIBDÓ,0.581294,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
4,27073,0.900000,0.0,0.900000,Desconectado,0.035941,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
5,27075,0.900000,0.1,1.000000,Desconectado,0.427158,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
6,27077,0.900000,0.1,1.000000,Desconectado,0.478101,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
7,27099,0.900000,0.1,1.000000,Desconectado,0.499856,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
8,27135,0.193055,0.1,0.293055,SAN FRANCISCO DE QUIBDÓ,0.363636,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN
9,27150,0.900000,0.1,1.000000,Desconectado,0.412695,True,IndiceBrechaConectividadFisica.csv,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,🟡 Adaptar — indicador existente; validar metod...,No se reconstruye. El archivo no documenta año...,NaN

Dataset 03: diagnóstico inicial

Tenemos 30 municipios, no 31. Eso significa que ya encontramos una diferencia con el Dataset 01.

Además:

indice_brecha_conectividad_fisica: 30/30 completos
brecha_componente_carretero: 30/30
brecha_componente_fluvial: 30/30
gini_movilidad: 29/30
gini_movilidad_valido: 30/30
DIVIPOLA: 30 únicos
No hay duplicados aparentes.

Por tanto, la brecha de conectividad física está bastante limpia.

qué municipio falta respecto al universo de 31 municipios.

In [32]:
# Comparar universo del Dataset 01 vs Dataset 03

divipola_01 = set(df01["divipola"].dropna().astype(int))
divipola_03 = set(df03["divipola"].dropna().astype(int))

faltantes_03 = sorted(divipola_01 - divipola_03)
extras_03 = sorted(divipola_03 - divipola_01)

print("Municipios en Dataset 01:", len(divipola_01))
print("Municipios en Dataset 03:", len(divipola_03))

print("\nFaltantes en Dataset 03:")
print(faltantes_03)

print("\nDIVIPOLA adicionales en Dataset 03:")
print(extras_03)

Municipios en Dataset 01: 31
Municipios en Dataset 03: 30

Faltantes en Dataset 03:
[27493]

DIVIPOLA adicionales en Dataset 03:
[]

In [33]:
# Mostrar nombres del municipio faltante en Dataset 01

df01.loc[
    df01["divipola"].isin(faltantes_03),
    ["divipola", "municipio"]
]

    divipola              municipio
21     27493  Nuevo Belén de Bajirá

verificamos que contiene y que mide observación_gini.

In [34]:
ROOT = Path(r"C:\Users\USUARIO\Desktop\Colombia_en_datos")

for archivo in ROOT.rglob("*GiniMovilidad*"):
    print(archivo)

C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\GiniMovilidad.csv

In [35]:
for archivo in ROOT.rglob("*Gini*"):
    print(archivo)

C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jedi\third_party\typeshed\stubs\workalendar\workalendar\usa\virginia.pyi
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jedi\third_party\typeshed\stubs\workalendar\workalendar\usa\west_virginia.pyi
C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\GiniMovilidad.csv

In [36]:
from pathlib import Path

ROOT = Path(r"C:\Users\USUARIO\Desktop\Colombia_en_datos")

carpetas_proyecto = [
    ROOT / "episodios",
    ROOT / "src",
    ROOT / "tests",
]

for carpeta in carpetas_proyecto:
    if carpeta.exists():
        for archivo in carpeta.rglob("*"):
            if archivo.is_file() and "gini" in archivo.name.lower():
                print(archivo)

C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\GiniMovilidad.csv

In [37]:
for carpeta in carpetas_proyecto:
    if carpeta.exists():
        for archivo in carpeta.rglob("*GiniMovilidad*"):
            print(archivo)

C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\GiniMovilidad.csv

In [38]:
df03[
    [
        "divipola",
        "gini_movilidad",
        "gini_movilidad_valido",
        "fuente_gini_movilidad",
        "estado_gini",
        "observacion_gini"
    ]
].head(10)

,divipola,gini_movilidad,gini_movilidad_valido,fuente_gini_movilidad,estado_gini,observacion_gini
0,27001,0.477117,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
1,27006,0.446825,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
2,27025,0.681551,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
3,27050,0.581294,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
4,27073,0.035941,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
5,27075,0.427158,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
6,27077,0.478101,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
7,27099,0.499856,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
8,27135,0.363636,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN
9,27150,0.412695,True,GiniMovilidad.csv,🟡 Adaptar — indicador existente; validar metod...,NaN

In [39]:
print(df03["fuente_gini_movilidad"].unique())
print(df03["estado_gini"].unique())
print(df03["observacion_gini"].dropna().unique())

['GiniMovilidad.csv']
['🟡 Adaptar — indicador existente; validar metodología/fuente']
['Valor original -1; tratado como faltante porque no pertenece al rango 0–1.']

Hacemos un merge con un nuevo archivo que contiene el gini de todos los municipios de los cuales solo necesitamos los del departamento del chocó.

In [40]:
ROOT = Path(r"C:\Users\USUARIO\Desktop\Colombia_en_datos")
RAW = ROOT / "episodios" / "002_EL_chocó" / "Data" / "raw"

ruta_gini = RAW / "GiniMovilidad.csv"

df_gini = pd.read_csv(
    ruta_gini,
    sep="|",
    decimal=","
)

print(df_gini.shape)
display(df_gini.head())
print(df_gini.columns.tolist())

(1101, 5)

   DaneDep Departamento  DaneMun   Municipio      Gini
0        5    Antioquia     5001    Medellín  0.393334
1        5    Antioquia     5002   Abejorral  0.519149
2        5    Antioquia     5004    Abriaquí  0.449674
3        5    Antioquia     5021  Alejandría  0.477745
4        5    Antioquia     5030       Amagá  0.508876

['DaneDep', 'Departamento', 'DaneMun', 'Municipio', 'Gini']

Normalizamos la fuente

In [41]:
df_gini = df_gini.rename(columns={
    "DaneMun": "divipola",
    "Gini": "gini_movilidad"
})

df_gini["divipola"] = pd.to_numeric(
    df_gini["divipola"],
    errors="coerce"
).astype("Int64")

df_gini["gini_movilidad"] = pd.to_numeric(
    df_gini["gini_movilidad"],
    errors="coerce"
)

validamos que la fuente no tenga municipios repetidos

In [42]:
print("Filas:", len(df_gini))
print("DIVIPOLA únicos:", df_gini["divipola"].nunique())
print("Duplicados DIVIPOLA:", df_gini["divipola"].duplicated().sum())

Filas: 1101
DIVIPOLA únicos: 1101
Duplicados DIVIPOLA: 0

Creamos la variable de validez

In [43]:
df_gini["gini_movilidad_valido"] = (
    df_gini["gini_movilidad"].between(0, 1)
)

# Los valores fuera de [0,1] pasan a faltante
df_gini.loc[
    ~df_gini["gini_movilidad_valido"],
    "gini_movilidad"
] = pd.NA

In [44]:
display(
    df_gini[
        ["divipola", "Municipio", "gini_movilidad", "gini_movilidad_valido"]
    ].head(10)
)

print(
    "Valores inválidos:",
    (~df_gini["gini_movilidad_valido"]).sum()
)

   divipola    Municipio  gini_movilidad  gini_movilidad_valido
0      5001     Medellín        0.393334                   True
1      5002    Abejorral        0.519149                   True
2      5004     Abriaquí        0.449674                   True
3      5021   Alejandría        0.477745                   True
4      5030        Amagá        0.508876                   True
5      5031       Amalfi        0.439173                   True
6      5034        Andes        0.468518                   True
7      5036  Angelópolis        0.569502                   True
8      5038    Angostura        0.579117                   True
9      5040        Anorí        0.391191                   True

Valores inválidos: 4

Hacemos el merge con Dataset 03

In [45]:
n_antes = len(df03)

print("Municipios Dataset 03 antes:", n_antes)

Municipios Dataset 03 antes: 30

In [49]:
df03 = df03.merge(
    df_gini[
        [
            "divipola",
            "gini_movilidad",
            "gini_movilidad_valido"
        ]
    ],
    on="divipola",
    how="left",
    validate="one_to_one"
)

In [50]:
validate="one_to_one"

In [51]:
print("Municipios después:", len(df03))
print("DIVIPOLA únicos:", df03["divipola"].nunique())
print("Duplicados:", df03["divipola"].duplicated().sum())

print("\nGini válidos:", df03["gini_movilidad"].notna().sum())
print("Gini faltantes:", df03["gini_movilidad"].isna().sum())

Municipios después: 30
DIVIPOLA únicos: 30
Duplicados: 0

Gini válidos: 29
Gini faltantes: 1

In [52]:
[c for c in df03.columns if "gini" in c.lower()]

['gini_movilidad_x',
 'gini_movilidad_valido_x',
 'fuente_gini_movilidad',
 'estado_gini',
 'observacion_gini',
 'gini_movilidad_y',
 'gini_movilidad_valido_y',
 'gini_movilidad',
 'gini_movilidad_valido']

In [53]:
df03.columns.to_list()

['divipola',
 'brecha_componente_carretero',
 'brecha_componente_fluvial',
 'indice_brecha_conectividad_fisica',
 'categoria_o_ciudad_referencia',
 'gini_movilidad_x',
 'gini_movilidad_valido_x',
 'fuente_brecha',
 'fuente_gini_movilidad',
 'estado_brecha',
 'estado_gini',
 'observacion_brecha',
 'observacion_gini',
 'gini_movilidad_y',
 'gini_movilidad_valido_y',
 'gini_movilidad',
 'gini_movilidad_valido']

In [54]:
df03[
    [
        "divipola",
        "gini_movilidad_x",
        "gini_movilidad_valido_x",
        "gini_movilidad_y",
        "gini_movilidad_valido_y"
    ]
].head()

,divipola,gini_movilidad_x,gini_movilidad_valido_x,gini_movilidad_y,gini_movilidad_valido_y
0,27001,0.477117,True,0.477117,True
1,27006,0.446825,True,0.446825,True
2,27025,0.681551,True,0.681551,True
3,27050,0.581294,True,0.581294,True
4,27073,0.035941,True,0.035941,True

In [55]:
print(
    df03[
        [c for c in df03.columns if "gini" in c.lower()]
    ].head()
)

   gini_movilidad_x  gini_movilidad_valido_x fuente_gini_movilidad  \
0          0.477117                     True     GiniMovilidad.csv
1          0.446825                     True     GiniMovilidad.csv
2          0.681551                     True     GiniMovilidad.csv
3          0.581294                     True     GiniMovilidad.csv
4          0.035941                     True     GiniMovilidad.csv

                                         estado_gini observacion_gini  \
0  🟡 Adaptar — indicador existente; validar metod...              NaN
1  🟡 Adaptar — indicador existente; validar metod...              NaN
2  🟡 Adaptar — indicador existente; validar metod...              NaN
3  🟡 Adaptar — indicador existente; validar metod...              NaN
4  🟡 Adaptar — indicador existente; validar metod...              NaN

   gini_movilidad_y  gini_movilidad_valido_y  gini_movilidad  \
0          0.477117                     True        0.477117
1          0.446825                     True        0.446825
2          0.681551                     True        0.681551
3          0.581294                     True        0.581294
4          0.035941                     True        0.035941

   gini_movilidad_valido
0                   True
1                   True
2                   True
3                   True
4                   True

In [56]:
comparacion_gini = (
    df03["gini_movilidad_x"].fillna(-999)
    == df03["gini_movilidad_y"].fillna(-999)
)

print("Valores idénticos:", comparacion_gini.all())
print("Diferencias:", (~comparacion_gini).sum())

Valores idénticos: True
Diferencias: 0

In [57]:
df03 = df03.drop(
    columns=[
        "gini_movilidad_y",
        "gini_movilidad_valido_y"
    ]
)

df03 = df03.rename(
    columns={
        "gini_movilidad_x": "gini_movilidad",
        "gini_movilidad_valido_x": "gini_movilidad_valido"
    }
)

In [58]:
print(df03.shape)

print(
    df03[
        [
            "divipola",
            "gini_movilidad",
            "gini_movilidad_valido"
        ]
    ].head()
)

print("\nColumnas Gini:")
print([c for c in df03.columns if "gini" in c.lower()])

(30, 15)
   divipola  gini_movilidad  gini_movilidad  gini_movilidad_valido  \
0     27001        0.477117        0.477117                   True
1     27006        0.446825        0.446825                   True
2     27025        0.681551        0.681551                   True
3     27050        0.581294        0.581294                   True
4     27073        0.035941        0.035941                   True

   gini_movilidad_valido
0                   True
1                   True
2                   True
3                   True
4                   True

Columnas Gini:
['gini_movilidad', 'gini_movilidad_valido', 'fuente_gini_movilidad', 'estado_gini', 'observacion_gini', 'gini_movilidad', 'gini_movilidad_valido']

In [59]:
display(
    df03.loc[
        df03["divipola"].isin([27250, 27493]),
        [
            "divipola",
            "gini_movilidad",
            "gini_movilidad_valido",
            "fuente_gini_movilidad",
            "observacion_gini"
        ]
    ]
)

,divipola,gini_movilidad,gini_movilidad,gini_movilidad_valido,gini_movilidad_valido,fuente_gini_movilidad,observacion_gini
13,27250,NaN,NaN,False,False,GiniMovilidad.csv,Valor original -1; tratado como faltante porqu...

In [60]:
PROCESSED = (
    ROOT
    / "episodios"
    / "002_EL_chocó"
    / "Data"
    / "processed"
)

PROCESSED.mkdir(parents=True, exist_ok=True)

print(PROCESSED)

C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\processed

In [61]:
ruta_salida_03 = (
    PROCESSED
    / "dataset_03_conectividad_fisica_choco.csv"
)

df03.to_csv(
    ruta_salida_03,
    index=False,
    encoding="utf-8-sig"
)

print(f"Guardado en: {ruta_salida_03}")

Guardado en: C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\processed\dataset_03_conectividad_fisica_choco.csv

In [68]:
assert len(df03) == 30
assert df03["divipola"].nunique() == 30
assert df03["divipola"].duplicated().sum() == 0

assert df03["indice_brecha_conectividad_fisica"].notna().all()
assert df03["brecha_componente_carretero"].notna().all()
assert df03["brecha_componente_fluvial"].notna().all()

assert df03["gini_movilidad"].between(0, 1).sum() == 29

print("Dataset 03 supera las pruebas básicas de integridad.")

AttributeError: 'DataFrame' object has no attribute 'between'

In [70]:
from pathlib import Path

ROOT = Path(r"C:\Users\USUARIO\Desktop\Colombia_en_datos")

RAW = (
    ROOT
    / "episodios"
    / "002_EL_chocó"
    / "Data"
    / "raw"
)

for archivo in sorted(RAW.iterdir()):
    print(archivo.name)

dataset_01_poblacion_territorio_choco.csv
dataset_01_poblacion_territorio_choco_definitivo.csv
dataset_02_conectividad_digital_choco_v2.csv
dataset_03_conectividad_fisica_choco_final.csv
dataset_05_condiciones_socioeconomicas_choco_final.csv
dataset_06_informacion_comunicacion_choco_v1.xlsx
dataset_07_emergencias_desastres_choco_final(1).xlsx
dataset_08_capacidad_institucional_choco_v1.xlsx
dataset_09_inversion_publica_infraestructura_choco_v1.xlsx
dataset_10_historia_evidencia_cualitativa_choco_v1.xlsx
Divipola_Serv_PuntosCentrosPoblados2013I.pitemx
Documento_Dataset_03_Conectividad_Fisica_Choco.docx
GiniMovilidad.csv
TerriData_Dim4.xlsx
TerriData_Dim5.xlsx
Visor-TCCN.xlsx

Vamos a construir el Dataset 04 con archivos que ya tenemos en Raw.

identificar las hojas

In [71]:
ruta_dim4 = RAW / "TerriData_Dim4.xlsx"

xls_dim4 = pd.ExcelFile(ruta_dim4)

print("Hojas disponibles:")
for hoja in xls_dim4.sheet_names:
    print("-", hoja)

Hojas disponibles:
- Hoja01

In [72]:
df_dim4 = pd.read_excel(
    RAW / "TerriData_Dim4.xlsx"
)

print(df_dim4.shape)
print(df_dim4.columns.tolist())
display(df_dim4.head())

(452990, 13)
['Código Departamento', 'Departamento', 'Código Entidad', 'Entidad', 'Dimensión', 'Subcategoría', 'Indicador', 'Dato Numérico', 'Dato Cualitativo', 'Año', 'Mes', 'Fuente', 'Unidad de Medida']

,Código Departamento,Departamento,Código Entidad,Entidad,Dimensión,Subcategoría,Indicador,Dato Numérico,Dato Cualitativo,Año,Mes,Fuente,Unidad de Medida
0,41,Huila,41503,Oporapa,Educación,Acceso a la educación,Cobertura bruta en transición,"47,89",NaN,2005,12,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1,41,Huila,41518,Paicol,Educación,Acceso a la educación,Cobertura bruta en transición,"55,56",NaN,2005,12,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
2,41,Huila,41524,Palermo,Educación,Acceso a la educación,Cobertura bruta en transición,"67,32",NaN,2005,12,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
3,41,Huila,41530,Palestina,Educación,Acceso a la educación,Cobertura bruta en transición,"63,77",NaN,2005,12,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
4,41,Huila,41548,Pital,Educación,Acceso a la educación,Cobertura bruta en transición,"42,15",NaN,2005,12,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)

In [73]:
df_dim4_choco = df_dim4[
    df_dim4["Departamento"].str.strip().str.lower() == "chocó"
].copy()

print("Filas Chocó:", len(df_dim4_choco))
print("Municipios:", df_dim4_choco["Entidad"].nunique())
print("DIVIPOLA:", df_dim4_choco["Código Entidad"].nunique())

Filas Chocó: 12314
Municipios: 31
DIVIPOLA: 31

In [74]:
display(
    df_dim4_choco[
        [
            "Código Entidad",
            "Entidad",
            "Subcategoría",
            "Indicador",
            "Año",
            "Fuente",
            "Unidad de Medida"
        ]
    ].head(20)
)

,Código Entidad,Entidad,Subcategoría,Indicador,Año,Fuente,Unidad de Medida
1083,27000,Chocó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1084,27001,Quibdó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1085,27006,Acandí,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1086,27025,Alto Baudó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1087,27050,Atrato,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1088,27073,Bagadó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1089,27075,Bahía Solano,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1090,27077,Bajo Baudó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1091,27099,Bojayá,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1092,27135,El Cantón del San Pablo,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1093,27150,Carmen del Darién,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1094,27160,Cértegui,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1095,27205,Condoto,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1096,27245,El Carmen de Atrato,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1097,27250,El Litoral del San Juan,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1098,27361,Istmina,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1099,27372,Juradó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1100,27413,Lloró,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1101,27425,Medio Atrato,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)
1102,27430,Medio Baudó,Acceso a la educación,Cobertura bruta en transición,2005,Ministerio de Educación Nacional,Porcentaje (el valor está multiplicado por 100)

In [75]:
tabla_indicadores_dim4 = (
    df_dim4_choco
    .groupby(
        ["Subcategoría", "Indicador"],
        dropna=False
    )
    .agg(
        registros=("Código Entidad", "size"),
        municipios=("Código Entidad", "nunique"),
        anio_min=("Año", "min"),
        anio_max=("Año", "max")
    )
    .reset_index()
    .sort_values(
        ["Subcategoría", "Indicador"]
    )
)

display(tabla_indicadores_dim4)

,Subcategoría,Indicador,registros,municipios,anio_min,anio_max
0,Acceso a la educación,Cobertura bruta en educación - Total,620,31,2005,2024
1,Acceso a la educación,Cobertura bruta en educación básica,620,31,2005,2024
2,Acceso a la educación,Cobertura bruta en educación media,620,31,2005,2024
3,Acceso a la educación,Cobertura bruta en educación primaria,620,31,2005,2024
4,Acceso a la educación,Cobertura bruta en educación secundaria,620,31,2005,2024
5,Acceso a la educación,Cobertura bruta en transición,620,31,2005,2024
6,Acceso a la educación,Cobertura en educación superior,620,31,2005,2024
7,Acceso a la educación,Cobertura neta en educación - Total,620,31,2005,2024
8,Acceso a la educación,Cobertura neta en educación básica,620,31,2005,2024
9,Acceso a la educación,Cobertura neta en educación media,620,31,2005,2024
10,Acceso a la educación,Cobertura neta en educación primaria,620,31,2005,2024
11,Acceso a la educación,Cobertura neta en educación secundaria,620,31,2005,2024
12,Acceso a la educación,Cobertura neta en transición,620,31,2005,2024
13,Acceso a la educación,Tasa de tránsito inmediato a la educación supe...,341,31,2014,2024
14,Acceso a la educación desagregado por sexo,Cobertura neta en educación básica - Hombres,8,1,2014,2022
15,Acceso a la educación desagregado por sexo,Cobertura neta en educación básica - Mujeres,8,1,2014,2022
16,Acceso a la educación desagregado por sexo,Cobertura neta en educación total - Hombres,8,1,2014,2022
17,Acceso a la educación desagregado por sexo,Cobertura neta en educación total - Mujeres,8,1,2014,2022
18,Calidad,"Número de niños, niñas y mujeres gestantes con...",279,31,2015,2023
19,Calidad,Porcentaje de niños y niñas cuyas familias par...,248,31,2015,2022
20,Calidad,Porcentaje de niños y niñas de preescolar que ...,93,31,2023,2025
21,Calidad,Porcentaje de niños y niñas en primera infanci...,248,31,2015,2022
22,Calidad,Porcentaje de niños y niñas en servicios de ed...,310,31,2018,2022
23,Calidad,Puntaje promedio Pruebas Saber 11 - Lectura cr...,403,31,2010,2022
24,Calidad,Puntaje promedio Pruebas Saber 11 - Matemáticas,403,31,2010,2022
25,Logro,Años de educación personas de 15 y más años,7,1,2014,2020
26,Logro,Porcentaje de asistencia de 5 a 24 años (Censo),30,30,2018,2018
27,Logro,Porcentaje de asistencia de 5 a 24 años Rural ...,30,30,2018,2018
28,Logro,Porcentaje de asistencia de 5 a 24 años Urbana...,30,30,2018,2018
29,Logro,Tasa de Analfabetismo (Censo),30,30,2018,2018
30,Logro,Tasa de Analfabetismo Rural (Censo),30,30,2018,2018
31,Logro,Tasa de Analfabetismo Urbana (Censo),30,30,2018,2018
32,Logro,Tasa de analfabetismo de personas de 15 y más ...,6,1,2014,2019
33,Permanencia y rezago,Tasa de deserción intra-anual del sector no of...,30,3,2015,2024
34,Permanencia y rezago,Tasa de deserción intra-anual del sector ofici...,682,31,2003,2024
35,Permanencia y rezago,Tasa de deserción intra-anual en educación (De...,310,31,2015,2024
36,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,682,31,2003,2024

In [76]:
print(
    df_dim4_choco["Subcategoría"]
    .value_counts()
)

Subcategoría
Acceso a la educación                         8401
Calidad                                       1984
Permanencia y rezago                          1704
Logro                                          193
Acceso a la educación desagregado por sexo      32
Name: count, dtype: int64

In [77]:
print(
    df_dim4_choco["Dimensión"]
    .value_counts()
)

Dimensión
Educación    12314
Name: count, dtype: int64

In [78]:
# Indicadores y variables relacionadas con el Dataset 04
# dentro de los archivos/documentación que ya tenemos localmente

root = Path(r"C:\Users\USUARIO\Desktop\Colombia_en_datos")

for archivo in root.rglob("*"):
    if archivo.is_file():
        nombre = archivo.name.lower()
        
        if any(
            termino in nombre
            for termino in [
                "04",
                "dataset_04",
                "educacion",
                "educación",
                "institucional"
            ]
        ):
            print(archivo)

C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\12\1afaf0d4fd1c0f730de149b04527370df1d275
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\16\8be7eaf09a093a8d4bec04593eb998139420e7
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\21\5b05881c041c281aede639de312d162466f90c
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\4d\77504ba0fd1e06f7eee15b460e2c70380fa291
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\52\2606a911385376418e7e20ed04feed82d6512f
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\52\6328c515c8cdb215b06ce4a23cb8154a0450db
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\57\3fc76d84141e47cfe639c25f125e8ff7683a04
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\5a\3e07e58552a958b2d3b904af23dedae12ffc95
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\5b\04be48a124ce3611a8ea9a8f25d0bc80ad5078
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\5c\158ecf1191f00cf1ad98337312bc047547a305
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\5e\87d46db69920a773eb1b6eb0b040d727144eb1
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\6c\b0ca83402a5546e84695c9e04feb26401a3f05
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\80\37197cd9e0415d6e3a9eeb2da20cb0b7ba5e19
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\88\c0f30e3fe0a170426910f65ce2828217cb8735
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\8e\2e4c426e310898504997c9e862b0341f0c0c48
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\a2\578fd64add5e304268b560c72af9aa800854ed
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\a9\5b0def3195a3c994d0929e79af39ae204a5981
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\b3\83f04d5521d815542d46085de76bf85c006e54
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\b7\1a184437c0a80a78a8076ab5ab2e89c3564204
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\b9\aeb51022e2f8204e555233015c8da407539ed2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\c8\dee1d3022a3ed25e045a0865e935f10a4c0764
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\d0\c73ae833b04a4da75a77ff9d236704204851d1
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\e7\270467bd86cd7ed19d03db30f7527fada3b74e
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\e9\bcc0994004c0d2b65e7ef45beaa4b3e7cf3066
C:\Users\USUARIO\Desktop\Colombia_en_datos\.git\objects\fb\7a38a8ac7c07c0ad8de1493849be8f1248404d
C:\Users\USUARIO\Desktop\Colombia_en_datos\.ruff_cache\0.16.1\13160600775730436212
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\fastjsonschema\draft04.py
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\fastjsonschema\__pycache__\draft04.cpython-311.pyc
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jedi\third_party\typeshed\stdlib\encodings\euc_jis_2004.pyi
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jedi\third_party\typeshed\stdlib\encodings\iso2022_jp_2004.pyi
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jedi\third_party\typeshed\stdlib\encodings\kz1048.pyi
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jedi\third_party\typeshed\stdlib\encodings\shift_jis_2004.pyi
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\04103ccddd44c0a5.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\04dd5282f2256565.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\2004.2f631b96f5439cea.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\3048300eb9b40fad.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\4204.25e6678031ce64da.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\4385.29cdf9dd304b8c00.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\5560.d4dcb973b404cdb2.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\5633.af0479b6c739b55f.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\5695.5cbe004c8157ef7a.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\6046.dc0342f041d9a57e.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\6506.c5495027d50f4c04.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\7045.803530a771e0dcfb.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\7904.183ecadda1cbac81.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\8680.bb5e6e1f4a04dd0d.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\8774.ed0400e7546c7247.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\9001.4f10419147a67141.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\static\d5c28b04b1641433.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\2e4b1f04fcd05047.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\4c8b25a1a9337045.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\4cd6c589c004a6a7.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\504cbcba1f63591b.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\a804b352cb9fec1a.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\affd121385d0442d.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\c03f046bccd789d0.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\c8a7e0d049e965fa.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyterlab\galata\@jupyterlab\galata-extension\static\e0b04bd488f953f4.woff2
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\jupyter_server\templates\404.html
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\matplotlib\mpl-data\sample_data\s1045.ima.gz
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\04103ccddd44c0a5.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\04dd5282f2256565.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\2762.8a4d047696d5bdfe.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\3048300eb9b40fad.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\3245.b058a04ff180041e.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\3276.541abdf74740409a.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\3289.6a0c8550c8932040.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\3604.7d76b2be66a17071.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\3854.ba0461b790b27313.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\4793.04f4ff1faf9ebd8f.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\6219.a9163047efe69e17.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\6338.d91042985c244030.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\7161.045ede8f9ce150dd.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\7604.9bfcdc511f58590f.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\8041.6732ac73fc610c56.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\9301.16980451252fc694.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\9612.08613b585c048838.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\notebook\static\d5c28b04b1641433.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\scipy\stats\tests\data\nist_anova\SmLs04.dat
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\wcwidth\table_grapheme_overrides\_known_8f94b404.py
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\Lib\site-packages\wcwidth\table_grapheme_overrides\__pycache__\_known_8f94b404.cpython-311.pyc
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\04103ccddd44c0a5.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\04dd5282f2256565.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\2004.2f631b96f5439cea.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\3048300eb9b40fad.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\4204.25e6678031ce64da.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\4385.29cdf9dd304b8c00.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\5560.d4dcb973b404cdb2.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\5633.af0479b6c739b55f.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\5695.5cbe004c8157ef7a.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\6046.dc0342f041d9a57e.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\6506.c5495027d50f4c04.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\7045.803530a771e0dcfb.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\7904.183ecadda1cbac81.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\8680.bb5e6e1f4a04dd0d.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\8774.ed0400e7546c7247.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\9001.4f10419147a67141.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\lab\static\d5c28b04b1641433.woff
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\lib_index_js.56f37fb50492d0d63a45.js
C:\Users\USUARIO\Desktop\Colombia_en_datos\.venv\share\jupyter\labextensions\@jupyter-widgets\jupyterlab-manager\static\lib_index_js.56f37fb50492d0d63a45.js.map
C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\dataset_08_capacidad_institucional_choco_v1.xlsx

In [79]:
from pathlib import Path
import pandas as pd

EPISODIO = Path(
    r"C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó"
)

archivos = []

for archivo in EPISODIO.rglob("*"):
    if not archivo.is_file():
        continue

    archivos.append({
        "ruta": str(archivo.relative_to(EPISODIO)),
        "nombre": archivo.name,
        "extension": archivo.suffix.lower(),
        "tamano_kb": round(archivo.stat().st_size / 1024, 2)
    })

inventario = pd.DataFrame(archivos)

display(
    inventario.sort_values("ruta").reset_index(drop=True)
)

,ruta,nombre,extension,tamano_kb
0,.gitignore,.gitignore,,0.22
1,Data\processed\dataset_03_conectividad_fisica_...,dataset_03_conectividad_fisica_choco.csv,.csv,12.70
2,Data\raw\Divipola_Serv_PuntosCentrosPoblados20...,Divipola_Serv_PuntosCentrosPoblados2013I.pitemx,.pitemx,0.43
3,Data\raw\Documento_Dataset_03_Conectividad_Fis...,Documento_Dataset_03_Conectividad_Fisica_Choco...,.docx,38.56
4,Data\raw\GiniMovilidad.csv,GiniMovilidad.csv,.csv,52.40
5,Data\raw\TerriData_Dim4.xlsx,TerriData_Dim4.xlsx,.xlsx,20301.89
6,Data\raw\TerriData_Dim5.xlsx,TerriData_Dim5.xlsx,.xlsx,28133.48
7,Data\raw\Visor-TCCN.xlsx,Visor-TCCN.xlsx,.xlsx,11597.92
8,Data\raw\dataset_01_poblacion_territorio_choco...,dataset_01_poblacion_territorio_choco.csv,.csv,1.70
9,Data\raw\dataset_01_poblacion_territorio_choco...,dataset_01_poblacion_territorio_choco_definiti...,.csv,4.02
10,Data\raw\dataset_02_conectividad_digital_choco...,dataset_02_conectividad_digital_choco_v2.csv,.csv,7.66
11,Data\raw\dataset_03_conectividad_fisica_choco_...,dataset_03_conectividad_fisica_choco_final.csv,.csv,11.95
12,Data\raw\dataset_05_condiciones_socioeconomica...,dataset_05_condiciones_socioeconomicas_choco_f...,.csv,4.88
13,Data\raw\dataset_06_informacion_comunicacion_c...,dataset_06_informacion_comunicacion_choco_v1.xlsx,.xlsx,15.95
14,Data\raw\dataset_07_emergencias_desastres_choc...,dataset_07_emergencias_desastres_choco_final(1...,.xlsx,114.37
15,Data\raw\dataset_08_capacidad_institucional_ch...,dataset_08_capacidad_institucional_choco_v1.xlsx,.xlsx,13.17
16,Data\raw\dataset_09_inversion_publica_infraest...,dataset_09_inversion_publica_infraestructura_c...,.xlsx,4591.66
17,Data\raw\dataset_10_historia_evidencia_cualita...,dataset_10_historia_evidencia_cualitativa_choc...,.xlsx,12.27
18,README.md,README.md,.md,0.89
19,environment.yml,environment.yml,.yml,0.21
20,notebooks\002_exploracion_inicial.ipynb,002_exploracion_inicial.ipynb,.ipynb,751.02
21,notebooks\README.md,README.md,.md,0.10
22,requirements.txt,requirements.txt,.txt,0.08

In [80]:
# Archivos de documentación que pueden contener la definición metodológica
docs = inventario[
    inventario["extension"].isin(
        [".md", ".txt", ".py", ".docx"]
    )
].copy()

display(docs)

,ruta,nombre,extension,tamano_kb
2,README.md,README.md,.md,0.89
3,requirements.txt,requirements.txt,.txt,0.08
5,notebooks\README.md,README.md,.md,0.10
18,Data\raw\Documento_Dataset_03_Conectividad_Fis...,Documento_Dataset_03_Conectividad_Fisica_Choco...,.docx,38.56

In [81]:
for archivo in EPISODIO.rglob("*"):
    if not archivo.is_file():
        continue

    if archivo.suffix.lower() not in [".md", ".txt"]:
        continue

    print("\n" + "=" * 80)
    print(archivo.relative_to(EPISODIO))
    print("=" * 80)

    texto = archivo.read_text(
        encoding="utf-8",
        errors="ignore"
    )

    print(texto[:12000])

================================================================================
README.md
================================================================================
# 002 - EL Chocó

Este episodio agrupa las fuentes, datos, analisis, guiones y materiales de salida para trabajar el tema del Chocó en Colombia.

## Estructura

```text
002_EL_chocó/
├── README.md
├── requirements.txt
├── environment.yml
├── .gitignore
├── Data/
│   ├── raw/
│   ├── interim/
│   └── processed/
├── notebooks/
├── src/
├── outputs/
├── docs/
├── video/
└── LICENSE
```

## Datos disponibles

Los archivos fuente actuales se encuentran en `Data/raw/`.

## Proximo flujo sugerido

1. Revisar y documentar las fuentes y diccionario de variables.
2. Normalizar los datasets en `src/` o `notebooks/`.
3. Guardar versiones intermedias y limpias en `Data/interim/` y `Data/processed/`.
4. Exportar graficos, tablas y materiales visuales en `outputs/`, `docs/` y `video/`.


================================================================================
requirements.txt
================================================================================
pandas
numpy
jupyter
matplotlib
seaborn
plotly
pyyaml
scipy
geopandas


================================================================================
notebooks\README.md
================================================================================
# Notebooks

Este directorio se usa para guardar cuadernos de exploración y análisis del episodio 2.

In [82]:
RAW = Path(
    r"C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw"
)

for archivo in sorted(RAW.iterdir()):

    if not archivo.is_file():
        continue

    print("\n" + "=" * 100)
    print(f"ARCHIVO: {archivo.name}")
    print("=" * 100)

    # Excel
    if archivo.suffix.lower() in [".xlsx", ".xls"]:
        try:
            xl = pd.ExcelFile(archivo)

            print("Hojas:")
            for hoja in xl.sheet_names:
                df_tmp = pd.read_excel(
                    archivo,
                    sheet_name=hoja,
                    nrows=5
                )

                print(
                    f"  - {hoja}: "
                    f"{len(df_tmp.columns)} columnas"
                )

                print(
                    "    ",
                    list(df_tmp.columns)[:15]
                )

        except Exception as e:
            print("ERROR:", e)

    # CSV
    elif archivo.suffix.lower() == ".csv":
        try:
            df_tmp = pd.read_csv(
                archivo,
                nrows=5
            )

            print("Columnas:")
            print(list(df_tmp.columns))

        except Exception as e:
            print("ERROR:", e)

    # Otros
    else:
        print("Tipo de archivo no tabular")

====================================================================================================
ARCHIVO: dataset_01_poblacion_territorio_choco.csv
====================================================================================================
Columnas:
['divipola', 'municipio', 'departamento', 'poblacion_total', 'poblacion_urbana_cabecera', 'poblacion_centros_poblados', 'poblacion_rural_disperso', 'densidad_poblacional_km2', 'superficie_km2', 'porcentaje_rural', 'poblacion_indigena', 'poblacion_afrodescendiente', 'centros_poblados', 'distancia_quibdo_km', 'proporcion_poblacion_10_19']

====================================================================================================
ARCHIVO: dataset_01_poblacion_territorio_choco_definitivo.csv
====================================================================================================
Columnas:
['divipola', 'municipio', 'departamento', 'poblacion_total', 'poblacion_urbana_cabecera', 'poblacion_centros_poblados', 'poblacion_rural_disperso', 'porcentaje_poblacion_rural', 'indice_ruralidad_existente', 'proporcion_poblacion_10_19', 'poblacion_indigena', 'poblacion_afrodescendiente_narp', 'poblacion_negra_mulata_afro', 'poblacion_raizal', 'poblacion_palenquera', 'densidad_poblacional_km2', 'superficie_km2', 'centros_poblados', 'distancia_quibdo_km', 'observacion_fuente_2018']

====================================================================================================
ARCHIVO: dataset_02_conectividad_digital_choco_v2.csv
====================================================================================================
Columnas:
['divipola', 'municipio', 'departamento', 'anio', 'cobertura_internet_fijo_pct', 'hogares_con_internet_pct', 'cobertura_movil_3g_4g_pct', 'suscriptores_moviles_por_100_hab', 'accesos_fijos', 'accesos_moviles', 'tecnologia_acceso_fijo', 'cobertura_2g_pct', 'cobertura_3g_pct', 'cobertura_4g_pct', 'cobertura_5g_pct', 'centros_digitales', 'zonas_comunitarias', 'infraestructura_fibra', 'operadores', 'interrupciones_fallas_relevantes', 'fuente_base', 'accesos_fijos_2025_t3', 'penetracion_internet_fijo_2025_t3_pct', 'accesos_cable_2025_t3', 'accesos_fiber_to_the_building_o_fiber_to_the_basement__fttb_2025_t3', 'accesos_fiber_to_the_home__ftth_2025_t3', 'accesos_fiber_to_the_premises_2025_t3', 'accesos_hybrid_fiber_coaxial__hfc_2025_t3', 'accesos_otras_tecnologías_de_fibra__antes_fttx_2025_t3', 'accesos_otras_tecnologías_inalámbricas_2025_t3', 'accesos_satelital_2025_t3', 'accesos_wifi_2025_t3', 'accesos_wimax_2025_t3', 'accesos_xdsl_2025_t3', 'operadores_movil_2025_t3', 'presencia_2g_2025_t3', 'presencia_3g_2025_t3', 'presencia_4g_2025_t3', 'presencia_5g_2025_t3', 'fuente_mintic_actualizacion', 'periodo_actualizacion']

====================================================================================================
ARCHIVO: dataset_03_conectividad_fisica_choco_final.csv
====================================================================================================
Columnas:
['divipola', 'brecha_componente_carretero', 'brecha_componente_fluvial', 'indice_brecha_conectividad_fisica', 'categoria_o_ciudad_referencia', 'gini_movilidad', 'gini_movilidad_valido', 'fuente_brecha', 'fuente_gini_movilidad', 'estado_brecha', 'estado_gini', 'observacion_brecha', 'observacion_gini']

====================================================================================================
ARCHIVO: dataset_05_condiciones_socioeconomicas_choco_final.csv
====================================================================================================
Columnas:
['divipola', 'municipio', 'departamento', 'deficit_habitacional_cualitativo_cabecera_2018', 'deficit_habitacional_cualitativo_rural_2018', 'deficit_habitacional_cuantitativo_cabecera_2018', 'deficit_habitacional_cuantitativo_rural_2018', 'ipm_cabecera_censo_2018', 'ipm_censo_2018', 'ipm_rural_censo_2018', 'nbi_2018', 'nbi_dependencia_economica_2018', 'nbi_hacinamiento_critico_2018', 'nbi_inasistencia_escolar_2018', 'nbi_servicios_inadecuados_2018', 'nbi_vivienda_inadecuada_2018', 'fuente_principal', 'nivel_geografico', 'anio_principal']

====================================================================================================
ARCHIVO: dataset_06_informacion_comunicacion_choco_v1.xlsx
====================================================================================================
Hojas:
  - Base_municipal: 29 columnas
     ['divipola', 'municipio', 'departamento', 'anio_ecosistema_informativo', 'medios_locales_total', 'medios_radio', 'medios_television', 'medios_digitales', 'medios_impresos', 'emisoras_comunitarias', 'emisoras_publicas', 'emisoras_fuerza_publica', 'restriccion_acceso_informacion', 'cobertura_territorial_medios_locales', 'produccion_informacion_local']
  - Agresiones_FLIP: 15 columnas
     ['id_evento_flip', 'fecha_agresion', 'anio', 'departamento', 'municipio', 'divipola', 'tipo_agresion', 'presunto_agresor', 'internet', 'violencia_genero', 'genero_victima', 'cargo_victima', 'descripcion_breve', 'fuente_url', 'observacion_calidad']
  - Diccionario: 8 columnas
     ['variable', 'definicion', 'tipo', 'fuente', 'año_referencia', 'nivel', 'entra_indice', 'regla_observacion']
  - Metodologia: 2 columnas
     ['campo', 'valor']
  - No_incluir: 3 columnas
     ['variable_fuente', 'dataset_responsable', 'motivo']
  - Casos_FLIP: 10 columnas
     ['id_caso', 'municipio', 'tema', 'actividad_relacionada', 'tipo_evidencia', 'fecha_fuente', 'titulo_fuente', 'descripcion', 'fuente_url', 'usar_en_indice']

====================================================================================================
ARCHIVO: dataset_07_emergencias_desastres_choco_final(1).xlsx
====================================================================================================
Hojas:
  - Eventos: 24 columnas
     ['id_evento', 'fecha', 'anio', 'departamento', 'municipio', 'divipola', 'evento', 'muertos', 'heridos', 'desaparecidos', 'personas_afectadas', 'familias_afectadas', 'viviendas_destruidas', 'viviendas_afectadas', 'vias']
  - Municipio_anio: 21 columnas
     ['anio', 'divipola', 'municipio', 'registros_evento', 'tipos_evento', 'muertos', 'heridos', 'desaparecidos', 'personas_afectadas', 'familias_afectadas', 'viviendas_destruidas', 'viviendas_afectadas', 'vias', 'puentes_vehiculares', 'puentes_peatonales']
  - Tipo_evento: 5 columnas
     ['anio', 'divipola', 'municipio', 'evento', 'registros_evento']
  - Fuentes: 7 columnas
     ['fuente', 'recurso', 'periodo', 'nivel', 'observacion_metodologica', 'calidad', 'archivo']
  - Metodologia: 2 columnas
     ['campo', 'valor']

====================================================================================================
ARCHIVO: dataset_08_capacidad_institucional_choco_v1.xlsx
====================================================================================================
Hojas:
  - Municipio: 12 columnas
     ['divipola', 'municipio', 'departamento', 'policia_registros_fuente', 'presencia_policia_en_directorio', 'observacion_policia', 'registros_ejercito_fuente', 'presencia_ejercito_en_archivo', 'observacion_ejercito', 'ips_total', 'servicios_urgencias', 'fuente_salud']
  - Policia_Choco: 8 columnas
     ['DEPARTAMENTO', 'CIUDAD/MUNICIPIO', 'UNIDAD', 'TIPO UNIDAD', 'CODIGO_CUADRANTE', 'CUADRANTE', 'NUMERO_CELULAR_CUADRANTE', 'municipio_detectado']
  - Ejercito_Choco: 6 columnas
     ['ZONA -DIM', 'DIRECCION', 'CIUDAD', 'TELEFONO', 'CORREO ELECTRÓNICO', 'municipio_detectado']
  - Diccionario: 5 columnas
     ['variable', 'definicion', 'fuente', 'calidad', 'regla']
  - Metodologia: 2 columnas
     ['campo', 'valor']

====================================================================================================
ARCHIVO: dataset_09_inversion_publica_infraestructura_choco_v1.xlsx
====================================================================================================
Hojas:
  - SGP_H_Datos Reporte SGP: 8 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']
  - SGP_2027_SGP: 17 columnas
     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  - SGP_2027_Inicio: 3 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2']
  - SGP_2027_SGP Histórico_1: 27 columnas
     ['Unnamed: 0', 'Apropiaciones del Sistema General de Participaciones\nmiles de millones de pesos corrientes\n2002-2027', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - SGP_2027_SGP Histórico: 14 columnas
     ['Apropiaciones del Sistema General de Participaciones\nmiles de millones de pesos corrientes\n2002-2027', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Volver al Inicio', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
  - SGP_2027_ Ficha Proyecciones: 13 columnas
     ['Unnamed: 0', 'Ficha de Proyecciones - Vigencia 2027\nSistema General de Participaciones', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
  - SGP_2027_EF_PG: 19 columnas
     [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
  - SGP_2027_ET: 37 columnas
     ['Unnamed: 0', 'AMAZONAS', 'ANTIOQUIA', 'ARAUCA', 'ATLANTICO', 'BOGOTA_DC', 'BOLIVAR', 'BOYACA', 'CALDAS', 'CAQUETA', 'CASANARE', 'CAUCA', 'CESAR', 'CHOCO', 'CORDOBA']
  - SGP_2027_lista: 39 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - SECOP_Gob_Choco: 66 columnas
     ['Nombre Entidad', 'Nit Entidad', 'Departamento', 'Ciudad', 'Localización', 'Orden', 'Sector', 'Rama', 'Entidad Centralizada', 'Proceso de Compra', 'ID Contrato', 'Referencia del Contrato', 'Estado Contrato', 'Codigo de Categoria Principal', 'Descripcion del Proceso']
  - Inventario_fuentes: 7 columnas
     ['fuente', 'archivo', 'entidad', 'periodo', 'nivel', 'calidad', 'uso']
  - Diccionario: 6 columnas
     ['variable', 'definicion', 'fuente', 'nivel', 'calidad', 'regla']
  - Metodologia: 2 columnas
     ['campo', 'valor']

====================================================================================================
ARCHIVO: dataset_10_historia_evidencia_cualitativa_choco_v1.xlsx
====================================================================================================
Hojas:
  - Biblioteca: 14 columnas
     ['id', 'categoria', 'autor', 'año', 'titulo', 'tipo', 'territorio', 'tema', 'metodologia', 'hallazgo', 'uso', 'calidad', 'enlace', 'nota']
  - Conceptos: 3 columnas
     ['concepto', 'definicion_operativa', 'fuente_contextual']
  - Casos: 6 columnas
     ['id_caso', 'territorio', 'tema', 'actores_o_procesos', 'fuente', 'uso']
  - Fuentes: 4 columnas
     ['id', 'institucion', 'enlace', 'tipo']
  - Metodologia: 2 columnas
     ['campo', 'valor']

====================================================================================================
ARCHIVO: Divipola_Serv_PuntosCentrosPoblados2013I.pitemx
====================================================================================================
Tipo de archivo no tabular

====================================================================================================
ARCHIVO: Documento_Dataset_03_Conectividad_Fisica_Choco.docx
====================================================================================================
Tipo de archivo no tabular

====================================================================================================
ARCHIVO: GiniMovilidad.csv
====================================================================================================
Columnas:
['DaneDep|Departamento|DaneMun|Municipio|Gini']

====================================================================================================
ARCHIVO: TerriData_Dim4.xlsx
====================================================================================================
Hojas:
  - Hoja01: 13 columnas
     ['Código Departamento', 'Departamento', 'Código Entidad', 'Entidad', 'Dimensión', 'Subcategoría', 'Indicador', 'Dato Numérico', 'Dato Cualitativo', 'Año', 'Mes', 'Fuente', 'Unidad de Medida']

====================================================================================================
ARCHIVO: TerriData_Dim5.xlsx
====================================================================================================
Hojas:
  - Hoja01: 13 columnas
     ['Código Departamento', 'Departamento', 'Código Entidad', 'Entidad', 'Dimensión', 'Subcategoría', 'Indicador', 'Dato Numérico', 'Dato Cualitativo', 'Año', 'Mes', 'Fuente', 'Unidad de Medida']

====================================================================================================
ARCHIVO: Visor-TCCN.xlsx
====================================================================================================
Hojas:
  - Introducción: 6 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5']
  - Visor-TCCN CNPV 2018: 16 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Nota: El concepto de Territorio Colectivo de Comunidades Negras, usado como opción de respuesta en la variable de ubicación "Tipo de territorio étnico" del formulario censal, corresponde a las Tierras de las Comunidades Negras referidas en el Artículo 4° de la Ley 70 de 1993.', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - LenguaXTCCN: 11 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Raizal', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Palenquero(a)', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10']
  - ResguardosXEdad2018: 29 columnas
     ['ID', 'Cod Dpto', 'Departamento', 'Cod Mpio', 'Municipio', 'Cod TCCN', 'Nombre TCCN', 'Nombre TCCN Notas Aclaratorias', 'Pueblo', 'Grupo Edad', 'Grupo Edad 2', 'Ind Hombre', 'Ind Mujer', 'Git Hombre', 'Git Mujer']
  - Proyecciones vs CNPV2018: 42 columnas
     ['ID', 'Observación', 'Cod Dpto', 'Departamento', 'Cod Mpio', 'Municipio', 'Cod Resguardo o TCCN', 'Nombre Resguardo o TCN Notas Aclaratorias', 'Pueblo', 'Región (5 regiones)', 'Región (9 regiones)', 'Resguardo colonial', 'Acuerdo Real', 'Número de Fragmentos (2018)', 'No Acuerdo Reserva']
  - GEXRdo: 11 columnas
     ['POBLACIÓN EN TERRITORIOS COLECTIVOS DE COMUNIDAD NEGRA POR GRUPO ÉTNICO, CNPV 2018', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10']
  - Fuera de resguardo: 20 columnas
     ['ID', 'Municipio', 'Cod_Dpto', 'Departamento', 'Cod_Mpio', 'Municipio.1', 'UA_CLASE', 'Está en Resguardo indígena o TCCN?', 'Tipo de territorialidad', 'Cod_Territorialidad', 'Nombre del Resguardo o TCCN', 'Indígena', 'Gitano o Rrom', 'Raizal', 'Palenquero']
  - Alfabetismo 2: 78 columnas
     ['Unnamed: 0', 'Unnamed: 1', 'Población Total NARP', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Hombres NARP', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Mujeres NARP', 'Unnamed: 13', 'Unnamed: 14']
  - Alfabetismo: 94 columnas
     ['Alfabetismo población NARP de 5 años y más TOTAL PERSONAS NARP', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Hombre', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Asistencia: 117 columnas
     ['Asistencia escolar población NARP de 5 años y más EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Hombre', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Nivel educativo: 91 columnas
     ['Máximo nivel educativo alcanzado TOTAL PERSONAS NARP', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Hombre', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Nivel educativo TCCN: 19 columnas
     ['Unnamed: 0', 'Hombre', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Mujer', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Dificultad: 82 columnas
     ['¿Tiene dificultades como: oir, hablar, ver, moverse, agarrar, entender, comer, interactuar o problemas cardiacos? PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Hombre', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Oir: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Hablar: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Ver: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Caminar: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Coger: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Cognitivo: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Comer: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Interactuar: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Actividades diarias: 29 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Hombre', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  - Servicios públicos: 31 columnas
     ['PERSONAS NARP EN HOGARES PARTICULARES', 'Unnamed: 1', 'Unnamed: 2', 'Electricidad', 'Unnamed: 4', 'Acueducto', 'Unnamed: 6', 'Alcantarillado', 'Unnamed: 8', 'Gas', 'Unnamed: 10', 'Recolección basuras', 'Unnamed: 12', 'Internet', 'Unnamed: 14']

In [83]:
# Indicadores educativos disponibles en Chocó
df_edu = df_dim4_choco[
    df_dim4_choco["Dimensión"].str.contains(
        "Educación",
        case=False,
        na=False
    )
].copy()

print("Registros:", len(df_edu))
print("Municipios:", df_edu["Código Entidad"].nunique())
print("Años:", df_edu["Año"].min(), "-", df_edu["Año"].max())

display(
    df_edu[
        [
            "Subcategoría",
            "Indicador",
            "Año"
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["Subcategoría", "Indicador", "Año"]
    )
)

Registros: 12314
Municipios: 31
Años: 2003 - 2025

,Subcategoría,Indicador,Año
113171,Acceso a la educación,Cobertura bruta en educación - Total,2005
114694,Acceso a la educación,Cobertura bruta en educación - Total,2006
115441,Acceso a la educación,Cobertura bruta en educación - Total,2007
116964,Acceso a la educación,Cobertura bruta en educación - Total,2008
117711,Acceso a la educación,Cobertura bruta en educación - Total,2009
...,...,...,...
351182,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,2020
351940,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,2021
353432,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,2022
354190,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,2023
355684,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,2024

In [84]:
cobertura_edu = (
    df_edu
    .groupby(["Subcategoría", "Indicador"])
    .agg(
        registros=("Código Entidad", "size"),
        municipios=("Código Entidad", "nunique"),
        anio_min=("Año", "min"),
        anio_max=("Año", "max"),
    )
    .reset_index()
    .sort_values(
        ["Subcategoría", "Indicador"]
    )
)

display(cobertura_edu)

,Subcategoría,Indicador,registros,municipios,anio_min,anio_max
0,Acceso a la educación,Cobertura bruta en educación - Total,620,31,2005,2024
1,Acceso a la educación,Cobertura bruta en educación básica,620,31,2005,2024
2,Acceso a la educación,Cobertura bruta en educación media,620,31,2005,2024
3,Acceso a la educación,Cobertura bruta en educación primaria,620,31,2005,2024
4,Acceso a la educación,Cobertura bruta en educación secundaria,620,31,2005,2024
5,Acceso a la educación,Cobertura bruta en transición,620,31,2005,2024
6,Acceso a la educación,Cobertura en educación superior,620,31,2005,2024
7,Acceso a la educación,Cobertura neta en educación - Total,620,31,2005,2024
8,Acceso a la educación,Cobertura neta en educación básica,620,31,2005,2024
9,Acceso a la educación,Cobertura neta en educación media,620,31,2005,2024
10,Acceso a la educación,Cobertura neta en educación primaria,620,31,2005,2024
11,Acceso a la educación,Cobertura neta en educación secundaria,620,31,2005,2024
12,Acceso a la educación,Cobertura neta en transición,620,31,2005,2024
13,Acceso a la educación,Tasa de tránsito inmediato a la educación supe...,341,31,2014,2024
14,Acceso a la educación desagregado por sexo,Cobertura neta en educación básica - Hombres,8,1,2014,2022
15,Acceso a la educación desagregado por sexo,Cobertura neta en educación básica - Mujeres,8,1,2014,2022
16,Acceso a la educación desagregado por sexo,Cobertura neta en educación total - Hombres,8,1,2014,2022
17,Acceso a la educación desagregado por sexo,Cobertura neta en educación total - Mujeres,8,1,2014,2022
18,Calidad,"Número de niños, niñas y mujeres gestantes con...",279,31,2015,2023
19,Calidad,Porcentaje de niños y niñas cuyas familias par...,248,31,2015,2022
20,Calidad,Porcentaje de niños y niñas de preescolar que ...,93,31,2023,2025
21,Calidad,Porcentaje de niños y niñas en primera infanci...,248,31,2015,2022
22,Calidad,Porcentaje de niños y niñas en servicios de ed...,310,31,2018,2022
23,Calidad,Puntaje promedio Pruebas Saber 11 - Lectura cr...,403,31,2010,2022
24,Calidad,Puntaje promedio Pruebas Saber 11 - Matemáticas,403,31,2010,2022
25,Logro,Años de educación personas de 15 y más años,7,1,2014,2020
26,Logro,Porcentaje de asistencia de 5 a 24 años (Censo),30,30,2018,2018
27,Logro,Porcentaje de asistencia de 5 a 24 años Rural ...,30,30,2018,2018
28,Logro,Porcentaje de asistencia de 5 a 24 años Urbana...,30,30,2018,2018
29,Logro,Tasa de Analfabetismo (Censo),30,30,2018,2018
30,Logro,Tasa de Analfabetismo Rural (Censo),30,30,2018,2018
31,Logro,Tasa de Analfabetismo Urbana (Censo),30,30,2018,2018
32,Logro,Tasa de analfabetismo de personas de 15 y más ...,6,1,2014,2019
33,Permanencia y rezago,Tasa de deserción intra-anual del sector no of...,30,3,2015,2024
34,Permanencia y rezago,Tasa de deserción intra-anual del sector ofici...,682,31,2003,2024
35,Permanencia y rezago,Tasa de deserción intra-anual en educación (De...,310,31,2015,2024
36,Permanencia y rezago,Tasa de repitencia del sector oficial en educa...,682,31,2003,2024

El Dataset 04 podría desaparecer

No significa que tiremos a la basura TerriData_Dim4.

Lo podemos conservar como fuente auxiliar.

Por ejemplo, si después descubrimos que:

“Los municipios más desconectados también presentan menor cobertura educativa”

eso puede convertirse en un análisis del episodio, una gráfica o una evidencia complementaria.

Pero no necesitamos convertirlo necesariamente en una dimensión del índice.

Empezamos con exploración de DataSet 05 "dataset_05_condiciones_socioeconomicas_choco_final.csv"

In [85]:
from pathlib import Path

base = Path.cwd()

print("Directorio actual:")
print(base)

print("\nBuscando dataset 05:")
for archivo in base.rglob("*dataset_05*"):
    print(archivo)

Directorio actual:
c:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\notebooks

Buscando dataset 05:

In [86]:
from pathlib import Path

base = Path(r"c:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó")

for archivo in base.rglob("*dataset_05_condiciones_socioeconomicas*"):
    print(archivo)

c:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\dataset_05_condiciones_socioeconomicas_choco_final.csv

In [87]:
df05_socio = pd.read_csv(
    r"c:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\dataset_05_condiciones_socioeconomicas_choco_final.csv"
)

In [88]:
print(df05_socio.shape)

for i, col in enumerate(df05_socio.columns):
    print(f"{i:02d} | {repr(col)}")

(31, 19)
00 | 'divipola'
01 | 'municipio'
02 | 'departamento'
03 | 'deficit_habitacional_cualitativo_cabecera_2018'
04 | 'deficit_habitacional_cualitativo_rural_2018'
05 | 'deficit_habitacional_cuantitativo_cabecera_2018'
06 | 'deficit_habitacional_cuantitativo_rural_2018'
07 | 'ipm_cabecera_censo_2018'
08 | 'ipm_censo_2018'
09 | 'ipm_rural_censo_2018'
10 | 'nbi_2018'
11 | 'nbi_dependencia_economica_2018'
12 | 'nbi_hacinamiento_critico_2018'
13 | 'nbi_inasistencia_escolar_2018'
14 | 'nbi_servicios_inadecuados_2018'
15 | 'nbi_vivienda_inadecuada_2018'
16 | 'fuente_principal'
17 | 'nivel_geografico'
18 | 'anio_principal'

In [89]:
variables_05 = [
    "deficit_habitacional_cualitativo_cabecera_2018",
    "deficit_habitacional_cualitativo_rural_2018",
    "deficit_habitacional_cuantitativo_cabecera_2018",
    "deficit_habitacional_cuantitativo_rural_2018",
    "ipm_cabecera_censo_2018",
    "ipm_censo_2018",
    "ipm_rural_censo_2018",
    "nbi_2018",
    "nbi_dependencia_economica_2018",
    "nbi_hacinamiento_critico_2018",
    "nbi_inasistencia_escolar_2018",
    "nbi_servicios_inadecuados_2018",
    "nbi_vivienda_inadecuada_2018"
]

corr_05 = df05_socio[variables_05].corr()

display(corr_05.round(2))

,deficit_habitacional_cualitativo_cabecera_2018,deficit_habitacional_cualitativo_rural_2018,deficit_habitacional_cuantitativo_cabecera_2018,deficit_habitacional_cuantitativo_rural_2018,ipm_cabecera_censo_2018,ipm_censo_2018,ipm_rural_censo_2018,nbi_2018,nbi_dependencia_economica_2018,nbi_hacinamiento_critico_2018,nbi_inasistencia_escolar_2018,nbi_servicios_inadecuados_2018,nbi_vivienda_inadecuada_2018
deficit_habitacional_cualitativo_cabecera_2018,1.00,0.51,-0.70,-0.49,-0.31,-0.41,-0.13,0.05,-0.37,-0.33,-0.65,0.12,-0.50
deficit_habitacional_cualitativo_rural_2018,0.51,1.00,-0.64,-1.00,-0.45,-0.67,-0.63,-0.46,-0.24,-0.62,-0.68,-0.36,-0.34
deficit_habitacional_cuantitativo_cabecera_2018,-0.70,-0.64,1.00,0.65,0.75,0.62,0.30,0.35,0.33,0.44,0.57,0.27,0.48
deficit_habitacional_cuantitativo_rural_2018,-0.49,-1.00,0.65,1.00,0.48,0.67,0.63,0.46,0.26,0.62,0.68,0.37,0.32
ipm_cabecera_censo_2018,-0.31,-0.45,0.75,0.48,1.00,0.68,0.36,0.38,0.49,0.44,0.45,0.28,0.37
ipm_censo_2018,-0.41,-0.67,0.62,0.67,0.68,1.00,0.76,0.47,0.58,0.77,0.72,0.35,0.27
ipm_rural_censo_2018,-0.13,-0.63,0.30,0.63,0.36,0.76,1.00,0.71,0.38,0.69,0.59,0.64,0.04
nbi_2018,0.05,-0.46,0.35,0.46,0.38,0.47,0.71,1.00,0.01,0.45,0.28,0.97,0.15
nbi_dependencia_economica_2018,-0.37,-0.24,0.33,0.26,0.49,0.58,0.38,0.01,1.00,0.32,0.45,-0.10,0.01
nbi_hacinamiento_critico_2018,-0.33,-0.62,0.44,0.62,0.44,0.77,0.69,0.45,0.32,1.00,0.58,0.36,0.26
nbi_inasistencia_escolar_2018,-0.65,-0.68,0.57,0.68,0.45,0.72,0.59,0.28,0.45,0.58,1.00,0.21,0.27
nbi_servicios_inadecuados_2018,0.12,-0.36,0.27,0.37,0.28,0.35,0.64,0.97,-0.10,0.36,0.21,1.00,-0.01
nbi_vivienda_inadecuada_2018,-0.50,-0.34,0.48,0.32,0.37,0.27,0.04,0.15,0.01,0.26,0.27,-0.01,1.00

In [90]:
display(
    corr_05["ipm_censo_2018"]
    .sort_values(ascending=False)
)

ipm_censo_2018                                     1.000000
nbi_hacinamiento_critico_2018                      0.767511
ipm_rural_censo_2018                               0.764346
nbi_inasistencia_escolar_2018                      0.722394
ipm_cabecera_censo_2018                            0.684920
deficit_habitacional_cuantitativo_rural_2018       0.673555
deficit_habitacional_cuantitativo_cabecera_2018    0.618125
nbi_dependencia_economica_2018                     0.583433
nbi_2018                                           0.468662
nbi_servicios_inadecuados_2018                     0.345478
nbi_vivienda_inadecuada_2018                       0.271546
deficit_habitacional_cualitativo_cabecera_2018    -0.413259
deficit_habitacional_cualitativo_rural_2018       -0.666377
Name: ipm_censo_2018, dtype: float64

In [91]:
display(
    corr_05["nbi_2018"]
    .sort_values(ascending=False)
)

nbi_2018                                           1.000000
nbi_servicios_inadecuados_2018                     0.967242
ipm_rural_censo_2018                               0.710495
ipm_censo_2018                                     0.468662
deficit_habitacional_cuantitativo_rural_2018       0.464604
nbi_hacinamiento_critico_2018                      0.447751
ipm_cabecera_censo_2018                            0.377997
deficit_habitacional_cuantitativo_cabecera_2018    0.348564
nbi_inasistencia_escolar_2018                      0.282403
nbi_vivienda_inadecuada_2018                       0.145468
deficit_habitacional_cualitativo_cabecera_2018     0.051889
nbi_dependencia_economica_2018                     0.005843
deficit_habitacional_cualitativo_rural_2018       -0.457799
Name: nbi_2018, dtype: float64

Dataset 05 en estado:

🟡 Revisado — reducir antes de incorporar al IOT.

Y como candidatos principales:

ipm_censo_2018
nbi_2018
deficit_habitacional_...

Hay una cuestión que debemos resolver primero: qué queremos que mida exactamente la dimensión socioeconómica del IOT.

Porque si la pregunta es:

"¿Qué tan buenas son las condiciones estructurales para que una persona pueda desarrollar sus oportunidades?"

**DataSet 6 auditoria inicial.**

In [92]:
path_06 = datasets["06_informacion_comunicacion"]

df06 = pd.read_excel(path_06)

print("Shape:", df06.shape)

print("\nColumnas:")
for i, col in enumerate(df06.columns, start=1):
    print(f"{i:02d}. {col}")

Shape: (31, 29)

Columnas:
01. divipola
02. municipio
03. departamento
04. anio_ecosistema_informativo
05. medios_locales_total
06. medios_radio
07. medios_television
08. medios_digitales
09. medios_impresos
10. emisoras_comunitarias
11. emisoras_publicas
12. emisoras_fuerza_publica
13. restriccion_acceso_informacion
14. cobertura_territorial_medios_locales
15. produccion_informacion_local
16. observacion_ecosistema
17. fuente_ecosistema
18. anio_agresiones_flip
19. agresiones_prensa_total
20. amenazas
21. asesinatos
22. hostigamientos
23. estigmatizaciones
24. agresiones_fisicas
25. acoso_judicial
26. acceso_informacion_publica
27. otras_agresiones
28. observacion_agresiones
29. fuente_agresiones

In [93]:
auditoria_06 = pd.DataFrame({
    "variable": df06.columns,
    "tipo": df06.dtypes.astype(str),
    "nulos": df06.isna().sum(),
    "nulos_pct": (df06.isna().mean() * 100).round(2),
    "unicos": df06.nunique(dropna=False)
})

display(auditoria_06)

,variable,tipo,nulos,nulos_pct,unicos
divipola,divipola,int64,0,0.0,31
municipio,municipio,object,0,0.0,31
departamento,departamento,object,0,0.0,1
anio_ecosistema_informativo,anio_ecosistema_informativo,float64,31,100.0,1
medios_locales_total,medios_locales_total,float64,31,100.0,1
medios_radio,medios_radio,float64,31,100.0,1
medios_television,medios_television,float64,31,100.0,1
medios_digitales,medios_digitales,float64,31,100.0,1
medios_impresos,medios_impresos,float64,31,100.0,1
emisoras_comunitarias,emisoras_comunitarias,float64,31,100.0,1
emisoras_publicas,emisoras_publicas,float64,31,100.0,1
emisoras_fuerza_publica,emisoras_fuerza_publica,float64,31,100.0,1
restriccion_acceso_informacion,restriccion_acceso_informacion,float64,31,100.0,1
cobertura_territorial_medios_locales,cobertura_territorial_medios_locales,float64,31,100.0,1
produccion_informacion_local,produccion_informacion_local,float64,31,100.0,1
observacion_ecosistema,observacion_ecosistema,float64,31,100.0,1
fuente_ecosistema,fuente_ecosistema,float64,31,100.0,1
anio_agresiones_flip,anio_agresiones_flip,float64,31,100.0,1
agresiones_prensa_total,agresiones_prensa_total,float64,31,100.0,1
amenazas,amenazas,float64,31,100.0,1
asesinatos,asesinatos,float64,31,100.0,1
hostigamientos,hostigamientos,float64,31,100.0,1
estigmatizaciones,estigmatizaciones,float64,31,100.0,1
agresiones_fisicas,agresiones_fisicas,float64,31,100.0,1
acoso_judicial,acoso_judicial,float64,31,100.0,1
acceso_informacion_publica,acceso_informacion_publica,float64,31,100.0,1
otras_agresiones,otras_agresiones,float64,31,100.0,1
observacion_agresiones,observacion_agresiones,float64,31,100.0,1
fuente_agresiones,fuente_agresiones,float64,31,100.0,1

In [94]:
df06.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 29 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   divipola                              31 non-null     int64
 1   municipio                             31 non-null     object
 2   departamento                          31 non-null     object
 3   anio_ecosistema_informativo           0 non-null      float64
 4   medios_locales_total                  0 non-null      float64
 5   medios_radio                          0 non-null      float64
 6   medios_television                     0 non-null      float64
 7   medios_digitales                      0 non-null      float64
 8   medios_impresos                       0 non-null      float64
 9   emisoras_comunitarias                 0 non-null      float64
 10  emisoras_publicas                     0 non-null      float64
 11  emisoras_fuerza_publica               0 non-null      float64
 12  restriccion_acceso_informacion        0 non-null      float64
 13  cobertura_territorial_medios_locales  0 non-null      float64
 14  produccion_informacion_local          0 non-null      float64
 15  observacion_ecosistema                0 non-null      float64
 16  fuente_ecosistema                     0 non-null      float64
 17  anio_agresiones_flip                  0 non-null      float64
 18  agresiones_prensa_total               0 non-null      float64
 19  amenazas                              0 non-null      float64
 20  asesinatos                            0 non-null      float64
 21  hostigamientos                        0 non-null      float64
 22  estigmatizaciones                     0 non-null      float64
 23  agresiones_fisicas                    0 non-null      float64
 24  acoso_judicial                        0 non-null      float64
 25  acceso_informacion_publica            0 non-null      float64
 26  otras_agresiones                      0 non-null      float64
 27  observacion_agresiones                0 non-null      float64
 28  fuente_agresiones                     0 non-null      float64
dtypes: float64(26), int64(1), object(2)
memory usage: 7.2+ KB

In [95]:
df06.describe()

,divipola,anio_ecosistema_informativo,medios_locales_total,medios_radio,medios_television,medios_digitales,medios_impresos,emisoras_comunitarias,emisoras_publicas,emisoras_fuerza_publica,...,amenazas,asesinatos,hostigamientos,estigmatizaciones,agresiones_fisicas,acoso_judicial,acceso_informacion_publica,otras_agresiones,observacion_agresiones,fuente_agresiones
count,31.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,27357.354839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,259.429958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,27001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,27117.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,27372.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,27537.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,27810.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
ruta_06 = r"C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\dataset_06_informacion_comunicacion_choco_v1.xlsx"

xls_06 = pd.ExcelFile(ruta_06)

print("Hojas disponibles")
for i, hoja in enumerate(xls_06.sheet_names):
    print(f"{i:02d} | {hoja}")

Hojas disponibles
00 | Base_municipal
01 | Agresiones_FLIP
02 | Diccionario
03 | Metodologia
04 | No_incluir
05 | Casos_FLIP

In [97]:
for hoja in xls_06.sheet_names:
    df_temp = pd.read_excel(ruta_06, sheet_name=hoja)

    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print(f"Shape: {df_temp.shape}")
    print("Columnas:")
    
    for i, col in enumerate(df_temp.columns):
        print(f"{i:02d} | {col}")

================================================================================
HOJA: Base_municipal
Shape: (31, 29)
Columnas:
00 | divipola
01 | municipio
02 | departamento
03 | anio_ecosistema_informativo
04 | medios_locales_total
05 | medios_radio
06 | medios_television
07 | medios_digitales
08 | medios_impresos
09 | emisoras_comunitarias
10 | emisoras_publicas
11 | emisoras_fuerza_publica
12 | restriccion_acceso_informacion
13 | cobertura_territorial_medios_locales
14 | produccion_informacion_local
15 | observacion_ecosistema
16 | fuente_ecosistema
17 | anio_agresiones_flip
18 | agresiones_prensa_total
19 | amenazas
20 | asesinatos
21 | hostigamientos
22 | estigmatizaciones
23 | agresiones_fisicas
24 | acoso_judicial
25 | acceso_informacion_publica
26 | otras_agresiones
27 | observacion_agresiones
28 | fuente_agresiones

================================================================================
HOJA: Agresiones_FLIP
Shape: (0, 15)
Columnas:
00 | id_evento_flip
01 | fecha_agresion
02 | anio
03 | departamento
04 | municipio
05 | divipola
06 | tipo_agresion
07 | presunto_agresor
08 | internet
09 | violencia_genero
10 | genero_victima
11 | cargo_victima
12 | descripcion_breve
13 | fuente_url
14 | observacion_calidad

================================================================================
HOJA: Diccionario
Shape: (29, 8)
Columnas:
00 | variable
01 | definicion
02 | tipo
03 | fuente
04 | año_referencia
05 | nivel
06 | entra_indice
07 | regla_observacion

================================================================================
HOJA: Metodologia
Shape: (13, 2)
Columnas:
00 | campo
01 | valor

================================================================================
HOJA: No_incluir
Shape: (8, 3)
Columnas:
00 | variable_fuente
01 | dataset_responsable
02 | motivo

================================================================================
HOJA: Casos_FLIP
Shape: (2, 10)
Columnas:
00 | id_caso
01 | municipio
02 | tema
03 | actividad_relacionada
04 | tipo_evidencia
05 | fecha_fuente
06 | titulo_fuente
07 | descripcion
08 | fuente_url
09 | usar_en_indice

In [98]:
for hoja in xls_06.sheet_names:
    df_temp = pd.read_excel(ruta_06, sheet_name=hoja)

    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print(f"Registros: {len(df_temp)}")
    
    display(df_temp.head(5))

================================================================================
HOJA: Base_municipal
Registros: 31

,divipola,municipio,departamento,anio_ecosistema_informativo,medios_locales_total,medios_radio,medios_television,medios_digitales,medios_impresos,emisoras_comunitarias,...,amenazas,asesinatos,hostigamientos,estigmatizaciones,agresiones_fisicas,acoso_judicial,acceso_informacion_publica,otras_agresiones,observacion_agresiones,fuente_agresiones
0,27001,Quibdó,Chocó,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,27006,Acandí,Chocó,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27025,Alto Baudó,Chocó,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,27050,Atrato,Chocó,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,27073,Bagadó,Chocó,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
HOJA: Agresiones_FLIP
Registros: 0

Empty DataFrame
Columns: [id_evento_flip, fecha_agresion, anio, departamento, municipio, divipola, tipo_agresion, presunto_agresor, internet, violencia_genero, genero_victima, cargo_victima, descripcion_breve, fuente_url, observacion_calidad]
Index: []

================================================================================
HOJA: Diccionario
Registros: 29

,variable,definicion,tipo,fuente,año_referencia,nivel,entra_indice,regla_observacion
0,divipola,Identificador municipal DIVIPOLA,Clave,DANE,Actual,Municipal,No,Clave de unión con los demás datasets.
1,municipio,Nombre oficial del municipio,Texto,DANE,Actual,Municipal,No,Catálogo territorial.
2,departamento,Departamento,Texto,DANE,Actual,Departamental,No,Se fija en Chocó para esta versión.
3,anio_ecosistema_informativo,Año de referencia de la medición FLIP del ecos...,Año,FLIP,Según fuente,Municipal,Sí,No mezclar mediciones de Cartografías de disti...
4,medios_locales_total,Número de medios locales identificados,Conteo,FLIP / Cartografías de la Información,Según fuente,Municipal,Sí,Solo medios que produzcan información local se...

================================================================================
HOJA: Metodologia
Registros: 13

                      campo                                              valor
0                   dataset  06 — Información, comunicación pública y liber...
1                territorio                                              Chocó
2          unidad_principal  Municipio; tabla secundaria a nivel de evento ...
3                  objetivo  Medir condiciones territoriales de acceso a in...
4  principio_no_duplicacion  No incorporar variables de conectividad digita...

================================================================================
HOJA: No_incluir
Registros: 8

,variable_fuente,dataset_responsable,motivo
0,cobertura_internet_fijo_pct,02 — Conectividad digital,Duplicaría conectividad digital.
1,cobertura_movil_2g_3g_4g_5g,02 — Conectividad digital,Ya está cubierta por MinTIC.
2,operadores_movil,02 — Conectividad digital,Ya está cubierta por MinTIC.
3,centros_digitales,02 — Conectividad digital,"Infraestructura digital, no ecosistema mediático."
4,poblacion_total_ruralidad_densidad,01 — Población y territorio,Variables demográficas.

================================================================================
HOJA: Casos_FLIP
Registros: 2

,id_caso,municipio,tema,actividad_relacionada,tipo_evidencia,fecha_fuente,titulo_fuente,descripcion,fuente_url,usar_en_indice
0,FLIP-CH-001,El Carmen de Atrato,desierto informativo / cobertura local,ambiental / territorial,cualitativa,2022-2023,Guardianes del territorio: la voz de la comuni...,La fuente describe dificultades para la cobert...,https://flip.org.co/pronunciamientos/guardiane...,No
1,FLIP-CH-002,Chocó,agresiones relacionadas con minería ilegal,minería,cualitativa,2025,Alerta por la seguridad de integrante de Cofra...,La FLIP documentó amenazas posteriores a publi...,https://flip.org.co/pronunciamientos?pagina=11...,No

In [99]:
for hoja in ["Diccionario", "Metodologia", "No_incluir", "Casos_FLIP"]:
    df_temp = pd.read_excel(ruta_06, sheet_name=hoja)
    
    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print(f"Shape: {df_temp.shape}")
    display(df_temp)

================================================================================
HOJA: Diccionario
Shape: (29, 8)

,variable,definicion,tipo,fuente,año_referencia,nivel,entra_indice,regla_observacion
0,divipola,Identificador municipal DIVIPOLA,Clave,DANE,Actual,Municipal,No,Clave de unión con los demás datasets.
1,municipio,Nombre oficial del municipio,Texto,DANE,Actual,Municipal,No,Catálogo territorial.
2,departamento,Departamento,Texto,DANE,Actual,Departamental,No,Se fija en Chocó para esta versión.
3,anio_ecosistema_informativo,Año de referencia de la medición FLIP del ecos...,Año,FLIP,Según fuente,Municipal,Sí,No mezclar mediciones de Cartografías de disti...
4,medios_locales_total,Número de medios locales identificados,Conteo,FLIP / Cartografías de la Información,Según fuente,Municipal,Sí,Solo medios que produzcan información local se...
5,medios_radio,Número de medios locales de radio,Conteo,FLIP,Según fuente,Municipal,Sí,Desagregación por tipo de medio.
6,medios_television,Número de medios locales de televisión,Conteo,FLIP,Según fuente,Municipal,Sí,Desagregación por tipo de medio.
7,medios_digitales,Número de medios locales digitales,Conteo,FLIP,Según fuente,Municipal,Sí,Desagregación por tipo de medio.
8,medios_impresos,Número de medios locales impresos,Conteo,FLIP,Según fuente,Municipal,Sí,Desagregación por tipo de medio.
9,emisoras_comunitarias,Número de emisoras comunitarias,Conteo,FLIP,Según fuente,Municipal,Sí,No confundir con toda la radio existente.
10,emisoras_publicas,Número de emisoras públicas,Conteo,FLIP,Según fuente,Municipal,Sí,Según clasificación de la fuente.
11,emisoras_fuerza_publica,Número de emisoras administradas por la Fuerza...,Conteo,FLIP,Según fuente,Municipal,Sí,Variable útil para caracterizar pluralidad del...
12,restriccion_acceso_informacion,Categoría FLIP de restricción de acceso a info...,Categórica,FLIP / Cartografías,Según fuente,Municipal,Sí,Valores previstos: sin_restriccion / media / a...
13,cobertura_territorial_medios_locales,Los medios locales cubren todo el municipio,Binaria,FLIP,Según fuente,Municipal,Sí,Debe respetar la definición metodológica de FLIP.
14,produccion_informacion_local,Existe producción de información sobre el prop...,Binaria,FLIP,Según fuente,Municipal,Sí,No equivale a tener conexión a Internet.
15,observacion_ecosistema,Nota cualitativa breve sobre el ecosistema local,Texto,FLIP,Según fuente,Municipal,No,No usar directamente en el índice.
16,fuente_ecosistema,Referencia exacta de la medición,Texto,FLIP,Según fuente,Municipal,No,URL o identificador del archivo descargado.
17,anio_agresiones_flip,Año de referencia de las agresiones FLIP,Año,FLIP,Según descarga,Municipal/Evento,Sí,Mantener separado del año del ecosistema infor...
18,agresiones_prensa_total,Número de agresiones FLIP registradas en el mu...,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado desde la tabla de eventos; no reempla...
19,amenazas,Número de amenazas registradas,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado de la tabla de eventos.
20,asesinatos,Número de asesinatos de periodistas registrados,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado de la tabla de eventos.
21,hostigamientos,Número de hostigamientos registrados,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado de la tabla de eventos.
22,estigmatizaciones,Número de estigmatizaciones registradas,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado de la tabla de eventos.
23,agresiones_fisicas,Número de agresiones físicas registradas,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado de la tabla de eventos.
24,acoso_judicial,Número de casos de acoso judicial registrados,Conteo,FLIP,Según descarga,Municipal,Sí,Agregado de la tabla de eventos.
25,acceso_informacion_publica,Número de casos relacionados con acceso a info...,Conteo,FLIP,Según descarga,Municipal,Sí,No confundir con conectividad digital.
26,otras_agresiones,Otras agresiones registradas,Conteo,FLIP,Según descarga,Municipal,Sí,Conservar la taxonomía original de FLIP.
27,observacion_agresiones,"Nota sobre cobertura, casos o limitaciones",Texto,FLIP,Según descarga,Municipal,No,Para control de calidad.
28,fuente_agresiones,Referencia exacta de la descarga,Texto,FLIP,Según descarga,Municipal/Evento,No,URL o identificador del archivo.

================================================================================
HOJA: Metodologia
Shape: (13, 2)

,campo,valor
0,dataset,"06 — Información, comunicación pública y liber..."
1,territorio,Chocó
2,unidad_principal,Municipio; tabla secundaria a nivel de evento ...
3,objetivo,Medir condiciones territoriales de acceso a in...
4,principio_no_duplicacion,No incorporar variables de conectividad digita...
5,nucleo_1,"Ecosistema informativo local: cantidad, tipos,..."
6,nucleo_2,Libertad de prensa: agresiones documentadas po...
7,fuente_ecosistema,FLIP — Cartografías de la Información / invest...
8,fuente_agresiones,FLIP — base/visualización de Agresiones a la l...
9,regla_temporal,No mezclar años sin conservar explícitamente e...
10,regla_indice,Los conteos de agresiones no deben interpretar...
11,regla_cualitativa,"Los informes FLIP sobre minería, silencio info..."
12,estado,Estructura v1 lista. Falta importar y validar ...

================================================================================
HOJA: No_incluir
Shape: (8, 3)

,variable_fuente,dataset_responsable,motivo
0,cobertura_internet_fijo_pct,02 — Conectividad digital,Duplicaría conectividad digital.
1,cobertura_movil_2g_3g_4g_5g,02 — Conectividad digital,Ya está cubierta por MinTIC.
2,operadores_movil,02 — Conectividad digital,Ya está cubierta por MinTIC.
3,centros_digitales,02 — Conectividad digital,"Infraestructura digital, no ecosistema mediático."
4,poblacion_total_ruralidad_densidad,01 — Población y territorio,Variables demográficas.
5,brecha_conectividad_fisica_gini_movilidad,03 — Conectividad física,Movilidad/accesibilidad física.
6,IPM_NBI_deficit_habitacional,05 — Condiciones socioeconómicas,Condiciones materiales y pobreza.
7,dependencia_pauta_oficial_departamental,No municipalizable sin fuente adecuada,FLIP reporta resultados agregados para regione...

================================================================================
HOJA: Casos_FLIP
Shape: (2, 10)

,id_caso,municipio,tema,actividad_relacionada,tipo_evidencia,fecha_fuente,titulo_fuente,descripcion,fuente_url,usar_en_indice
0,FLIP-CH-001,El Carmen de Atrato,desierto informativo / cobertura local,ambiental / territorial,cualitativa,2022-2023,Guardianes del territorio: la voz de la comuni...,La fuente describe dificultades para la cobert...,https://flip.org.co/pronunciamientos/guardiane...,No
1,FLIP-CH-002,Chocó,agresiones relacionadas con minería ilegal,minería,cualitativa,2025,Alerta por la seguridad de integrante de Cofra...,La FLIP documentó amenazas posteriores a publi...,https://flip.org.co/pronunciamientos?pagina=11...,No

Dataset 06 sería:

🟡 Estructura y metodología aprobadas. Fuente de datos pendiente.

Dataset 07 — Emergencias y desastres.

In [100]:
ruta_07 = RAW / "dataset_07_emergencias_desastres_choco_final(1).xlsx"
xls_07 = pd.ExcelFile(ruta_07)

print("Hojas disponibles:")
for i, hoja in enumerate(xls_07.sheet_names):
    print(f"{i:02d} | {hoja}")

Hojas disponibles:
00 | Eventos
01 | Municipio_anio
02 | Tipo_evento
03 | Fuentes
04 | Metodologia

In [101]:
for hoja in xls_07.sheet_names:
    df_temp = pd.read_excel(ruta_07, sheet_name=hoja)

    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print(f"Shape: {df_temp.shape}")
    
    print("Columnas:")
    for i, col in enumerate(df_temp.columns):
        print(f"{i:02d} | {col}")

================================================================================
HOJA: Eventos
Shape: (862, 24)
Columnas:
00 | id_evento
01 | fecha
02 | anio
03 | departamento
04 | municipio
05 | divipola
06 | evento
07 | muertos
08 | heridos
09 | desaparecidos
10 | personas_afectadas
11 | familias_afectadas
12 | viviendas_destruidas
13 | viviendas_afectadas
14 | vias
15 | puentes_vehiculares
16 | puentes_peatonales
17 | acueductos
18 | alcantarillados
19 | centros_salud
20 | centros_educativos
21 | centros_comunitarios
22 | hectareas
23 | fuente_archivo

================================================================================
HOJA: Municipio_anio
Shape: (217, 21)
Columnas:
00 | anio
01 | divipola
02 | municipio
03 | registros_evento
04 | tipos_evento
05 | muertos
06 | heridos
07 | desaparecidos
08 | personas_afectadas
09 | familias_afectadas
10 | viviendas_destruidas
11 | viviendas_afectadas
12 | vias
13 | puentes_vehiculares
14 | puentes_peatonales
15 | acueductos
16 | alcantarillados
17 | centros_salud
18 | centros_educativos
19 | centros_comunitarios
20 | hectareas

================================================================================
HOJA: Tipo_evento
Shape: (512, 5)
Columnas:
00 | anio
01 | divipola
02 | municipio
03 | evento
04 | registros_evento

================================================================================
HOJA: Fuentes
Shape: (9, 7)
Columnas:
00 | fuente
01 | recurso
02 | periodo
03 | nivel
04 | observacion_metodologica
05 | calidad
06 | archivo

================================================================================
HOJA: Metodologia
Shape: (10, 2)
Columnas:
00 | campo
01 | valor

In [102]:
for hoja in xls_07.sheet_names:
    df_temp = pd.read_excel(ruta_07, sheet_name=hoja)

    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print(f"Registros: {len(df_temp)}")
    
    display(df_temp.head(5))

================================================================================
HOJA: Eventos
Registros: 862

,id_evento,fecha,anio,departamento,municipio,divipola,evento,muertos,heridos,desaparecidos,...,vias,puentes_vehiculares,puentes_peatonales,acueductos,alcantarillados,centros_salud,centros_educativos,centros_comunitarios,hectareas,fuente_archivo
0,1,2018-01-02,2018,CHOCO,LLORO,27413,ACCIDENTE FLUVIAL,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx
1,2,2018-01-12,2018,CHOCO,CARMEN DEL DARIEN,27150,INUNDACIÓN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx
2,3,2018-01-18,2018,CHOCO,UNGUIA,27800,CRECIENTE SÚBITA,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx
3,4,2018-01-28,2018,CHOCO,RIOSUCIO,27615,INCENDIO ESTRUCTURAL,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx
4,5,2018-02-04,2018,CHOCO,BAHIA SOLANO,27075,OTROS,0.0,21.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx

================================================================================
HOJA: Municipio_anio
Registros: 217

,anio,divipola,municipio,registros_evento,tipos_evento,muertos,heridos,desaparecidos,personas_afectadas,familias_afectadas,...,viviendas_afectadas,vias,puentes_vehiculares,puentes_peatonales,acueductos,alcantarillados,centros_salud,centros_educativos,centros_comunitarios,hectareas
0,2018,27001,QUIBDO,7,6,2.0,7.0,0.0,7612.0,1716.0,...,501.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,27006,ACANDI,2,2,0.0,3.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018,27050,ATRATO,3,2,0.0,0.0,0.0,4995.0,999.0,...,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,27073,BAGADO,2,2,0.0,0.0,0.0,763.0,168.0,...,30.0,0.0,0.0,0.0,3.0,2.0,0.0,1.0,0.0,60.0
4,2018,27075,BAHIA SOLANO,1,1,0.0,21.0,0.0,21.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

================================================================================
HOJA: Tipo_evento
Registros: 512

   anio  divipola municipio                 evento  registros_evento
0  2018     27001    QUIBDO  ACCIDENTE DE TRANSITO                 1
1  2018     27001    QUIBDO   INCENDIO ESTRUCTURAL                 2
2  2018     27001    QUIBDO             INUNDACION                 1
3  2018     27001    QUIBDO             INUNDACIÓN                 1
4  2018     27001    QUIBDO                  OTROS                 1

================================================================================
HOJA: Fuentes
Registros: 9

,fuente,recurso,periodo,nivel,observacion_metodologica,calidad,archivo
0,UNGRD,Reporte anual de emergencias 2018,2018,Municipal/evento,Fuente primaria de registros de emergencia.,🟢,EMERGENCIAS-2018.xls
1,UNGRD,Reporte anual de emergencias 2019,2019,Municipal/evento,Fuente primaria de registros de emergencia.,🟢,EMERGENCIAS-2019.xls
2,UNGRD,Reporte anual de emergencias 2020,2020,Municipal/evento,Fuente primaria; COVID-19 aparece además en ho...,🟡,EMERGENCIAS-2020.xls
3,UNGRD,Reporte anual de emergencias 2021,2021,Municipal/evento,Reporte hasta diciembre; incluye campos de res...,🟢,EMERGENCIAS-2021-DICIEMBRE.xls
4,UNGRD,Reporte anual de emergencias 2022,2022,Municipal/evento,Fuente primaria.,🟢,REPORTE-ANUAL-DE-EMERGENCIAS-2022.xls

================================================================================
HOJA: Metodologia
Registros: 10

               campo                                              valor
0           objetivo  Construir un registro histórico de emergencias...
1  periodo_principal  2018-2025, a partir de reportes anuales de eme...
2   unidad_principal  Evento registrado; se incluye también agregado...
3  variables_impacto  Muertos, heridos, desaparecidos, personas/fami...
4        desinventar  Se conserva como fuente histórica de contraste...

In [103]:
eventos = pd.read_excel(
    ruta_07,
    sheet_name="Eventos"
)

print(eventos["anio"].value_counts().sort_index())

anio
2018     67
2019    103
2020    102
2021     78
2022     81
2023     94
2024    180
2025    157
Name: count, dtype: int64

In [104]:
print(
    eventos.groupby("anio")["divipola"]
    .nunique()
    .sort_index()
)

anio
2018    25
2019    27
2020    27
2021    27
2022    25
2023    26
2024    29
2025    31
Name: divipola, dtype: int64

In [105]:
print(
    eventos["evento"]
    .value_counts()
    .to_frame("registros")
)

                                         registros
evento
INUNDACION                                     341
VENDAVAL                                       131
INCENDIO ESTRUCTURAL                           105
MOVIMIENTO EN MASA                              91
INUNDACIÓN                                      26
CRECIENTE SUBITA                                26
INCENDIO FORESTAL                               22
TEMPORAL                                        21
ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL         12
INMERSION                                        7
SISMO                                            7
AVENIDA TORRENCIAL                               7
TORMENTA ELECTRICA                               6
CASO FORTUITO                                    6
EROSION                                          6
INCENDIO DE COBERTURA VEGETAL                    6
DESLIZAMIENTO                                    5
COLAPSO ESTRUCTURAL                              5
ACCIDENTE MINERO                                 4
LLUVIAS                                          4
ACCIDENTE FLUVIAL                                4
ACCIDENTE TRANSPORTE TERRESTRE                   4
OTROS                                            3
EXPLOSION                                        2
ACCIDENTE TRANSPORTE AEREO                       2
EROSION COSTERA                                  2
INCENDIO                                         1
ACCIDENTE DE TRANSITO                            1
REMOCIÓN EN MASA                                 1
COLAPSO                                          1
ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL          1
ACCIDENTE                                        1
CRECIENTE SÚBITA                                 1

In [106]:
print(
    eventos.groupby("evento")["divipola"]
    .nunique()
    .sort_values(ascending=False)
    .to_frame("municipios")
)

                                         municipios
evento
INUNDACION                                       31
VENDAVAL                                         29
INCENDIO ESTRUCTURAL                             28
MOVIMIENTO EN MASA                               17
INUNDACIÓN                                       16
CRECIENTE SUBITA                                 15
TEMPORAL                                         14
ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL           8
INMERSION                                         7
INCENDIO FORESTAL                                 7
SISMO                                             7
TORMENTA ELECTRICA                                6
CASO FORTUITO                                     5
AVENIDA TORRENCIAL                                5
COLAPSO ESTRUCTURAL                               5
DESLIZAMIENTO                                     4
EROSION                                           4
LLUVIAS                                           4
ACCIDENTE FLUVIAL                                 4
OTROS                                             3
ACCIDENTE TRANSPORTE TERRESTRE                    3
INCENDIO DE COBERTURA VEGETAL                     3
EROSION COSTERA                                   2
EXPLOSION                                         2
ACCIDENTE TRANSPORTE AEREO                        2
ACCIDENTE MINERO                                  2
INCENDIO                                          1
ACCIDENTE DE TRANSITO                             1
CRECIENTE SÚBITA                                  1
COLAPSO                                           1
REMOCIÓN EN MASA                                  1
ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL           1
ACCIDENTE                                         1

In [107]:
variables_impacto = [
    "muertos",
    "heridos",
    "desaparecidos",
    "personas_afectadas",
    "familias_afectadas",
    "viviendas_destruidas",
    "viviendas_afectadas",
    "vias",
    "puentes_vehiculares",
    "puentes_peatonales",
    "acueductos",
    "alcantarillados",
    "centros_salud",
    "centros_educativos",
    "centros_comunitarios",
    "hectareas"
]

display(
    eventos[variables_impacto]
    .describe()
    .T
)

,count,mean,std,min,25%,50%,75%,max
muertos,106.0,1.462264,4.082890,0.0,0.0,1.00,1.00,40.0
heridos,93.0,2.043011,3.784735,0.0,0.0,1.00,2.00,21.0
desaparecidos,51.0,0.117647,0.431141,0.0,0.0,0.00,0.00,2.0
personas_afectadas,686.0,1700.900875,3630.243300,0.0,18.0,250.00,1505.25,35000.0
familias_afectadas,682.0,502.019062,1001.416095,0.0,6.0,94.50,467.00,7500.0
viviendas_destruidas,233.0,11.909871,75.213177,0.0,1.0,1.00,5.00,1118.0
viviendas_afectadas,482.0,244.624481,646.387558,0.0,4.0,28.50,193.25,7500.0
vias,99.0,0.727273,0.966988,0.0,0.0,1.00,1.00,5.0
puentes_vehiculares,64.0,0.484375,1.083677,0.0,0.0,0.00,1.00,5.0
puentes_peatonales,67.0,1.000000,2.498484,0.0,0.0,0.00,1.00,13.0
acueductos,72.0,1.402778,4.277882,0.0,0.0,0.00,1.00,24.0
alcantarillados,54.0,0.166667,0.504695,0.0,0.0,0.00,0.00,2.0
centros_salud,70.0,1.128571,3.509496,0.0,0.0,0.00,1.00,20.0
centros_educativos,107.0,1.654206,2.832103,0.0,0.0,1.00,2.00,17.0
centros_comunitarios,70.0,0.842857,1.908302,0.0,0.0,0.00,1.00,10.0
hectareas,114.0,410.108772,2179.443334,0.0,0.0,3.25,155.25,23000.0

In [108]:
display(
    eventos[variables_impacto]
    .isna()
    .sum()
    .to_frame("nulos")
)

                      nulos
muertos                 756
heridos                 769
desaparecidos           811
personas_afectadas      176
familias_afectadas      180
viviendas_destruidas    629
viviendas_afectadas     380
vias                    763
puentes_vehiculares     798
puentes_peatonales      795
acueductos              790
alcantarillados         808
centros_salud           792
centros_educativos      755
centros_comunitarios    792
hectareas               748

In [109]:
print(eventos["evento"].unique())

['ACCIDENTE FLUVIAL' 'INUNDACIÓN' 'CRECIENTE SÚBITA'
 'INCENDIO ESTRUCTURAL' 'OTROS' 'ACCIDENTE' 'COLAPSO' 'VENDAVAL'
 'REMOCIÓN EN MASA' 'INCENDIO FORESTAL' 'AVENIDA TORRENCIAL'
 'ACCIDENTE DE TRANSITO' 'TORMENTA ELECTRICA' 'DESLIZAMIENTO' 'EXPLOSION'
 'INUNDACION' 'INMERSION' 'EROSION'
 'ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL' 'INCENDIO' 'MOVIMIENTO EN MASA'
 'INCENDIO DE COBERTURA VEGETAL' 'SISMO' 'COLAPSO ESTRUCTURAL' 'TEMPORAL'
 'CRECIENTE SUBITA' 'ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL'
 'ACCIDENTE MINERO' 'CASO FORTUITO' 'LLUVIAS' 'ACCIDENTE TRANSPORTE AEREO'
 'EROSION COSTERA' 'ACCIDENTE TRANSPORTE TERRESTRE']

In [110]:
print(
    eventos.groupby("evento")
    .agg(
        registros=("id_evento", "count"),
        municipios=("divipola", "nunique"),
        personas_afectadas=("personas_afectadas", "sum")
    )
    .sort_values("registros", ascending=False)
)

                                         registros  municipios  \
evento
INUNDACION                                     341          31
VENDAVAL                                       131          29
INCENDIO ESTRUCTURAL                           105          28
MOVIMIENTO EN MASA                              91          17
INUNDACIÓN                                      26          16
CRECIENTE SUBITA                                26          15
INCENDIO FORESTAL                               22           7
TEMPORAL                                        21          14
ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL         12           8
SISMO                                            7           7
INMERSION                                        7           7
AVENIDA TORRENCIAL                               7           5
CASO FORTUITO                                    6           5
EROSION                                          6           4
TORMENTA ELECTRICA                               6           6
INCENDIO DE COBERTURA VEGETAL                    6           3
DESLIZAMIENTO                                    5           4
COLAPSO ESTRUCTURAL                              5           5
ACCIDENTE TRANSPORTE TERRESTRE                   4           3
LLUVIAS                                          4           4
ACCIDENTE MINERO                                 4           2
ACCIDENTE FLUVIAL                                4           4
OTROS                                            3           3
EROSION COSTERA                                  2           2
EXPLOSION                                        2           2
ACCIDENTE TRANSPORTE AEREO                       2           2
INCENDIO                                         1           1
ACCIDENTE DE TRANSITO                            1           1
CRECIENTE SÚBITA                                 1           1
REMOCIÓN EN MASA                                 1           1
COLAPSO                                          1           1
ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL          1           1
ACCIDENTE                                        1           1

                                         personas_afectadas
evento
INUNDACION                                         940407.0
VENDAVAL                                            93178.0
INCENDIO ESTRUCTURAL                                 2353.0
MOVIMIENTO EN MASA                                  12521.0
INUNDACIÓN                                          48325.0
CRECIENTE SUBITA                                    53063.0
INCENDIO FORESTAL                                       4.0
TEMPORAL                                             8736.0
ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL               115.0
SISMO                                                2513.0
INMERSION                                               7.0
AVENIDA TORRENCIAL                                   3055.0
CASO FORTUITO                                          22.0
EROSION                                               602.0
TORMENTA ELECTRICA                                   1417.0
INCENDIO DE COBERTURA VEGETAL                           0.0
DESLIZAMIENTO                                          33.0
COLAPSO ESTRUCTURAL                                    34.0
ACCIDENTE TRANSPORTE TERRESTRE                         26.0
LLUVIAS                                                 0.0
ACCIDENTE MINERO                                        7.0
ACCIDENTE FLUVIAL                                       8.0
OTROS                                                  22.0
EROSION COSTERA                                       290.0
EXPLOSION                                               3.0
ACCIDENTE TRANSPORTE AEREO                              7.0
INCENDIO                                                0.0
ACCIDENTE DE TRANSITO                                   8.0
CRECIENTE SÚBITA                                        0.0
REMOCIÓN EN MASA                                       25.0
COLAPSO                                                30.0
ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL                 6.0
ACCIDENTE                                               1.0

In [111]:
eventos["evento"].value_counts()

evento
INUNDACION                                 341
VENDAVAL                                   131
INCENDIO ESTRUCTURAL                       105
MOVIMIENTO EN MASA                          91
INUNDACIÓN                                  26
CRECIENTE SUBITA                            26
INCENDIO FORESTAL                           22
TEMPORAL                                    21
ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL     12
INMERSION                                    7
SISMO                                        7
AVENIDA TORRENCIAL                           7
TORMENTA ELECTRICA                           6
CASO FORTUITO                                6
EROSION                                      6
INCENDIO DE COBERTURA VEGETAL                6
DESLIZAMIENTO                                5
COLAPSO ESTRUCTURAL                          5
ACCIDENTE MINERO                             4
LLUVIAS                                      4
ACCIDENTE FLUVIAL                            4
ACCIDENTE TRANSPORTE TERRESTRE               4
OTROS                                        3
EXPLOSION                                    2
ACCIDENTE TRANSPORTE AEREO                   2
EROSION COSTERA                              2
INCENDIO                                     1
ACCIDENTE DE TRANSITO                        1
REMOCIÓN EN MASA                             1
COLAPSO                                      1
ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL      1
ACCIDENTE                                    1
CRECIENTE SÚBITA                             1
Name: count, dtype: int64

In [112]:
# Copia de trabajo
eventos_limpio = eventos.copy()

# ---------------------------------------------------------
# 1. Tipos básicos
# ---------------------------------------------------------

eventos_limpio["fecha"] = pd.to_datetime(
    eventos_limpio["fecha"],
    errors="coerce"
)

eventos_limpio["anio"] = pd.to_numeric(
    eventos_limpio["anio"],
    errors="coerce"
).astype("Int64")

eventos_limpio["divipola"] = pd.to_numeric(
    eventos_limpio["divipola"],
    errors="coerce"
).astype("Int64")


# ---------------------------------------------------------
# 2. Limpieza de texto
# ---------------------------------------------------------

for col in ["departamento", "municipio", "evento"]:
    eventos_limpio[col] = (
        eventos_limpio[col]
        .astype("string")
        .str.strip()
    )


# ---------------------------------------------------------
# 3. Normalización SOLO de inconsistencias evidentes
# ---------------------------------------------------------

mapa_eventos = {
    "INUNDACION": "INUNDACIÓN",
    "CRECIENTE SUBITA": "CRECIENTE SÚBITA",
    "ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL":
        "ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL"
}

eventos_limpio["evento_normalizado"] = (
    eventos_limpio["evento"]
    .replace(mapa_eventos)
)

In [113]:
comparacion = (
    eventos_limpio[
        eventos_limpio["evento"] != eventos_limpio["evento_normalizado"]
    ][["evento", "evento_normalizado"]]
    .drop_duplicates()
    .sort_values(["evento", "evento_normalizado"])
)

display(comparacion)

,evento,evento_normalizado
68,ACCIDENTE TRANSPORTE MARITIMO O FLUVIAL,ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL
209,CRECIENTE SUBITA,CRECIENTE SÚBITA
62,INUNDACION,INUNDACIÓN

In [114]:
print(
    eventos_limpio["evento_normalizado"]
    .value_counts()
)

evento_normalizado
INUNDACIÓN                                 367
VENDAVAL                                   131
INCENDIO ESTRUCTURAL                       105
MOVIMIENTO EN MASA                          91
CRECIENTE SÚBITA                            27
INCENDIO FORESTAL                           22
TEMPORAL                                    21
ACCIDENTE TRANSPORTE MARÍTIMO O FLUVIAL     13
AVENIDA TORRENCIAL                           7
SISMO                                        7
INMERSION                                    7
TORMENTA ELECTRICA                           6
CASO FORTUITO                                6
EROSION                                      6
INCENDIO DE COBERTURA VEGETAL                6
DESLIZAMIENTO                                5
COLAPSO ESTRUCTURAL                          5
ACCIDENTE MINERO                             4
LLUVIAS                                      4
ACCIDENTE FLUVIAL                            4
ACCIDENTE TRANSPORTE TERRESTRE               4
OTROS                                        3
EXPLOSION                                    2
ACCIDENTE TRANSPORTE AEREO                   2
EROSION COSTERA                              2
INCENDIO                                     1
ACCIDENTE DE TRANSITO                        1
REMOCIÓN EN MASA                             1
COLAPSO                                      1
ACCIDENTE                                    1
Name: count, dtype: Int64

In [115]:
regla_nulos = {
    "regla": "Los valores faltantes se conservan como NA.",
    "motivo": (
        "La ausencia de registro en una variable de impacto "
        "no se interpreta automáticamente como cero."
    )
}

print(regla_nulos)

{'regla': 'Los valores faltantes se conservan como NA.', 'motivo': 'La ausencia de registro en una variable de impacto no se interpreta automáticamente como cero.'}

In [116]:
print(
    "Duplicados exactos:",
    eventos_limpio.duplicated().sum()
)

Duplicados exactos: 0

In [117]:
print(
    "ID de evento duplicados:",
    eventos_limpio["id_evento"].duplicated().sum()
)

ID de evento duplicados: 0

In [118]:
variables_numericas = [
    "muertos",
    "heridos",
    "desaparecidos",
    "personas_afectadas",
    "familias_afectadas",
    "viviendas_destruidas",
    "viviendas_afectadas",
    "vias",
    "puentes_vehiculares",
    "puentes_peatonales",
    "acueductos",
    "alcantarillados",
    "centros_salud",
    "centros_educativos",
    "centros_comunitarios",
    "hectareas"
]

calidad = pd.DataFrame({
    "variable": variables_numericas,
    "registros_totales": len(eventos_limpio),
    "registros_no_nulos": [
        eventos_limpio[c].notna().sum()
        for c in variables_numericas
    ],
    "registros_nulos": [
        eventos_limpio[c].isna().sum()
        for c in variables_numericas
    ]
})

calidad["cobertura_pct"] = (
    calidad["registros_no_nulos"]
    / calidad["registros_totales"]
    * 100
).round(2)

display(calidad)

,variable,registros_totales,registros_no_nulos,registros_nulos,cobertura_pct
0,muertos,862,106,756,12.30
1,heridos,862,93,769,10.79
2,desaparecidos,862,51,811,5.92
3,personas_afectadas,862,686,176,79.58
4,familias_afectadas,862,682,180,79.12
5,viviendas_destruidas,862,233,629,27.03
6,viviendas_afectadas,862,482,380,55.92
7,vias,862,99,763,11.48
8,puentes_vehiculares,862,64,798,7.42
9,puentes_peatonales,862,67,795,7.77
10,acueductos,862,72,790,8.35
11,alcantarillados,862,54,808,6.26
12,centros_salud,862,70,792,8.12
13,centros_educativos,862,107,755,12.41
14,centros_comunitarios,862,70,792,8.12
15,hectareas,862,114,748,13.23

In [119]:
metodologia_07 = pd.DataFrame([
    {
        "campo": "objetivo",
        "valor": "Construir una base histórica municipal de eventos de emergencia y sus impactos reportados."
    },
    {
        "campo": "fuente_principal",
        "valor": "UNGRD — reportes anuales de emergencias."
    },
    {
        "campo": "periodo",
        "valor": "2018-2025."
    },
    {
        "campo": "unidad_original",
        "valor": "Evento registrado."
    },
    {
        "campo": "unidad_para_indice",
        "valor": "Municipio-año, mediante agregación posterior."
    },
    {
        "campo": "clave_territorial",
        "valor": "DIVIPOLA."
    },
    {
        "campo": "normalizacion_eventos",
        "valor": "Se corrigen únicamente inconsistencias evidentes de escritura."
    },
    {
        "campo": "agrupacion_semantica",
        "valor": "No realizada en esta etapa."
    },
    {
        "campo": "tratamiento_nulos",
        "valor": "Los valores faltantes se conservan como NA; no se imputan automáticamente como cero."
    },
    {
        "campo": "variables_indice",
        "valor": "Pendientes de selección después de construir y evaluar los agregados municipales."
    }
])

display(metodologia_07)

                   campo                                              valor
0               objetivo  Construir una base histórica municipal de even...
1       fuente_principal           UNGRD — reportes anuales de emergencias.
2                periodo                                         2018-2025.
3        unidad_original                                 Evento registrado.
4     unidad_para_indice      Municipio-año, mediante agregación posterior.
5      clave_territorial                                          DIVIPOLA.
6  normalizacion_eventos  Se corrigen únicamente inconsistencias evident...
7   agrupacion_semantica                        No realizada en esta etapa.
8      tratamiento_nulos  Los valores faltantes se conservan como NA; no...
9       variables_indice  Pendientes de selección después de construir y...

In [120]:
print(eventos_limpio.shape)

for i, col in enumerate(eventos_limpio.columns):
    print(f"{i:02d} | {col}")

(862, 25)
00 | id_evento
01 | fecha
02 | anio
03 | departamento
04 | municipio
05 | divipola
06 | evento
07 | muertos
08 | heridos
09 | desaparecidos
10 | personas_afectadas
11 | familias_afectadas
12 | viviendas_destruidas
13 | viviendas_afectadas
14 | vias
15 | puentes_vehiculares
16 | puentes_peatonales
17 | acueductos
18 | alcantarillados
19 | centros_salud
20 | centros_educativos
21 | centros_comunitarios
22 | hectareas
23 | fuente_archivo
24 | evento_normalizado

In [121]:
print(eventos_limpio.shape)

for i, col in enumerate(eventos_limpio.columns):
    print(f"{i:02d} | {col}")

(862, 25)
00 | id_evento
01 | fecha
02 | anio
03 | departamento
04 | municipio
05 | divipola
06 | evento
07 | muertos
08 | heridos
09 | desaparecidos
10 | personas_afectadas
11 | familias_afectadas
12 | viviendas_destruidas
13 | viviendas_afectadas
14 | vias
15 | puentes_vehiculares
16 | puentes_peatonales
17 | acueductos
18 | alcantarillados
19 | centros_salud
20 | centros_educativos
21 | centros_comunitarios
22 | hectareas
23 | fuente_archivo
24 | evento_normalizado

In [122]:
display(eventos_limpio.head())

,id_evento,fecha,anio,departamento,municipio,divipola,evento,muertos,heridos,desaparecidos,...,puentes_vehiculares,puentes_peatonales,acueductos,alcantarillados,centros_salud,centros_educativos,centros_comunitarios,hectareas,fuente_archivo,evento_normalizado
0,1,2018-01-02,2018,CHOCO,LLORO,27413,ACCIDENTE FLUVIAL,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx,ACCIDENTE FLUVIAL
1,2,2018-01-12,2018,CHOCO,CARMEN DEL DARIEN,27150,INUNDACIÓN,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx,INUNDACIÓN
2,3,2018-01-18,2018,CHOCO,UNGUIA,27800,CRECIENTE SÚBITA,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx,CRECIENTE SÚBITA
3,4,2018-01-28,2018,CHOCO,RIOSUCIO,27615,INCENDIO ESTRUCTURAL,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx,INCENDIO ESTRUCTURAL
4,5,2018-02-04,2018,CHOCO,BAHIA SOLANO,27075,OTROS,0.0,21.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,EMERGENCIAS-2018.xlsx,OTROS

In [123]:
variables_afectacion = [
    "personas_afectadas",
    "familias_afectadas",
    "viviendas_destruidas",
    "viviendas_afectadas",
    "muertos",
    "heridos",
    "desaparecidos",
    "vias",
    "puentes_vehiculares",
    "puentes_peatonales",
    "acueductos",
    "alcantarillados",
    "centros_salud",
    "centros_educativos",
    "centros_comunitarios",
    "hectareas"
]

In [124]:
grupo = eventos_limpio.groupby(
    ["anio", "divipola", "municipio"],
    dropna=False
)

df07_municipio_anio = grupo.agg(
    registros_evento=("id_evento", "count"),
    tipos_evento=("evento", "nunique")
).reset_index()

In [125]:
for variable in variables_afectacion:
    
    temp = (
        grupo[variable]
        .sum(min_count=1)
        .reset_index(name=variable)
    )
    
    df07_municipio_anio = df07_municipio_anio.merge(
        temp,
        on=["anio", "divipola", "municipio"],
        how="left"
    )

In [126]:
print("Shape:", df07_municipio_anio.shape)
print("Municipios:", df07_municipio_anio["divipola"].nunique())
print("Años:", df07_municipio_anio["anio"].nunique())

display(
    df07_municipio_anio
    .sort_values(["anio", "divipola"])
    .head(20)
)

Shape: (217, 21)
Municipios: 31
Años: 8

,anio,divipola,municipio,registros_evento,tipos_evento,personas_afectadas,familias_afectadas,viviendas_destruidas,viviendas_afectadas,muertos,...,desaparecidos,vias,puentes_vehiculares,puentes_peatonales,acueductos,alcantarillados,centros_salud,centros_educativos,centros_comunitarios,hectareas
0,2018,27001,QUIBDO,7,6,7612.0,1716.0,19.0,501.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2018,27006,ACANDI,2,2,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018,27050,ATRATO,3,2,4995.0,999.0,0.0,120.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2018,27073,BAGADO,2,2,763.0,168.0,36.0,30.0,NaN,...,NaN,NaN,NaN,NaN,3.0,2.0,NaN,1.0,NaN,60.0
4,2018,27075,BAHIA SOLANO,1,1,21.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2018,27077,BAJO BAUDO,2,2,109.0,21.0,0.0,21.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2018,27099,BOJAYA,1,1,7000.0,1400.0,NaN,1400.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2018,27135,CANTON DE SAN PABLO,1,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2018,27150,CARMEN DEL DARIEN,6,4,330.0,2866.0,8.0,2858.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
9,2018,27205,CONDOTO,3,3,26.0,5.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2018,27245,EL CARMEN DE ATRATO,1,1,10.0,2.0,0.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
11,2018,27250,EL LITORAL DEL SAN JUAN,1,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2018,27361,ISTMINA,2,2,2451.0,490.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2018,27413,LLORO,5,2,4757.0,1579.0,1.0,289.0,2.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,4.0,1.0,0.0
14,2018,27425,MEDIO ATRATO,6,4,8432.0,1876.0,16.0,1617.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
15,2018,27430,MEDIO BAUDO,3,2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2018,27450,MEDIO SAN JUAN,1,1,1250.0,250.0,0.0,25.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2018,27491,NOVITA,2,2,2242.0,583.0,7.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18,2018,27580,RIO IRO,1,1,3.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2018,27600,RIO QUITO,1,1,145.0,29.0,0.0,29.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [127]:
display(
    df07_municipio_anio[
        [
            "anio",
            "divipola",
            "municipio",
            "registros_evento",
            "tipos_evento",
            "personas_afectadas",
            "familias_afectadas",
            "viviendas_afectadas"
        ]
    ].head(20)
)

,anio,divipola,municipio,registros_evento,tipos_evento,personas_afectadas,familias_afectadas,viviendas_afectadas
0,2018,27001,QUIBDO,7,6,7612.0,1716.0,501.0
1,2018,27006,ACANDI,2,2,3.0,0.0,0.0
2,2018,27050,ATRATO,3,2,4995.0,999.0,120.0
3,2018,27073,BAGADO,2,2,763.0,168.0,30.0
4,2018,27075,BAHIA SOLANO,1,1,21.0,0.0,0.0
5,2018,27077,BAJO BAUDO,2,2,109.0,21.0,21.0
6,2018,27099,BOJAYA,1,1,7000.0,1400.0,1400.0
7,2018,27135,CANTON DE SAN PABLO,1,1,0.0,0.0,0.0
8,2018,27150,CARMEN DEL DARIEN,6,4,330.0,2866.0,2858.0
9,2018,27205,CONDOTO,3,3,26.0,5.0,0.0
10,2018,27245,EL CARMEN DE ATRATO,1,1,10.0,2.0,2.0
11,2018,27250,EL LITORAL DEL SAN JUAN,1,1,0.0,0.0,0.0
12,2018,27361,ISTMINA,2,2,2451.0,490.0,0.0
13,2018,27413,LLORO,5,2,4757.0,1579.0,289.0
14,2018,27425,MEDIO ATRATO,6,4,8432.0,1876.0,1617.0
15,2018,27430,MEDIO BAUDO,3,2,0.0,0.0,0.0
16,2018,27450,MEDIO SAN JUAN,1,1,1250.0,250.0,25.0
17,2018,27491,NOVITA,2,2,2242.0,583.0,0.0
18,2018,27580,RIO IRO,1,1,3.0,0.0,0.0
19,2018,27600,RIO QUITO,1,1,145.0,29.0,29.0

In [128]:
cobertura_07_municipio_anio = pd.DataFrame({
    "variable": variables_afectacion,
    "registros_totales": len(df07_municipio_anio),
    "registros_no_nulos": [
        df07_municipio_anio[v].notna().sum()
        for v in variables_afectacion
    ]
})

cobertura_07_municipio_anio["registros_nulos"] = (
    cobertura_07_municipio_anio["registros_totales"]
    - cobertura_07_municipio_anio["registros_no_nulos"]
)

cobertura_07_municipio_anio["cobertura_pct"] = (
    cobertura_07_municipio_anio["registros_no_nulos"]
    / cobertura_07_municipio_anio["registros_totales"]
    * 100
).round(2)

display(cobertura_07_municipio_anio)

,variable,registros_totales,registros_no_nulos,registros_nulos,cobertura_pct
0,personas_afectadas,217,203,14,93.55
1,familias_afectadas,217,202,15,93.09
2,viviendas_destruidas,217,111,106,51.15
3,viviendas_afectadas,217,181,36,83.41
4,muertos,217,65,152,29.95
5,heridos,217,57,160,26.27
6,desaparecidos,217,25,192,11.52
7,vias,217,53,164,24.42
8,puentes_vehiculares,217,35,182,16.13
9,puentes_peatonales,217,40,177,18.43
10,acueductos,217,43,174,19.82
11,alcantarillados,217,27,190,12.44
12,centros_salud,217,38,179,17.51
13,centros_educativos,217,69,148,31.80
14,centros_comunitarios,217,41,176,18.89
15,hectareas,217,64,153,29.49

In [129]:
print("Municipio-año:", len(df07_municipio_anio))
print("Municipios:", df07_municipio_anio["divipola"].nunique())
print("Años:", sorted(df07_municipio_anio["anio"].unique()))

display(
    df07_municipio_anio
    .groupby("anio")["divipola"]
    .nunique()
    .rename("municipios_con_eventos")
    .to_frame()
)

Municipio-año: 217
Municipios: 31
Años: [2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

      municipios_con_eventos
anio
2018                      25
2019                      27
2020                      27
2021                      27
2022                      25
2023                      26
2024                      29
2025                      31

Dataset 07 — Emergencias y desastres

Estado: 🟢 Dataset cerrado / listo para integración

Ya tenemos:

Fuente: UNGRD.
Periodo: 2018–2025.
Unidad original: evento.
Clave territorial: DIVIPOLA.
862 eventos.
31 municipios.
217 municipio-año con registros.
evento_normalizado creado.
Inconsistencias evidentes de nombres de eventos identificadas y corregidas.
Variables de impacto auditadas.
Cobertura de cada variable documentada.
Los NA se conservan como faltantes; no se convierten automáticamente en cero.
La agregación municipio-año está construida.
La documentación metodológica ya contempla la unidad original y la unidad para el índice.

Candidatas principales

registros_evento
personas_afectadas
familias_afectadas
viviendas_afectadas

Variables de apoyo / no principales

viviendas_destruidas
muertos
heridos
desaparecidos
daños a infraestructura
hectareas

dataset_08_capacidad_institucional

In [130]:
path_08 = datasets["08_capacidad_institucional"]

df08 = pd.read_excel(path_08)

print("Shape:", df08.shape)

print("\nColumnas:")
for i, col in enumerate(df08.columns, start=1):
    print(f"{i:02d}. {col}")

Shape: (31, 12)

Columnas:
01. divipola
02. municipio
03. departamento
04. policia_registros_fuente
05. presencia_policia_en_directorio
06. observacion_policia
07. registros_ejercito_fuente
08. presencia_ejercito_en_archivo
09. observacion_ejercito
10. ips_total
11. servicios_urgencias
12. fuente_salud

In [131]:
ruta_08 = RAW / "dataset_08_capacidad_institucional_choco_v1.xlsx"
xls_08 = pd.ExcelFile(ruta_08)

print("Hojas disponibles:")
for i, hoja in enumerate(xls_08.sheet_names):
    print(f"{i:02d} | {hoja}")

Hojas disponibles:
00 | Municipio
01 | Policia_Choco
02 | Ejercito_Choco
03 | Diccionario
04 | Metodologia

In [132]:
for hoja in xls_08.sheet_names:
    df_temp = pd.read_excel(ruta_08, sheet_name=hoja)

    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print(f"Registros: {len(df_temp)}")
    
    display(df_temp.head(5))

================================================================================
HOJA: Municipio
Registros: 31

,divipola,municipio,departamento,policia_registros_fuente,presencia_policia_en_directorio,observacion_policia,registros_ejercito_fuente,presencia_ejercito_en_archivo,observacion_ejercito,ips_total,servicios_urgencias,fuente_salud
0,27001,Quibdó,Chocó,0,0,Sin registro en el archivo; no interpretar aut...,0,0,Sin registro municipal identificado en el arch...,NaN,NaN,Pendiente de incorporar REPS
1,27006,Acandí,Chocó,0,0,Sin registro en el archivo; no interpretar aut...,0,0,Sin registro municipal identificado en el arch...,NaN,NaN,Pendiente de incorporar REPS
2,27025,Alto Baudó,Chocó,0,0,Sin registro en el archivo; no interpretar aut...,0,0,Sin registro municipal identificado en el arch...,NaN,NaN,Pendiente de incorporar REPS
3,27050,Atrato,Chocó,3,1,Hay registro en el directorio cargado.,0,0,Sin registro municipal identificado en el arch...,NaN,NaN,Pendiente de incorporar REPS
4,27073,Bagadó,Chocó,0,0,Sin registro en el archivo; no interpretar aut...,0,0,Sin registro municipal identificado en el arch...,NaN,NaN,Pendiente de incorporar REPS

================================================================================
HOJA: Policia_Choco
Registros: 51

,DEPARTAMENTO,CIUDAD/MUNICIPIO,UNIDAD,TIPO UNIDAD,CODIGO_CUADRANTE,CUADRANTE,NUMERO_CELULAR_CUADRANTE,municipio_detectado
0,DEPARTAMENTO DE POLICIA CHOCO,ATRATO,ESTACION CARMEN DE ATRATO,ESTACION CARMEN DE ATRATO,DECHOMNVCCD01E04000000001,1,300,Atrato
1,DEPARTAMENTO DE POLICIA CHOCO,ATRATO,ESTACION CARMEN DE ATRATO,SUBESTACION DE POLICIA EL SIETE,DECHOMNVCCD01E04S01000001,1,3000000000,Atrato
2,DEPARTAMENTO DE POLICIA CHOCO,ALTO BAUDO (PIE DE PATO),ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO),ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO),DECHOMNVCCD04E05000000001,1,300,NaN
3,DEPARTAMENTO DE POLICIA CHOCO,ATRATO (YUTO),ESTACION DE POLICIA ATRATO (YUTO),ESTACION DE POLICIA ATRATO (YUTO),DECHOMNVCCD01E03000000001,1,300,Atrato
4,DEPARTAMENTO DE POLICIA CHOCO,BAGADO,ESTACION DE POLICIA BAGADO,ESTACION DE POLICIA BAGADO,DECHOMNVCCD04E06000000001,1,300,NaN

================================================================================
HOJA: Ejercito_Choco
Registros: 0

Empty DataFrame
Columns: [ZONA -DIM, DIRECCION, CIUDAD, TELEFONO, CORREO ELECTRÓNICO, municipio_detectado]
Index: []

================================================================================
HOJA: Diccionario
Registros: 7

,variable,definicion,fuente,calidad,regla
0,divipola,Código municipal DIVIPOLA,DANE / Dataset 01,🟢,Clave de unión.
1,policia_registros_fuente,Registros del municipio encontrados en el dire...,Policía Nacional,🟡,No equivale necesariamente a número de estacio...
2,presencia_policia_en_directorio,Existe al menos un registro del municipio en e...,Policía Nacional,🟡,"0 significa sin registro, no ausencia confirmada."
3,registros_ejercito_fuente,Registros del municipio encontrados en el arch...,Ejército Nacional,🟡,No equivale a capacidad operativa.
4,presencia_ejercito_en_archivo,Existe al menos un registro municipal en el ar...,Ejército Nacional,🟡,Mide presencia registrada en esta fuente.

================================================================================
HOJA: Metodologia
Registros: 7

            campo                                              valor
0         dataset                       08 — Capacidad institucional
1        universo                 Municipios de Chocó del Dataset 01
2   núcleo_actual           Policía + Ejército; salud pendiente REPS
3     descartadas  Cruz Roja, Defensa Civil, Bomberos, ambulancia...
4  regla_ausencia  La ausencia de un registro en una fuente no se...

Dataset 08
🟡 Dataset parcialmente construido — Policía disponible; Ejército no utilizable con la fuente actual; salud pendiente de REPS.

In [133]:
ruta_08 = r"dataset_08_capacidad_institucional_choco_v1.xlsx"

xls_08 = pd.ExcelFile(RAW / ruta_08)

print("Hojas:")
for i, hoja in enumerate(xls_08.sheet_names):
    print(f"{i:02d} | {hoja}")

Hojas:
00 | Municipio
01 | Policia_Choco
02 | Ejercito_Choco
03 | Diccionario
04 | Metodologia

In [134]:
for hoja in ["Policia_Choco", "Ejercito_Choco"]:
    
    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    
    df_temp = pd.read_excel(
        RAW / ruta_08,
        sheet_name=hoja
    )
    
    print("Shape:", df_temp.shape)
    print("Columnas:")
    
    for i, col in enumerate(df_temp.columns):
        print(f"{i:02d} | {col}")
    
    print("\nPrimeras filas:")
    display(df_temp.head(10))

================================================================================
HOJA: Policia_Choco
Shape: (51, 8)
Columnas:
00 | DEPARTAMENTO
01 | CIUDAD/MUNICIPIO
02 | UNIDAD
03 | TIPO UNIDAD
04 | CODIGO_CUADRANTE
05 | CUADRANTE
06 | NUMERO_CELULAR_CUADRANTE
07 | municipio_detectado

Primeras filas:

,DEPARTAMENTO,CIUDAD/MUNICIPIO,UNIDAD,TIPO UNIDAD,CODIGO_CUADRANTE,CUADRANTE,NUMERO_CELULAR_CUADRANTE,municipio_detectado
0,DEPARTAMENTO DE POLICIA CHOCO,ATRATO,ESTACION CARMEN DE ATRATO,ESTACION CARMEN DE ATRATO,DECHOMNVCCD01E04000000001,1,300,Atrato
1,DEPARTAMENTO DE POLICIA CHOCO,ATRATO,ESTACION CARMEN DE ATRATO,SUBESTACION DE POLICIA EL SIETE,DECHOMNVCCD01E04S01000001,1,3000000000,Atrato
2,DEPARTAMENTO DE POLICIA CHOCO,ALTO BAUDO (PIE DE PATO),ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO),ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO),DECHOMNVCCD04E05000000001,1,300,NaN
3,DEPARTAMENTO DE POLICIA CHOCO,ATRATO (YUTO),ESTACION DE POLICIA ATRATO (YUTO),ESTACION DE POLICIA ATRATO (YUTO),DECHOMNVCCD01E03000000001,1,300,Atrato
4,DEPARTAMENTO DE POLICIA CHOCO,BAGADO,ESTACION DE POLICIA BAGADO,ESTACION DE POLICIA BAGADO,DECHOMNVCCD04E06000000001,1,300,NaN
5,DEPARTAMENTO DE POLICIA CHOCO,BAGADO,ESTACION DE POLICIA BAGADO,SUBESTACION DE POLICIA SAN MARINO,DECHOMNVCCD04E06S01000001,1,3000000000,NaN
6,DEPARTAMENTO DE POLICIA CHOCO,BAHIA SOLANO,ESTACION DE POLICIA BAHIA SOLANO,ESTACION DE POLICIA BAHIA SOLANO,DECHOMNVCCD03E01000000001,1,300,NaN
7,DEPARTAMENTO DE POLICIA CHOCO,BAHIA SOLANO,ESTACION DE POLICIA BAHIA SOLANO,SUBESTACION DE POLICIA EL VALLE,DECHOMNVCCD03E01S01000001,1,3000000000,NaN
8,DEPARTAMENTO DE POLICIA CHOCO,BAJO BAUDO (PIZARRO),ESTACION DE POLICIA BAJO BAUDO (PIZARRO),ESTACION DE POLICIA BAJO BAUDO (PIZARRO),DECHOMNVCCD03E03000000001,1,300,NaN
9,DEPARTAMENTO DE POLICIA CHOCO,BOJAYA,ESTACION DE POLICIA BOJAYA,ESTACION DE POLICIA BOJAYA,DECHOMNVCCD01E06000000001,1,300,NaN

================================================================================
HOJA: Ejercito_Choco
Shape: (0, 6)
Columnas:
00 | ZONA -DIM
01 | DIRECCION
02 | CIUDAD
03 | TELEFONO
04 | CORREO ELECTRÓNICO
05 | municipio_detectado

Primeras filas:

Empty DataFrame
Columns: [ZONA -DIM, DIRECCION, CIUDAD, TELEFONO, CORREO ELECTRÓNICO, municipio_detectado]
Index: []

In [135]:
for hoja in ["Policia_Choco", "Ejercito_Choco"]:
    
    df_temp = pd.read_excel(
        RAW / ruta_08,
        sheet_name=hoja,
        header=None
    )
    
    print("\n" + "="*80)
    print(f"HOJA: {hoja}")
    print("Shape sin asumir encabezados:", df_temp.shape)
    
    display(df_temp.head(15))

================================================================================
HOJA: Policia_Choco
Shape sin asumir encabezados: (52, 8)

,0,1,2,3,4,5,6,7
0,DEPARTAMENTO,CIUDAD/MUNICIPIO,UNIDAD,TIPO UNIDAD,CODIGO_CUADRANTE,CUADRANTE,NUMERO_CELULAR_CUADRANTE,municipio_detectado
1,DEPARTAMENTO DE POLICIA CHOCO,ATRATO,ESTACION CARMEN DE ATRATO,ESTACION CARMEN DE ATRATO,DECHOMNVCCD01E04000000001,1,300,Atrato
2,DEPARTAMENTO DE POLICIA CHOCO,ATRATO,ESTACION CARMEN DE ATRATO,SUBESTACION DE POLICIA EL SIETE,DECHOMNVCCD01E04S01000001,1,3000000000,Atrato
3,DEPARTAMENTO DE POLICIA CHOCO,ALTO BAUDO (PIE DE PATO),ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO),ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO),DECHOMNVCCD04E05000000001,1,300,NaN
4,DEPARTAMENTO DE POLICIA CHOCO,ATRATO (YUTO),ESTACION DE POLICIA ATRATO (YUTO),ESTACION DE POLICIA ATRATO (YUTO),DECHOMNVCCD01E03000000001,1,300,Atrato
5,DEPARTAMENTO DE POLICIA CHOCO,BAGADO,ESTACION DE POLICIA BAGADO,ESTACION DE POLICIA BAGADO,DECHOMNVCCD04E06000000001,1,300,NaN
6,DEPARTAMENTO DE POLICIA CHOCO,BAGADO,ESTACION DE POLICIA BAGADO,SUBESTACION DE POLICIA SAN MARINO,DECHOMNVCCD04E06S01000001,1,3000000000,NaN
7,DEPARTAMENTO DE POLICIA CHOCO,BAHIA SOLANO,ESTACION DE POLICIA BAHIA SOLANO,ESTACION DE POLICIA BAHIA SOLANO,DECHOMNVCCD03E01000000001,1,300,NaN
8,DEPARTAMENTO DE POLICIA CHOCO,BAHIA SOLANO,ESTACION DE POLICIA BAHIA SOLANO,SUBESTACION DE POLICIA EL VALLE,DECHOMNVCCD03E01S01000001,1,3000000000,NaN
9,DEPARTAMENTO DE POLICIA CHOCO,BAJO BAUDO (PIZARRO),ESTACION DE POLICIA BAJO BAUDO (PIZARRO),ESTACION DE POLICIA BAJO BAUDO (PIZARRO),DECHOMNVCCD03E03000000001,1,300,NaN
10,DEPARTAMENTO DE POLICIA CHOCO,BOJAYA,ESTACION DE POLICIA BOJAYA,ESTACION DE POLICIA BOJAYA,DECHOMNVCCD01E06000000001,1,300,NaN
11,DEPARTAMENTO DE POLICIA CHOCO,CANTON DE SAN PABLO (MANAGRU),ESTACION DE POLICIA CANTON DE SAN PABLO (MANAGRU),ESTACION DE POLICIA CANTON DE SAN PABLO (MANAGRU),DECHOMNVCCD04E04000000001,1,300,NaN
12,DEPARTAMENTO DE POLICIA CHOCO,CERTEGUI,ESTACION DE POLICIA CERTEGUI,ESTACION DE POLICIA CERTEGUI,DECHOMNVCCD04E03000000001,1,300,NaN
13,DEPARTAMENTO DE POLICIA CHOCO,CONDOTO,ESTACION DE POLICIA CONDOTO,ESTACION DE POLICIA CONDOTO,DECHOMNVCCD02E03000000001,1,300,Condoto
14,DEPARTAMENTO DE POLICIA CHOCO,ISTMINA,ESTACION DE POLICIA ISTMINA,ESTACION DE POLICIA ISTMINA,DECHOMNVCCD02E01000000001,1,3174527787,Istmina

================================================================================
HOJA: Ejercito_Choco
Shape sin asumir encabezados: (1, 6)

,0,1,2,3,4,5
0,ZONA -DIM,DIRECCION,CIUDAD,TELEFONO,CORREO ELECTRÓNICO,municipio_detectado

1. Primero, diagnóstico general

In [136]:
policia = pd.read_excel(
    RAW / ruta_08,
    sheet_name="Policia_Choco"
)

print("Shape:", policia.shape)

print("\nMunicipios únicos en la fuente:")
print(policia["CIUDAD/MUNICIPIO"].nunique())

print("\nRegistros por municipio:")
display(
    policia["CIUDAD/MUNICIPIO"]
    .value_counts()
    .to_frame("registros")
)

Shape: (51, 8)

Municipios únicos en la fuente:
27

Registros por municipio:

                                registros
CIUDAD/MUNICIPIO
QUIBDO                                 15
ISTMINA                                 4
ATRATO                                  2
MEDIO BAUDO (PUERTO MELUK)              2
BAGADO                                  2
BAHIA SOLANO                            2
UNION PANAMERICANA (ANIMAS)             2
TADO                                    2
MEDIO SAN JUAN (ANDAGOYA)               2
VIGIA DEL FUERTE                        1
SIPI                                    1
RIO QUITO (PAIMADO)                     1
RIO IRO (SANTA RITA)                    1
NUQUI                                   1
NOVITA                                  1
LLORO                                   1
MEDIO ATRATO (BETE)                     1
ALTO BAUDO (PIE DE PATO)                1
LITORAL DEL SAN JUAN (DOCORDO)          1
JURADO                                  1
CONDOTO                                 1
CERTEGUI                                1
CANTON DE SAN PABLO (MANAGRU)           1
BOJAYA                                  1
BAJO BAUDO (PIZARRO)                    1
ATRATO (YUTO)                           1
CHOCONTA                                1

In [137]:
print("TIPO UNIDAD:")
display(
    policia["TIPO UNIDAD"]
    .value_counts(dropna=False)
    .to_frame("registros")
)

TIPO UNIDAD:

                                                    registros
TIPO UNIDAD
ESTACION DE POLICIA QUIBDO                                 14
ESTACION DE POLICIA ISTMINA                                 3
ESTACION CARMEN DE ATRATO                                   1
ESTACION DE POLICIA MEDIO BAUDO (PUERTO MELUK)              1
ESTACION DE POLICIA MEDIO SAN JUAN (ANDAGOYA)               1
SUBESTACION DE POLICIA BEBEDO                               1
ESTACION DE POLICIA NOVITA                                  1
ESTACION DE POLICIA NUQUI                                   1
SUBESTACION DE POLICIA TUTUNENDO                            1
ESTACION DE POLICIA RIO IRO (SANTA RITA)                    1
ESTACION DE POLICIA RIO QUITO (PAIMADO)                     1
ESTACION DE POLICIA SIPI                                    1
ESTACION DE POLICIA TADO                                    1
SUBESTACION DE POLICIA GUARATO                              1
ESTACION DE POLICIA UNION PANAMERICANA (ANIMAS)             1
SUBESTACION DE POLICIA EL DOS                               1
ESTACION DE POLICIA VIGIA DEL FUERTE                        1
SUBESTACION DE POLICIA PUERTO ECHEVERY                      1
ESTACION DE POLICIA MEDIO ATRATO (BETE)                     1
SUBESTACION DE POLICIA EL SIETE                             1
ESTACION DE POLICIA BAJO BAUDO (PIZARRO)                    1
ESTACION DE POLICIA ALTO BAUDO (PIE DE PATO)                1
ESTACION DE POLICIA ATRATO (YUTO)                           1
ESTACION DE POLICIA BAGADO                                  1
SUBESTACION DE POLICIA SAN MARINO                           1
ESTACION DE POLICIA BAHIA SOLANO                            1
SUBESTACION DE POLICIA EL VALLE                             1
ESTACION DE POLICIA BOJAYA                                  1
ESTACION DE POLICIA LLORO                                   1
ESTACION DE POLICIA CANTON DE SAN PABLO (MANAGRU)           1
ESTACION DE POLICIA CERTEGUI                                1
ESTACION DE POLICIA CONDOTO                                 1
SUBESTACION DE POLICIA PIE DE PEPE                          1
ESTACION DE POLICIA JURADO                                  1
ESTACION DE POLICIA LITORAL DEL SAN JUAN (DOCORDO)          1
ESTACION DE POLICIA CHOCONTA                                1

In [138]:
print("UNIDADES únicas:")
print(policia["UNIDAD"].nunique())

print("\nTIPO UNIDAD únicas:")
print(policia["TIPO UNIDAD"].nunique())

UNIDADES únicas:
27

TIPO UNIDAD únicas:
36

Quiero saber si policia_registros_fuente realmente está contando filas o si está contando otra cosa.

In [139]:
policia.groupby("CIUDAD/MUNICIPIO").agg(
    registros=("CIUDAD/MUNICIPIO", "size"),
    unidades=("UNIDAD", "nunique"),
    tipos_unidad=("TIPO UNIDAD", "nunique")
).sort_values("registros", ascending=False)

                                registros  unidades  tipos_unidad
CIUDAD/MUNICIPIO
QUIBDO                                 15         1             2
ISTMINA                                 4         1             2
MEDIO BAUDO (PUERTO MELUK)              2         1             2
UNION PANAMERICANA (ANIMAS)             2         1             2
BAGADO                                  2         1             2
BAHIA SOLANO                            2         1             2
TADO                                    2         1             2
ATRATO                                  2         1             2
MEDIO SAN JUAN (ANDAGOYA)               2         1             2
ALTO BAUDO (PIE DE PATO)                1         1             1
SIPI                                    1         1             1
RIO QUITO (PAIMADO)                     1         1             1
RIO IRO (SANTA RITA)                    1         1             1
NUQUI                                   1         1             1
NOVITA                                  1         1             1
LITORAL DEL SAN JUAN (DOCORDO)          1         1             1
MEDIO ATRATO (BETE)                     1         1             1
LLORO                                   1         1             1
JURADO                                  1         1             1
CONDOTO                                 1         1             1
CHOCONTA                                1         1             1
CERTEGUI                                1         1             1
CANTON DE SAN PABLO (MANAGRU)           1         1             1
BOJAYA                                  1         1             1
BAJO BAUDO (PIZARRO)                    1         1             1
ATRATO (YUTO)                           1         1             1
VIGIA DEL FUERTE                        1         1             1

cobertura sobre nuestros 31 municipios

In [140]:
municipios_fuente = set(
    policia["municipio_detectado"]
    .dropna()
    .str.strip()
)

if "df_municipio" in globals():
    municipios_iot = set(
        df_municipio["municipio"]
        .dropna()
        .astype(str)
        .str.strip()
    )
else:
    # Fallback: usar la lista oficial de municipios de Chocó que ya está en df_edu
    municipios_iot = set(
        df_edu.loc[
            df_edu["Departamento"].str.strip().str.lower().eq("chocó"),
            "Entidad"
        ]
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
    )

print("Municipios con registro:", len(municipios_fuente))
print("Municipios universo IOT:", len(municipios_iot))

print("\nMunicipios del universo sin registro:")
print(sorted(municipios_iot - municipios_fuente))

Municipios con registro: 5
Municipios universo IOT: 31

Municipios del universo sin registro:
['Acandí', 'Alto Baudó', 'Bagadó', 'Bahía Solano', 'Bajo Baudó', 'Bojayá', 'Carmen del Darién', 'Chocó', 'Cértegui', 'El Cantón del San Pablo', 'El Carmen de Atrato', 'El Litoral del San Juan', 'Juradó', 'Lloró', 'Medio Baudó', 'Nuquí', 'Nóvita', 'Quibdó', 'Riosucio', 'Río Iró', 'Río Quito', 'San José del Palmar', 'Sipí', 'Tadó', 'Unguía', 'Unión Panamericana']

In [141]:
policia[[
    "CIUDAD/MUNICIPIO",
    "municipio_detectado"
]].drop_duplicates().sort_values(
    ["CIUDAD/MUNICIPIO"]
)

                  CIUDAD/MUNICIPIO municipio_detectado
2         ALTO BAUDO (PIE DE PATO)                 NaN
0                           ATRATO              Atrato
3                    ATRATO (YUTO)              Atrato
4                           BAGADO                 NaN
6                     BAHIA SOLANO                 NaN
8             BAJO BAUDO (PIZARRO)                 NaN
9                           BOJAYA                 NaN
10   CANTON DE SAN PABLO (MANAGRU)                 NaN
11                        CERTEGUI                 NaN
50                        CHOCONTA                 NaN
12                         CONDOTO             Condoto
13                         ISTMINA             Istmina
17                          JURADO                 NaN
18  LITORAL DEL SAN JUAN (DOCORDO)                 NaN
19                           LLORO                 NaN
20             MEDIO ATRATO (BETE)        Medio Atrato
21      MEDIO BAUDO (PUERTO MELUK)                 NaN
23       MEDIO SAN JUAN (ANDAGOYA)      Medio San Juan
25                          NOVITA                 NaN
26                           NUQUI                 NaN
27                          QUIBDO                 NaN
42            RIO IRO (SANTA RITA)                 NaN
43             RIO QUITO (PAIMADO)                 NaN
44                            SIPI                 NaN
45                            TADO                 NaN
47     UNION PANAMERICANA (ANIMAS)                 NaN
49                VIGIA DEL FUERTE                 NaN

In [142]:
print(
    policia["CIUDAD/MUNICIPIO"]
    .drop_duplicates()
    .sort_values()
    .tolist()
)

['ALTO BAUDO (PIE DE PATO)', 'ATRATO', 'ATRATO (YUTO)', 'BAGADO', 'BAHIA SOLANO', 'BAJO BAUDO (PIZARRO)', 'BOJAYA', 'CANTON DE SAN PABLO (MANAGRU)', 'CERTEGUI', 'CHOCONTA', 'CONDOTO', 'ISTMINA', 'JURADO', 'LITORAL DEL SAN JUAN (DOCORDO)', 'LLORO', 'MEDIO ATRATO (BETE)', 'MEDIO BAUDO (PUERTO MELUK)', 'MEDIO SAN JUAN (ANDAGOYA)', 'NOVITA', 'NUQUI', 'QUIBDO', 'RIO IRO (SANTA RITA)', 'RIO QUITO (PAIMADO)', 'SIPI', 'TADO', 'UNION PANAMERICANA (ANIMAS)', 'VIGIA DEL FUERTE']

In [143]:
# Variables definidas actualmente en el notebook
variables = [
    nombre for nombre in globals()
    if not nombre.startswith("_")
]

print(f"Total de variables definidas: {len(variables)}")

for nombre in sorted(variables):
    print(nombre)

Total de variables definidas: 98
EPISODIO
In
Out
PROCESSED
Path
RAW
ROOT
archivo
archivos
archivos_raw
auditoria_01
auditoria_02
auditoria_03
auditoria_06
base
calidad
carpeta
carpetas_proyecto
cobertura_07_municipio_anio
cobertura_edu
col
columnas_base
columnas_vacias
comparacion
comparacion_gini
corr_05
datasets
df01
df02
df03
df05_socio
df06
df07_municipio_anio
df08
df_dim4
df_dim4_choco
df_edu
df_gini
df_temp
df_tmp
divipola_01
divipola_03
docs
eventos
eventos_limpio
existentes
exit
extras_03
faltantes
faltantes_03
get_ipython
grupo
hoja
i
inventario
mapa_eventos
metodologia_07
municipios_fuente
municipios_iot
n_antes
nombre
np
open
path
path_01
path_02
path_03
path_06
path_08
pd
policia
porcentajes
quit
registro
regla_nulos
root
ruta_06
ruta_07
ruta_08
ruta_dim4
ruta_gini
ruta_salida_03
tabla_indicadores_dim4
temp
texto
validate
variable
variables_05
variables_2025
variables_afectacion
variables_clave_02
variables_impacto
variables_numericas
xl
xls_06
xls_07
xls_08
xls_dim4

In [144]:
import pandas as pd

dataframes = []

for nombre, objeto in list(globals().items()):
    if not nombre.startswith("_") and isinstance(objeto, pd.DataFrame):
        dataframes.append({
            "variable": nombre,
            "filas": objeto.shape[0],
            "columnas": objeto.shape[1]
        })

df_variables = pd.DataFrame(dataframes)

df_variables.sort_values("variable")

                       variable   filas  columnas
2                  auditoria_01      20         5
4                  auditoria_02      41         5
6                  auditoria_03      13         5
18                 auditoria_06      29         5
23                      calidad      16         5
27  cobertura_07_municipio_anio      16         5
14                cobertura_edu      37         6
22                  comparacion       3         2
16                      corr_05      13        13
1                          df01      31        22
3                          df02      31        41
5                          df03      30        15
15                   df05_socio      31        19
17                         df06      31        29
25          df07_municipio_anio     217        21
28                         df08      31        12
8                       df_dim4  452990        13
9                 df_dim4_choco   12314        13
13                       df_edu   12314        13
7                       df_gini    1101         6
19                      df_temp       1         6
12                       df_tmp       5        31
11                         docs       4         4
20                      eventos     862        24
21               eventos_limpio     862        25
0                    inventario      23         4
24               metodologia_07      10         2
29                      policia      51         8
10       tabla_indicadores_dim4      37         6
26                         temp     217         4

In [145]:
[v for v in variables if any(
    palabra in v.lower()
    for palabra in ["institucional", "policia", "ejercito", "salud", "municipio"]
)]

['df07_municipio_anio',
 'cobertura_07_municipio_anio',
 'policia',
 'municipios_fuente',
 'municipios_iot']

dataset_08_capacidad_institucional

In [146]:
print(type(df08))

<class 'pandas.core.frame.DataFrame'>

In [147]:
print(df08.shape)

(31, 12)

In [148]:
print(df08.columns.tolist())

['divipola', 'municipio', 'departamento', 'policia_registros_fuente', 'presencia_policia_en_directorio', 'observacion_policia', 'registros_ejercito_fuente', 'presencia_ejercito_en_archivo', 'observacion_ejercito', 'ips_total', 'servicios_urgencias', 'fuente_salud']

In [149]:
print(type(municipios_iot))

<class 'set'>

In [150]:
print(type(municipios_fuente))

<class 'set'>

In [151]:
universo_08 = df08[["divipola", "municipio"]].copy()

universo_08.sort_values("municipio")

    divipola                municipio
1      27006                   Acandí
2      27025               Alto Baudó
3      27050                   Atrato
4      27073                   Bagadó
5      27075             Bahía Solano
6      27077               Bajo Baudó
7      27099                   Bojayá
9      27150        Carmen del Darién
11     27205                  Condoto
10     27160                 Cértegui
8      27135  El Cantón del San Pablo
12     27245      El Carmen de Atrato
13     27250  El Litoral del San Juan
14     27361                  Istmina
15     27372                   Juradó
16     27413                    Lloró
17     27425             Medio Atrato
18     27430              Medio Baudó
19     27450           Medio San Juan
21     27493    Nuevo Belén de Bajirá
22     27495                    Nuquí
20     27491                   Nóvita
0      27001                   Quibdó
25     27615                 Riosucio
23     27580                  Río Iró
24     27600                Río Quito
26     27660      San José del Palmar
27     27745                     Sipí
28     27787                     Tadó
29     27800                   Unguía
30     27810       Unión Panamericana

In [152]:
universo_08 = (
    df08[["divipola", "municipio"]]
    .drop_duplicates()
    .sort_values("municipio")
    .reset_index(drop=True)
)

print(universo_08.shape)
universo_08

(31, 2)

    divipola                municipio
0      27006                   Acandí
1      27025               Alto Baudó
2      27050                   Atrato
3      27073                   Bagadó
4      27075             Bahía Solano
5      27077               Bajo Baudó
6      27099                   Bojayá
7      27150        Carmen del Darién
8      27205                  Condoto
9      27160                 Cértegui
10     27135  El Cantón del San Pablo
11     27245      El Carmen de Atrato
12     27250  El Litoral del San Juan
13     27361                  Istmina
14     27372                   Juradó
15     27413                    Lloró
16     27425             Medio Atrato
17     27430              Medio Baudó
18     27450           Medio San Juan
19     27493    Nuevo Belén de Bajirá
20     27495                    Nuquí
21     27491                   Nóvita
22     27001                   Quibdó
23     27615                 Riosucio
24     27580                  Río Iró
25     27600                Río Quito
26     27660      San José del Palmar
27     27745                     Sipí
28     27787                     Tadó
29     27800                   Unguía
30     27810       Unión Panamericana

In [153]:
homologacion_policia = {
    "ALTO BAUDO (PIE DE PATO)": "Alto Baudó",
    "ATRATO": "Atrato",
    "ATRATO (YUTO)": "Atrato",
    "BAGADO": "Bagadó",
    "BAHIA SOLANO": "Bahía Solano",
    "BAJO BAUDO (PIZARRO)": "Bajo Baudó",
    "BOJAYA": "Bojayá",
    "CANTON DE SAN PABLO (MANAGRU)": "El Cantón del San Pablo",
    "CERTEGUI": "Cértegui",
    "CONDOTO": "Condoto",
    "ISTMINA": "Istmina",
    "JURADO": "Juradó",
    "LITORAL DEL SAN JUAN (DOCORDO)": "El Litoral del San Juan",
    "LLORO": "Lloró",
    "MEDIO ATRATO (BETE)": "Medio Atrato",
    "MEDIO BAUDO (PUERTO MELUK)": "Medio Baudó",
    "MEDIO SAN JUAN (ANDAGOYA)": "Medio San Juan",
    "NOVITA": "Nóvita",
    "NUQUI": "Nuquí",
    "QUIBDO": "Quibdó",
    "RIO IRO (SANTA RITA)": "Río Iró",
    "RIO QUITO (PAIMADO)": "Río Quito",
    "SIPI": "Sipí",
    "TADO": "Tadó",
    "UNION PANAMERICANA (ANIMAS)": "Unión Panamericana",
}

In [154]:

policia_homologado = policia.copy()

policia_homologado["municipio_homologado"] = (
    policia_homologado["CIUDAD/MUNICIPIO"]
    .str.strip()
    .str.upper()
    .map(homologacion_policia)
)

In [155]:
policia_homologado[
    policia_homologado["municipio_homologado"].isna()
]["CIUDAD/MUNICIPIO"].value_counts()

CIUDAD/MUNICIPIO
VIGIA DEL FUERTE    1
CHOCONTA            1
Name: count, dtype: int64

In [156]:
total = len(policia_homologado)

homologados = policia_homologado["municipio_homologado"].notna().sum()

print(f"Registros Policía: {total}")
print(f"Registros homologados: {homologados}")
print(f"Registros sin homologar: {total - homologados}")
print(f"Cobertura: {homologados / total * 100:.2f}%")

Registros Policía: 51
Registros homologados: 49
Registros sin homologar: 2
Cobertura: 96.08%

In [157]:
municipios_con_registro = (
    policia_homologado["municipio_homologado"]
    .dropna()
    .unique()
)

print(f"Municipios con registro: {len(municipios_con_registro)}")
print(f"Municipios universo: {len(universo_08)}")

Municipios con registro: 24
Municipios universo: 31

In [158]:
policia_homologado = policia_homologado.merge(
    universo_08,
    left_on="municipio_homologado",
    right_on="municipio",
    how="left",
    validate="many_to_one"
)

In [159]:
policia_homologado[
    ["CIUDAD/MUNICIPIO", "municipio_homologado", "municipio", "divipola"]
].drop_duplicates().sort_values("municipio_homologado")

,CIUDAD/MUNICIPIO,municipio_homologado,municipio,divipola
2,ALTO BAUDO (PIE DE PATO),Alto Baudó,Alto Baudó,27025.0
0,ATRATO,Atrato,Atrato,27050.0
3,ATRATO (YUTO),Atrato,Atrato,27050.0
4,BAGADO,Bagadó,Bagadó,27073.0
6,BAHIA SOLANO,Bahía Solano,Bahía Solano,27075.0
8,BAJO BAUDO (PIZARRO),Bajo Baudó,Bajo Baudó,27077.0
9,BOJAYA,Bojayá,Bojayá,27099.0
12,CONDOTO,Condoto,Condoto,27205.0
11,CERTEGUI,Cértegui,Cértegui,27160.0
10,CANTON DE SAN PABLO (MANAGRU),El Cantón del San Pablo,El Cantón del San Pablo,27135.0
18,LITORAL DEL SAN JUAN (DOCORDO),El Litoral del San Juan,El Litoral del San Juan,27250.0
13,ISTMINA,Istmina,Istmina,27361.0
17,JURADO,Juradó,Juradó,27372.0
19,LLORO,Lloró,Lloró,27413.0
20,MEDIO ATRATO (BETE),Medio Atrato,Medio Atrato,27425.0
21,MEDIO BAUDO (PUERTO MELUK),Medio Baudó,Medio Baudó,27430.0
23,MEDIO SAN JUAN (ANDAGOYA),Medio San Juan,Medio San Juan,27450.0
26,NUQUI,Nuquí,Nuquí,27495.0
25,NOVITA,Nóvita,Nóvita,27491.0
27,QUIBDO,Quibdó,Quibdó,27001.0
42,RIO IRO (SANTA RITA),Río Iró,Río Iró,27580.0
43,RIO QUITO (PAIMADO),Río Quito,Río Quito,27600.0
44,SIPI,Sipí,Sipí,27745.0
45,TADO,Tadó,Tadó,27787.0
47,UNION PANAMERICANA (ANIMAS),Unión Panamericana,Unión Panamericana,27810.0
49,VIGIA DEL FUERTE,NaN,NaN,NaN
50,CHOCONTA,NaN,NaN,NaN

In [160]:
policia_homologado[
    policia_homologado["municipio_homologado"].notna() &
    policia_homologado["divipola"].isna()
][["CIUDAD/MUNICIPIO", "municipio_homologado"]].drop_duplicates()

Empty DataFrame
Columns: [CIUDAD/MUNICIPIO, municipio_homologado]
Index: []

In [161]:
# Cobertura de homologación
auditoria_homologacion = pd.DataFrame({
    "total_registros": [len(policia_homologado)],
    "homologados": [
        policia_homologado["municipio_homologado"].notna().sum()
    ],
    "fuera_universo": [
        policia_homologado["municipio_homologado"].isna().sum()
    ]
})

auditoria_homologacion["cobertura_pct"] = (
    auditoria_homologacion["homologados"]
    / auditoria_homologacion["total_registros"] * 100
).round(2)

auditoria_homologacion

   total_registros  homologados  fuera_universo  cobertura_pct
0               51           49               2          96.08

In [162]:
municipios_policia = (
    policia_homologado[
        policia_homologado["municipio_homologado"].notna()
    ]
    .groupby(
        ["divipola", "municipio_homologado"],
        as_index=False
    )
    .size()
    .rename(columns={"size": "registros_policia"})
    .sort_values("registros_policia", ascending=False)
)

municipios_policia

    divipola     municipio_homologado  registros_policia
0    27001.0                   Quibdó                 15
11   27361.0                  Istmina                  4
2    27050.0                   Atrato                  3
22   27787.0                     Tadó                  2
16   27450.0           Medio San Juan                  2
15   27430.0              Medio Baudó                  2
23   27810.0       Unión Panamericana                  2
4    27075.0             Bahía Solano                  2
3    27073.0                   Bagadó                  2
7    27135.0  El Cantón del San Pablo                  1
21   27745.0                     Sipí                  1
20   27600.0                Río Quito                  1
19   27580.0                  Río Iró                  1
18   27495.0                    Nuquí                  1
17   27491.0                   Nóvita                  1
5    27077.0               Bajo Baudó                  1
8    27160.0                 Cértegui                  1
14   27425.0             Medio Atrato                  1
13   27413.0                    Lloró                  1
1    27025.0               Alto Baudó                  1
6    27099.0                   Bojayá                  1
10   27250.0  El Litoral del San Juan                  1
9    27205.0                  Condoto                  1
12   27372.0                   Juradó                  1

In [163]:
municipios_con_policia = set(
    municipios_policia["divipola"]
)

universo_divipola = set(
    universo_08["divipola"]
)

print("Municipios universo:", len(universo_divipola))
print("Municipios con Policía:", len(municipios_con_policia))
print(
    "Municipios sin registro:",
    len(universo_divipola - municipios_con_policia)
)

Municipios universo: 31
Municipios con Policía: 24
Municipios sin registro: 7

In [164]:
policia_agregado = (
    policia_homologado
    .dropna(subset=["divipola"])
    .groupby("divipola")
    .size()
    .reset_index(name="policia_registros_fuente")
)

policia_agregado["divipola"] = (
    policia_agregado["divipola"]
    .astype(int)
)

policia_agregado["presencia_policia_en_directorio"] = 1

In [165]:
df08 = universo_08.merge(
    policia_agregado,
    on="divipola",
    how="left"
)

df08["policia_registros_fuente"] = (
    df08["policia_registros_fuente"]
    .fillna(0)
    .astype(int)
)

df08["presencia_policia_en_directorio"] = (
    df08["presencia_policia_en_directorio"]
    .fillna(0)
    .astype(int)
)

In [166]:
print(df08.shape)
print(df08[[
    "divipola",
    "municipio",
    "policia_registros_fuente",
    "presencia_policia_en_directorio"
]].sort_values("municipio"))

(31, 4)
    divipola                municipio  policia_registros_fuente  \
0      27006                   Acandí                         0
1      27025               Alto Baudó                         1
2      27050                   Atrato                         3
3      27073                   Bagadó                         2
4      27075             Bahía Solano                         2
5      27077               Bajo Baudó                         1
6      27099                   Bojayá                         1
7      27150        Carmen del Darién                         0
8      27205                  Condoto                         1
9      27160                 Cértegui                         1
10     27135  El Cantón del San Pablo                         1
11     27245      El Carmen de Atrato                         0
12     27250  El Litoral del San Juan                         1
13     27361                  Istmina                         4
14     27372                   Juradó                         1
15     27413                    Lloró                         1
16     27425             Medio Atrato                         1
17     27430              Medio Baudó                         2
18     27450           Medio San Juan                         2
19     27493    Nuevo Belén de Bajirá                         0
20     27495                    Nuquí                         1
21     27491                   Nóvita                         1
22     27001                   Quibdó                        15
23     27615                 Riosucio                         0
24     27580                  Río Iró                         1
25     27600                Río Quito                         1
26     27660      San José del Palmar                         0
27     27745                     Sipí                         1
28     27787                     Tadó                         2
29     27800                   Unguía                         0
30     27810       Unión Panamericana                         2

    presencia_policia_en_directorio
0                                 0
1                                 1
2                                 1
3                                 1
4                                 1
5                                 1
6                                 1
7                                 0
8                                 1
9                                 1
10                                1
11                                0
12                                1
13                                1
14                                1
15                                1
16                                1
17                                1
18                                1
19                                0
20                                1
21                                1
22                                1
23                                0
24                                1
25                                1
26                                0
27                                1
28                                1
29                                0
30                                1

In [167]:
print(
    "Con presencia:",
    df08["presencia_policia_en_directorio"].sum()
)

print(
    "Sin registro:",
    (df08["presencia_policia_en_directorio"] == 0).sum()
)

print(
    "Total:",
    len(df08)
)

Con presencia: 24
Sin registro: 7
Total: 31

In [168]:
print(type(df08))
print(df08.shape)
print(df08.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
(31, 4)
['divipola', 'municipio', 'policia_registros_fuente', 'presencia_policia_en_directorio']

In [169]:
print(df08.head())

   divipola     municipio  policia_registros_fuente  \
0     27006        Acandí                         0
1     27025    Alto Baudó                         1
2     27050        Atrato                         3
3     27073        Bagadó                         2
4     27075  Bahía Solano                         2

   presencia_policia_en_directorio
0                                0
1                                1
2                                1
3                                1
4                                1

In [170]:
df08["registros_ejercito_fuente"] = pd.NA
df08["presencia_ejercito_en_archivo"] = pd.NA
df08["observacion_ejercito"] = (
    "Fuente sin registros; no permite inferir ausencia institucional."
)

In [171]:
print(xls_08.sheet_names)

['Municipio', 'Policia_Choco', 'Ejercito_Choco', 'Diccionario', 'Metodologia']

In [173]:
ejercito_fuente = pd.read_excel(
    RAW / ruta_08,
    sheet_name="Ejercito_Choco"
)

print(ejercito_fuente.shape)
print(ejercito_fuente.columns.tolist())

(0, 6)
['ZONA -DIM', 'DIRECCION', 'CIUDAD', 'TELEFONO', 'CORREO ELECTRÓNICO', 'municipio_detectado']

La fuente de Ejército está disponible en el archivo, pero la hoja Ejercito_Choco no contiene registros. Esta ausencia no permite determinar ausencia de presencia institucional en los municipios.

In [174]:
df08["registros_ejercito_fuente"] = pd.NA

df08["presencia_ejercito_en_archivo"] = pd.NA

df08["observacion_ejercito"] = (
    "La hoja Ejercito_Choco no contiene registros; "
    "no permite inferir ausencia institucional."
)

Contruimos fuentes de salud en el dataset 08.

In [175]:
print("Variables relacionadas con salud:")
print([x for x in globals() if "reps" in x.lower() or "salud" in x.lower() or "ips" in x.lower()])

Variables relacionadas con salud:
[]

In [176]:
print("Variables relacionadas con salud:")
print([x for x in globals() if "reps" in x.lower() or "salud" in x.lower() or "ips" in x.lower()])

Variables relacionadas con salud:
[]

Buscamos el nuevo archivo que queremos homologar por Dipola. Archivo sobre salud.

In [177]:
archivos_raw = list(Path(RAW).glob("*"))

for archivo in archivos_raw:
    print(archivo.name)

dataset_01_poblacion_territorio_choco.csv
dataset_01_poblacion_territorio_choco_definitivo.csv
dataset_02_conectividad_digital_choco_v2.csv
dataset_03_conectividad_fisica_choco_final.csv
dataset_05_condiciones_socioeconomicas_choco_final.csv
dataset_06_informacion_comunicacion_choco_v1.xlsx
dataset_07_emergencias_desastres_choco_final(1).xlsx
dataset_08_capacidad_institucional_choco_v1.xlsx
dataset_09_inversion_publica_infraestructura_choco_v1.xlsx
dataset_10_historia_evidencia_cualitativa_choco_v1.xlsx
Divipola_Serv_PuntosCentrosPoblados2013I.pitemx
Documento_Dataset_03_Conectividad_Fisica_Choco.docx
GiniMovilidad.csv
Registro_Especial_de_Prestadores_y_Sedes_de_Servicios_de_Salud_20260818.csv
TerriData_Dim4.xlsx
TerriData_Dim5.xlsx
Visor-TCCN.xlsx

In [180]:
archivos_salud = list(Path(RAW).glob("*Registro_Especial_de_Prestadores*"))

for archivo in archivos_salud:
    print(archivo)

C:\Users\USUARIO\Desktop\Colombia_en_datos\episodios\002_EL_chocó\Data\raw\Registro_Especial_de_Prestadores_y_Sedes_de_Servicios_de_Salud_20260818.csv

In [181]:
salud = pd.read_csv(
    archivos_salud[0],
    low_memory=False
)

print(type(salud))
print(salud.shape)
print(salud.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
(76821, 22)
['CodigoPrestador', 'NombrePrestador', 'CodigoHabilitacionSede', 'NombreSede', 'TipoIdentificacion', 'NumeroIdentificacion', 'NaturalezaJuridica', 'ESE', 'MunicipioPrestador', 'DepartamentoPrestadorDesc', 'MunicipioPrestadorDesc', 'DireccionPrestador', 'EmailPrestador', 'TelefonoPrestador', 'MunicipioSede', 'DepartamentoSedeDesc', 'MunicipioSedeDesc', 'DireccionSede', 'EmailSede', 'TelefonoSede', 'ClasePrestadorDesc', 'FechaCorte']

Exploración inicial.

In [186]:
print(salud["ClasePrestadorDesc"].value_counts(dropna=False))

ClasePrestadorDesc
Profesional Independiente                                        54657
Instituciones Prestadoras de Servicios de Salud - IPS            19551
Objeto Social Diferente a la Prestación de Servicios de Salud     2107
Transporte Especial de Pacientes                                   506
Name: count, dtype: int64

In [187]:
print("Prestadores únicos:", salud["CodigoPrestador"].nunique())
print("Sedes únicas:", salud["CodigoHabilitacionSede"].nunique())

Prestadores únicos: 61073
Sedes únicas: 76821

In [188]:
print(
    salud[
        [
            "CodigoPrestador",
            "CodigoHabilitacionSede",
            "NombrePrestador",
            "NombreSede",
            "MunicipioSedeDesc",
            "DepartamentoSedeDesc",
            "ClasePrestadorDesc"
        ]
    ].head(20)
)

   CodigoPrestador CodigoHabilitacionSede  \
0       9100100017           910010001701
1       9100100019           910010001901
2       9100100019           912630001911
3       9100100019           914050001914
4       9100100019           914070001915
5       9100100019           914300001916
6       9100100019           914600001917
7       9100100019           915300001918
8       9100100019           915360001920
9       9100100019           915400001925
10      9100100019           916690001926
11      9100100019           917980001927
12      9100100022           910010002201
13      9100100036           910010003601
14      9100100037           910010003701
15      9100100038           910010003801
16      9100100039           910010003901
17      9100100057           910010005701
18      9100100060           910010006001
19      9100100069           910010006901

                                      NombrePrestador  \
0                         MANUEL DE JESUS LUBO OROZCO
1               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
2               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
3               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
4               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
5               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
6               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
7               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
8               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
9               E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
10              E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
11              E.S.E. HOSPITAL SAN RAFAEL DE LETICIA
12  Unidad Administrativa Especial de Aeronáutica ...
13                        VICTOR FIDEL GODOY CASTILLO
14                      JORGE ALEJANDRO PALACIOS DIEZ
15                             ANA LUCIA DIAZ GUEVARA
16                          CESAR MAURICIO DIAZ ROJAS
17                              Liliana Pineda Fierro
18                              Esperanza Boada Ortiz
19                          FUNDACION CLINICA LETICIA

                                           NombreSede MunicipioSedeDesc  \
0                         MANUEL DE JESUS LUBO OROZCO           LETICIA
1                          E.S.E. HOSPITAL SAN RAFAEL           LETICIA
2   CENTRO DE SALUD SAN RAFAEL - E.S.E HOSPITAL SA...        EL ENCANTO
3   CENTRO DE SALUD DE LA CHORRERA- E.S.E HOSPITAL...       LA CHORRERA
4   CENTRO DE SALUD DE LA PEDRERA - E.S.E HOSPITAL...        LA PEDRERA
5               LA VICTORIA ESE SAN FARAEL DE LETICIA       LA VICTORIA
6   CENTRO DE SALUD DE MIRITÍ - PARANÁ - E.S.E HOS...   MIRITI - PARANÁ
7   PUESTO DE SALUD DE PUERTO ALEGRÍA - E.S.E HOSP...    PUERTO ALEGRÍA
8   CENTRO DE SALUD DE PUERTO ARICA - E.S.E HOSPIT...      PUERTO ARICA
9   HOSPITAL LOCAL DE PUERTO NARIÑO - E.S.E HOSPIT...     PUERTO NARIÑO
10  CENTRO DE SALUD DE PUERTO SANTANDER - E.S.E HO...  PUERTO SANTANDER
11  CENTRO DE SALUD TARAPACÁ - E.S.E HOSPITAL SAN ...          TARAPACÁ
12                      SANIDAD AEROPORTUARIA LETICIA           LETICIA
13                        VICTOR FIDEL GODOY CASTILLO           LETICIA
14                      JORGE ALEJANDRO PALACIOS DIEZ           LETICIA
15                             ANA LUCIA DIAZ GUEVARA           LETICIA
16                          CESAR MAURICIO DIAZ ROJAS           LETICIA
17                              Liliana Pineda Fierro           LETICIA
18                              Esperanza Boada Ortiz           LETICIA
19                          FUNDACION CLINICA LETICIA           LETICIA

   DepartamentoSedeDesc                                 ClasePrestadorDesc
0              Amazonas                          Profesional Independiente
1              Amazonas  Instituciones Prestadoras de Servicios de Salu...
2              Amazonas  Instituciones Prestadoras de Servicios de Salu...
3              Amazonas  Instituciones Prestadoras de Servicios de Salu...
4              Amazonas  Instituciones Prestadoras de Servicios de Salu...
5              Amazonas  Instituciones Prestadoras de Servicios de Salu...
6              Amazonas  Instituciones Prestadoras de Servicios de Salu...
7              Amazonas  Instituciones Prestadoras de Servicios de Salu...
8              Amazonas  Instituciones Prestadoras de Servicios de Salu...
9              Amazonas  Instituciones Prestadoras de Servicios de Salu...
10             Amazonas  Instituciones Prestadoras de Servicios de Salu...
11             Amazonas  Instituciones Prestadoras de Servicios de Salu...
12             Amazonas  Objeto Social Diferente a la Prestación de Ser...
13             Amazonas                          Profesional Independiente
14             Amazonas                          Profesional Independiente
15             Amazonas                          Profesional Independiente
16             Amazonas                          Profesional Independiente
17             Amazonas                          Profesional Independiente
18             Amazonas                          Profesional Independiente
19             Amazonas  Instituciones Prestadoras de Servicios de Salu...

In [189]:
print(
    salud.groupby("CodigoHabilitacionSede")
         .size()
         .value_counts()
         .sort_index()
         .head(20)
)

1    76821
Name: count, dtype: int64

no todas las filas son IPS. En la muestra aparecen:

Instituciones Prestadoras de Servicios de Salud...
Profesional Independiente
Objeto Social Diferente a la Prestación de Servicios de Salud...

Por tanto, no podemos simplemente contar todas las sedes.

In [190]:
salud["ClasePrestadorDesc"].value_counts(dropna=False)

ClasePrestadorDesc
Profesional Independiente                                        54657
Instituciones Prestadoras de Servicios de Salud - IPS            19551
Objeto Social Diferente a la Prestación de Servicios de Salud     2107
Transporte Especial de Pacientes                                   506
Name: count, dtype: int64

In [191]:
salud["DepartamentoSedeDesc"].value_counts().head(10)

DepartamentoSedeDesc
Antioquia             16822
Bogotá D.C            16181
Valle del cauca        7500
Cundinamarca           3568
Santander              3455
Atlántico              2938
Nariño                 2392
Bolívar                2120
Norte de Santander     2037
Boyacá                 1954
Name: count, dtype: int64

Filtrar chocó

In [192]:
salud_choco = salud[
    salud["DepartamentoSedeDesc"].str.upper().eq("CHOCÓ")
].copy()

print("Filas Chocó:", len(salud_choco))
print(
    "Sedes únicas Chocó:",
    salud_choco["CodigoHabilitacionSede"].nunique()
)

print(
    "Municipios Chocó:",
    salud_choco["MunicipioSedeDesc"].nunique()
)

Filas Chocó: 410
Sedes únicas Chocó: 410
Municipios Chocó: 32

In [193]:
print(
    salud_choco[
        [
            "CodigoPrestador",
            "CodigoHabilitacionSede",
            "MunicipioSedeDesc",
            "ClasePrestadorDesc"
        ]
    ].head(20)
)

      CodigoPrestador CodigoHabilitacionSede MunicipioSedeDesc  \
45410      2700100004           270010000401            QUIBDÓ
45411      2700100010           270010001001            QUIBDÓ
45412      2700100019           270010001901            QUIBDÓ
45413      2700100026           270010002601            QUIBDÓ
45414      2700100026           270010002602            QUIBDÓ
45415      2700100026           270010002604            QUIBDÓ
45416      2700100026           270010002605            QUIBDÓ
45417      2700100026           270010002607            QUIBDÓ
45418      2700100026           270010002608            QUIBDÓ
45419      2700100026           270010002609            QUIBDÓ
45420      2700100026           270010002610            QUIBDÓ
45421      2700100026           270010002611            QUIBDÓ
45422      2700100026           270010002612            QUIBDÓ
45423      2700100026           270010002613            QUIBDÓ
45424      2700100026           270010002614            QUIBDÓ
45425      2700100026           270010002615            QUIBDÓ
45426      2700100026           270010002616            QUIBDÓ
45427      2700100026           270010002617            QUIBDÓ
45428      2700100026           270010002618            QUIBDÓ
45429      2700100026           270010002619            QUIBDÓ

                                      ClasePrestadorDesc
45410                          Profesional Independiente
45411                          Profesional Independiente
45412  Instituciones Prestadoras de Servicios de Salu...
45413  Instituciones Prestadoras de Servicios de Salu...
45414  Instituciones Prestadoras de Servicios de Salu...
45415  Instituciones Prestadoras de Servicios de Salu...
45416  Instituciones Prestadoras de Servicios de Salu...
45417  Instituciones Prestadoras de Servicios de Salu...
45418  Instituciones Prestadoras de Servicios de Salu...
45419  Instituciones Prestadoras de Servicios de Salu...
45420  Instituciones Prestadoras de Servicios de Salu...
45421  Instituciones Prestadoras de Servicios de Salu...
45422  Instituciones Prestadoras de Servicios de Salu...
45423  Instituciones Prestadoras de Servicios de Salu...
45424  Instituciones Prestadoras de Servicios de Salu...
45425  Instituciones Prestadoras de Servicios de Salu...
45426  Instituciones Prestadoras de Servicios de Salu...
45427  Instituciones Prestadoras de Servicios de Salu...
45428  Instituciones Prestadoras de Servicios de Salu...
45429  Instituciones Prestadoras de Servicios de Salu...

In [194]:
ips_choco = salud_choco[
    salud_choco["ClasePrestadorDesc"]
    .eq("Instituciones Prestadoras de Servicios de Salud - IPS")
].copy()

print("Sedes IPS Chocó:", len(ips_choco))
print("Municipios con IPS:", ips_choco["MunicipioSedeDesc"].nunique())

print(
    ips_choco["MunicipioSedeDesc"]
    .value_counts()
)

Sedes IPS Chocó: 280
Municipios con IPS: 32
MunicipioSedeDesc
QUIBDÓ                     146
ISTMINA                     18
TADÓ                        11
ALTO BAUDO                   8
RIOSUCIO                     7
EL LITORAL DEL SAN JUAN      5
UNIÓN PANAMERICANA           5
NUEVO BELÉN DE BAJIRÁ        5
BAJO BAUDÓ                   5
MEDIO BAUDÓ                  4
ACANDÍ                       4
BAGADÓ                       4
BOJAYA                       4
BELÉN DE BAJIRÁ              4
EL CANTÓN DEL SAN PABLO      4
CARMEN DEL DARIEN            4
NUQUÍ                        3
BAHÍA SOLANO                 3
RÍO IRO                      3
CÉRTEGUI                     3
MEDIO SAN JUAN               3
UNGUÍA                       3
MEDIO ATRATO                 3
ATRATO                       3
CONDOTO                      3
LLORÓ                        3
NÓVITA                       2
SAN JOSÉ DEL PALMAR          2
SIPÍ                         2
EL CARMEN DE ATRATO          2
JURADÓ                       2
RÍO QUITO                    2
Name: count, dtype: int64

In [196]:
universo_iot = df08[["divipola", "municipio"]].copy()

universo_iot["municipio_norm"] = (
    universo_iot["municipio"]
    .str.strip()
    .str.upper()
)

municipios_reps = set(
    salud_choco["MunicipioSedeDesc"]
    .dropna()
    .str.strip()
    .str.upper()
)

municipios_iot = set(universo_iot["municipio_norm"])

print("Municipios REPS:", len(municipios_reps))
print("Municipios IOT:", len(municipios_iot))

print("\nREPS pero no IOT:")
print(sorted(municipios_reps - municipios_iot))

print("\nIOT pero no REPS:")
print(sorted(municipios_iot - municipios_reps))

Municipios REPS: 32
Municipios IOT: 31

REPS pero no IOT:
['ALTO BAUDO', 'BELÉN DE BAJIRÁ', 'BOJAYA', 'CARMEN DEL DARIEN', 'RÍO IRO']

IOT pero no REPS:
['ALTO BAUDÓ', 'BOJAYÁ', 'CARMEN DEL DARIÉN', 'RÍO IRÓ']

In [197]:
salud_choco[
    salud_choco["MunicipioSedeDesc"].isin([
        "BELÉN DE BAJIRÁ",
        "NUEVO BELÉN DE BAJIRÁ"
    ])
][[
    "CodigoPrestador",
    "CodigoHabilitacionSede",
    "MunicipioSedeDesc",
    "DepartamentoSedeDesc"
]].drop_duplicates()

,CodigoPrestador,CodigoHabilitacionSede,MunicipioSedeDesc,DepartamentoSedeDesc
45488,2700100643,274930064326,NUEVO BELÉN DE BAJIRÁ,Chocó
45548,2700101140,274930114011,NUEVO BELÉN DE BAJIRÁ,Chocó
45573,2700101253,270860125303,BELÉN DE BAJIRÁ,Chocó
45667,2700601062,270860106203,BELÉN DE BAJIRÁ,Chocó
45668,2700601062,274930106204,NUEVO BELÉN DE BAJIRÁ,Chocó
45689,2708601404,270860140401,BELÉN DE BAJIRÁ,Chocó
45690,2708601414,270860141401,BELÉN DE BAJIRÁ,Chocó
45691,2708601414,274930141402,NUEVO BELÉN DE BAJIRÁ,Chocó
45692,2708601421,270860142101,BELÉN DE BAJIRÁ,Chocó
45757,2749301193,274930119301,NUEVO BELÉN DE BAJIRÁ,Chocó
45758,2749301466,274930146601,NUEVO BELÉN DE BAJIRÁ,Chocó
45759,2761500697,274930069703,NUEVO BELÉN DE BAJIRÁ,Chocó

In [198]:
salud_choco[
    salud_choco["MunicipioSedeDesc"].isin([
        "BELÉN DE BAJIRÁ",
        "NUEVO BELÉN DE BAJIRÁ"
    ])
].assign(
    divipola_reps=lambda x:
        x["CodigoHabilitacionSede"].astype(str).str[:5]
)[[
    "MunicipioSedeDesc",
    "CodigoHabilitacionSede",
    "divipola_reps"
]].drop_duplicates()

           MunicipioSedeDesc CodigoHabilitacionSede divipola_reps
45488  NUEVO BELÉN DE BAJIRÁ           274930064326         27493
45548  NUEVO BELÉN DE BAJIRÁ           274930114011         27493
45573        BELÉN DE BAJIRÁ           270860125303         27086
45667        BELÉN DE BAJIRÁ           270860106203         27086
45668  NUEVO BELÉN DE BAJIRÁ           274930106204         27493
45689        BELÉN DE BAJIRÁ           270860140401         27086
45690        BELÉN DE BAJIRÁ           270860141401         27086
45691  NUEVO BELÉN DE BAJIRÁ           274930141402         27493
45692        BELÉN DE BAJIRÁ           270860142101         27086
45757  NUEVO BELÉN DE BAJIRÁ           274930119301         27493
45758  NUEVO BELÉN DE BAJIRÁ           274930146601         27493
45759  NUEVO BELÉN DE BAJIRÁ           274930069703         27493

In [200]:
print(type(municipios_iot))
print(len(municipios_iot))
print(list(municipios_iot)[:10])

<class 'set'>
31
['MEDIO BAUDÓ', 'NUEVO BELÉN DE BAJIRÁ', 'CÉRTEGUI', 'CARMEN DEL DARIÉN', 'EL CANTÓN DEL SAN PABLO', 'JURADÓ', 'EL CARMEN DE ATRATO', 'LLORÓ', 'RIOSUCIO', 'UNGUÍA']

In [201]:
salud_choco["divipola_reps"] = (
    salud_choco["CodigoHabilitacionSede"]
    .astype(str)
    .str[:5]
    .astype("Int64")
)

salud_choco["en_universo_iot"] = (
    salud_choco["divipola_reps"]
    .isin(universo_divipola)
)

print("Sedes Chocó:", len(salud_choco))
print(
    "Sedes dentro del universo IOT:",
    salud_choco["en_universo_iot"].sum()
)

Sedes Chocó: 410
Sedes dentro del universo IOT: 405

In [202]:
fuera_iot = salud_choco[
    ~salud_choco["en_universo_iot"]
][[
    "CodigoHabilitacionSede",
    "CodigoPrestador",
    "MunicipioSedeDesc",
    "DepartamentoSedeDesc",
    "divipola_reps"
]].drop_duplicates()

print(fuera_iot.to_string(index=False))

CodigoHabilitacionSede CodigoPrestador MunicipioSedeDesc DepartamentoSedeDesc  divipola_reps
          270860125303      2700101253   BELÉN DE BAJIRÁ                Chocó          27086
          270860106203      2700601062   BELÉN DE BAJIRÁ                Chocó          27086
          270860140401      2708601404   BELÉN DE BAJIRÁ                Chocó          27086
          270860141401      2708601414   BELÉN DE BAJIRÁ                Chocó          27086
          270860142101      2708601421   BELÉN DE BAJIRÁ                Chocó          27086

In [203]:
print(
    salud_choco.loc[
        ~salud_choco["en_universo_iot"],
        "MunicipioSedeDesc"
    ].value_counts()
)

MunicipioSedeDesc
BELÉN DE BAJIRÁ    5
Name: count, dtype: int64

Filtrar únicamente IPS

In [204]:
ips_choco = salud_choco[
    (salud_choco["ClasePrestadorDesc"] == 
     "Instituciones Prestadoras de Servicios de Salud - IPS")
    &
    (salud_choco["en_universo_iot"])
].copy()

print("Sedes IPS dentro del universo:", len(ips_choco))
print("Municipios con IPS:", ips_choco["divipola_reps"].nunique())

Sedes IPS dentro del universo: 276
Municipios con IPS: 31

In [205]:
ips_municipio = (
    ips_choco
    .groupby("divipola_reps")
    ["CodigoHabilitacionSede"]
    .nunique()
    .reset_index(name="ips_total")
    .rename(columns={"divipola_reps": "divipola"})
)

ips_municipio = ips_municipio.sort_values(
    "ips_total",
    ascending=False
)

print(ips_municipio.to_string(index=False))

 divipola  ips_total
    27001        146
    27361         18
    27787         11
    27025          8
    27615          7
    27250          5
    27493          5
    27810          5
    27077          5
    27135          4
    27073          4
    27099          4
    27006          4
    27430          4
    27150          4
    27075          3
    27800          3
    27050          3
    27580          3
    27495          3
    27450          3
    27425          3
    27413          3
    27205          3
    27160          3
    27491          2
    27600          2
    27245          2
    27660          2
    27745          2
    27372          2

La definición metodológica:

ips_total: número de sedes de Instituciones Prestadoras de Servicios de Salud (IPS) registradas en el REPS para cada municipio del universo IOT, utilizando el código territorial de la sede (CodigoHabilitacionSede) y contando sedes únicas.

Fuente: REPS, corte 18 de agosto de 2026.

In [206]:
print("Columnas relacionadas con servicios:")
print([
    col for col in salud.columns
    if any(
        termino in col.lower()
        for termino in ["servicio", "urgencia", "emergencia", "hospital"]
    )
])

Columnas relacionadas con servicios:
[]

In [207]:
for i, col in enumerate(salud.columns):
    print(f"{i:02d} | {col}")

00 | CodigoPrestador
01 | NombrePrestador
02 | CodigoHabilitacionSede
03 | NombreSede
04 | TipoIdentificacion
05 | NumeroIdentificacion
06 | NaturalezaJuridica
07 | ESE
08 | MunicipioPrestador
09 | DepartamentoPrestadorDesc
10 | MunicipioPrestadorDesc
11 | DireccionPrestador
12 | EmailPrestador
13 | TelefonoPrestador
14 | MunicipioSede
15 | DepartamentoSedeDesc
16 | MunicipioSedeDesc
17 | DireccionSede
18 | EmailSede
19 | TelefonoSede
20 | ClasePrestadorDesc
21 | FechaCorte

In [208]:
df08_final = df08[[
    "divipola",
    "municipio",
    "policia_registros_fuente",
    "ips_total"
]].copy()

print(df08_final.shape)
print(df08_final.columns.tolist())

KeyError: "['ips_total'] not in index"