## Dataset 09 — ejecución reproducible

Este cuaderno ejecuta el proceso y comprueba que la salida conserva los 31 municipios IOT, una fila por DIVIPOLA y sin nulos introducidos. La fuente representa asignaciones/proyecciones SGP 2027; no ejecución.

In [1]:
from pathlib import Path
import runpy

root = next(path for path in [Path.cwd(), *Path.cwd().parents] if (path / 'scripts' / 'construir_dataset_09.py').exists())
runpy.run_path(str(root / 'scripts' / 'construir_dataset_09.py'), run_name='__main__')

{'__name__': '__main__',
 '__doc__': 'Construye el Dataset 09 del IOT Chocó a partir de fuentes exclusivamente RAW.\n\nLa fuente SGP disponible contiene proyecciones/asignaciones para 2027. No se\ninterpreta como ejecución ni se territorializa la fuente SECOP departamental.\n',
 '__package__': '',
 '__loader__': None,
 '__spec__': None,
 '__file__': 'C:\\Users\\USUARIO\\Desktop\\Colombia_en_datos\\scripts\\construir_dataset_09.py',
 '__cached__': None,
 '__builtins__': {'__name__': 'builtins',
  '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.",
  '__package__': '',
  '__loader__': _frozen_importlib.BuiltinImporter,
  '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
  '__build_class__': <function __build_class__>,
  '__import__': <function __import__(name, globals=None, locals=None, fromlist=(), level=0)>,
  'abs': <function abs(x, /)>,
  'all': <function all(iterable, /)>,
  'any': <function any(iterable, /)>,
  'ascii': <function ascii(obj, /)>,
  'bin': <function bin(number, /)>,
  'breakpoint': <function breakpoint>,
  'callable': <function callable(obj, /)>,
  'chr': <function chr(i, /)>,
  'compile': <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>,
  'delattr': <function delattr(obj, name, /)>,
  'dir': <function dir>,
  'divmod': <function divmod(x, y, /)>,
  'eval': <function eval(source, globals=None, locals=None, /)>,
  'exec': <function exec(source, globals=None, locals=None, /, *, closure=None)>,
  'format': <function format(value, format_spec='', /)>,
  'getattr': <function getattr>,
  'globals': <function globals()>,
  'hasattr': <function hasattr(obj, name, /)>,
  'hash': <function hash(obj, /)>,
  'hex': <function hex(number, /)>,
  'id': <function id(obj, /)>,
  'input': <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x000001F3841D2720>>,
  'isinstance': <function isinstance(obj, class_or_tuple, /)>,
  'issubclass': <function issubclass(cls, class_or_tuple, /)>,
  'iter': <function iter>,
  'aiter': <function aiter(async_iterable, /)>,
  'len': <function len(obj, /)>,
  'locals': <function locals()>,
  'max': <function max>,
  'min': <function min>,
  'next': <function next>,
  'anext': <function anext>,
  'oct': <function oct(number, /)>,
  'ord': <function ord(c, /)>,
  'pow': <function pow(base, exp, mod=None)>,
  'print': <function print(*args, sep=' ', end='\n', file=None, flush=False)>,
  'repr': <function repr(obj, /)>,
  'round': <function round(number, ndigits=None)>,
  'setattr': <function setattr(obj, name, value, /)>,
  'sorted': <function sorted(iterable, /, *, key=None, reverse=False)>,
  'sum': <function sum(iterable, /, start=0)>,
  'vars': <function vars>,
  'None': None,
  'Ellipsis': Ellipsis,
  'NotImplemented': NotImplemented,
  'False': False,
  'True': True,
  'bool': bool,
  'memoryview': memoryview,
  'bytearray': bytearray,
  'bytes': bytes,
  'classmethod': classmethod,
  'complex': complex,
  'dict': dict,
  'enumerate': enumerate,
  'filter': filter,
  'float': float,
  'frozenset': frozenset,
  'property': property,
  'int': int,
  'list': list,
  'map': map,
  'object': object,
  'range': range,
  'reversed': reversed,
  'set': set,
  'slice': slice,
  'staticmethod': staticmethod,
  'str': str,
  'super': super,
  'tuple': tuple,
  'type': type,
  'zip': zip,
  '__debug__': True,
  'BaseException': BaseException,
  'BaseExceptionGroup': BaseExceptionGroup,
  'Exception': Exception,
  'GeneratorExit': GeneratorExit,
  'KeyboardInterrupt': KeyboardInterrupt,
  'SystemExit': SystemExit,
  'ArithmeticError': ArithmeticError,
  'AssertionError': AssertionError,
  'AttributeError': AttributeError,
  'BufferError': BufferError,
  'EOFError': EOFError,
  'ImportError': ImportError,
  'LookupError': LookupError,
  'MemoryError': MemoryError,
  'NameError': NameError,
  'OSError': OSError,
  'ReferenceError': ReferenceError,
  'RuntimeError': RuntimeError,
  'StopAsyncIteration': StopAsyncIteration,
  'StopIteration': StopIteration,
  'SyntaxError': SyntaxError,
  'SystemError': SystemError,
  'TypeError': TypeError,
  'ValueError': ValueError,
  'Warning': Warning,
  'FloatingPointError': FloatingPointError,
  'OverflowError': OverflowError,
  'ZeroDivisionError': ZeroDivisionError,
  'BytesWarning': BytesWarning,
  'DeprecationWarning': DeprecationWarning,
  'EncodingWarning': EncodingWarning,
  'FutureWarning': FutureWarning,
  'ImportWarning': ImportWarning,
  'PendingDeprecationWarning': PendingDeprecationWarning,
  'ResourceWarning': ResourceWarning,
  'RuntimeWarning': RuntimeWarning,
  'SyntaxWarning': SyntaxWarning,
  'UnicodeWarning': UnicodeWarning,
  'UserWarning': UserWarning,
  'BlockingIOError': BlockingIOError,
  'ChildProcessError': ChildProcessError,
  'ConnectionError': ConnectionError,
  'FileExistsError': FileExistsError,
  'FileNotFoundError': FileNotFoundError,
  'InterruptedError': InterruptedError,
  'IsADirectoryError': IsADirectoryError,
  'NotADirectoryError': NotADirectoryError,
  'PermissionError': PermissionError,
  'ProcessLookupError': ProcessLookupError,
  'TimeoutError': TimeoutError,
  'IndentationError': IndentationError,
  'IndexError': IndexError,
  'KeyError': KeyError,
  'ModuleNotFoundError': ModuleNotFoundError,
  'NotImplementedError': NotImplementedError,
  'RecursionError': RecursionError,
  'UnboundLocalError': UnboundLocalError,
  'UnicodeError': UnicodeError,
  'BrokenPipeError': BrokenPipeError,
  'ConnectionAbortedError': ConnectionAbortedError,
  'ConnectionRefusedError': ConnectionRefusedError,
  'ConnectionResetError': ConnectionResetError,
  'TabError': TabError,
  'UnicodeDecodeError': UnicodeDecodeError,
  'UnicodeEncodeError': UnicodeEncodeError,
  'UnicodeTranslateError': UnicodeTranslateError,
  'ExceptionGroup': ExceptionGroup,
  'EnvironmentError': OSError,
  'IOError': OSError,
  'WindowsError': OSError,
  'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
  'copyright': Copyright (c) 2001-2023 Python Software Foundation.
  All Rights Reserved.

  Copyright (c) 2000 BeOpen.com.
  All Rights Reserved.

  Copyright (c) 1995-2001 Corporation for National Research Initiatives.
  All Rights Reserved.

  Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
  All Rights Reserved.,
  'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
      for supporting Python development.  See www.python.org for more information.,
  'license': See https://www.python.org/psf/license/,
  'help': Type help() for interactive help, or help(object) for help about object.,
  'execfile': <function _pydev_bundle._pydev_execfile.execfile(file, glob=None, loc=None)>,
  'runfile': <function _pydev_bundle.pydev_umd.runfile(filename, args=None, wdir=None, namespace=None)>,
  '__IPYTHON__': True,
  'display': <function IPython.core.display_functions.display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)>,
  'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x000001F3841D0350>>},
 'annotations': _Feature((3, 7, 0, 'beta', 1), None, 16777216),
 'logging': <module 'logging' from 'C:\\Users\\USUARIO\\anaconda3\\Lib\\logging\\__init__.py'>,
 're': <module 're' from 'C:\\Users\\USUARIO\\anaconda3\\Lib\\re\\__init__.py'>,
 'sys': <module 'sys' (built-in)>,
 'date': datetime.date,
 'Path': pathlib.Path,
 'pd': <module 'pandas' from 'C:\\Users\\USUARIO\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>,
 'ROOT': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos'),
 'EPISODE': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó'),
 'DATA': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó/Data'),
 'RAW': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó/Data/raw'),
 'PROCESSED': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó/Data/processed'),
 'LOG_DIR': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó/logs'),
 'SOURCE_09': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó/Data/raw/dataset_09_inversion_publica_infraestructura_choco_v1.xlsx'),
 'UNIVERSE': WindowsPath('C:/Users/USUARIO/Desktop/Colombia_en_datos/episodios/002_EL_chocó/Data/raw/dataset_01_poblacion_territorio_choco_definitivo.csv'),
 'PROCESS_DATE': '2026-08-18',
 'setup_logger': <function __main__.setup_logger() -> 'logging.Logger'>,
 'clean_divipola': <function __main__.clean_divipola(series: 'pd.Series') -> 'pd.Series'>,
 'snake': <function __main__.snake(text: 'str') -> 'str'>,
 'main': <function __main__.main() -> 'None'>}

In [2]:
import pandas as pd

episode = next((root / 'episodios').glob('002_EL_*'))
output = episode / 'Data' / 'processed' / 'dataset_09_inversion_publica_infraestructura.csv'
df = pd.read_csv(output, dtype={'divipola': 'string'})
assert df.shape[0] == 31
assert df['divipola'].nunique() == 31
assert not df['divipola'].duplicated().any()
assert df['municipio_fuente'].notna().all()
assert (df.filter(regex='^sgp_').select_dtypes(include='number') >= 0).all().all()
df[['divipola', 'municipio', 'sgp_total_asignado_2027']].head()

  divipola   municipio  sgp_total_asignado_2027
0    27001      Quibdó             337773811203
1    27006      Acandí              21919018789
2    27025  Alto Baudó              38146547567
3    27050      Atrato              14948959123
4    27073      Bagadó              29875980543

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from pathlib import Path

PROCESSED = Path(
    r"C:\Users\USUARIO\Desktop\Colombia_en_datos"
    r"\episodios\002_EL_chocó\Data\processed"
)

ruta_09 = PROCESSED / "dataset_09_inversion_publica_infraestructura.csv"

df09 = pd.read_csv(ruta_09)

print("Shape:", df09.shape)
print("\nColumnas:")
for i, col in enumerate(df09.columns):
    print(f"{i:02d} | {col}")

Shape: (31, 25)

Columnas:
00 | divipola
01 | municipio
02 | municipio_homologado
03 | municipio_fuente
04 | departamento
05 | anio
06 | poblacion_proyectada_2027
07 | alerta_sgp_2027
08 | sgp_2027_poblacion_atendida
09 | sgp_2027_calidad_gratuidad
10 | sgp_2027_calidad_matricula
11 | sgp_2027_regimen_subsidiado
12 | sgp_2027_salud_publica
13 | sgp_2027_subsidio_a_la_oferta
14 | sgp_2027_agua_potable
15 | sgp_2027_poblacion_menor_que_25mil
16 | sgp_2027_pobreza_menor_que_25_mil
17 | sgp_2027_poblacion_general
18 | sgp_2027_pobreza_general
19 | sgp_2027_riberenos
20 | sgp_2027_alimentacion_escolar
21 | sgp_total_asignado_2027
22 | unidad_monetaria
23 | magnitud
24 | fuente_principal

In [2]:
df09.head()

,divipola,municipio,municipio_homologado,municipio_fuente,departamento,anio,poblacion_proyectada_2027,alerta_sgp_2027,sgp_2027_poblacion_atendida,sgp_2027_calidad_gratuidad,...,sgp_2027_poblacion_menor_que_25mil,sgp_2027_pobreza_menor_que_25_mil,sgp_2027_poblacion_general,sgp_2027_pobreza_general,sgp_2027_riberenos,sgp_2027_alimentacion_escolar,sgp_total_asignado_2027,unidad_monetaria,magnitud,fuente_principal
0,27001,Quibdó,Quibdó,Quibdó,Chocó,2027,144859,0,206512707226,6641890818,...,0,0,8480110382,9405588619,0,6065556952,337773811203,pesos corrientes colombianos,asignacion/proyeccion SGP; no ejecucion,"DNP/SGP, hoja SGP_2027_SGP"
1,27006,Acandí,Acandí,Acandí,Chocó,2027,16651,0,0,678537570,...,1317382524,2154207754,973545449,4707943491,0,339119815,21919018789,pesos corrientes colombianos,asignacion/proyeccion SGP; no ejecucion,"DNP/SGP, hoja SGP_2027_SGP"
2,27025,Alto Baudó,Alto Baudó,Alto Baudó,Chocó,2027,29550,0,0,2781375896,...,0,0,1736939976,10056566819,0,1876406885,38146547567,pesos corrientes colombianos,asignacion/proyeccion SGP; no ejecucion,"DNP/SGP, hoja SGP_2027_SGP"
3,27050,Atrato,Atrato,Atrato,Chocó,2027,6567,0,0,312703672,...,522950024,2512176227,386459974,5490270700,0,161688944,14948959123,pesos corrientes colombianos,asignacion/proyeccion SGP; no ejecucion,"DNP/SGP, hoja SGP_2027_SGP"
4,27073,Bagadó,Bagadó,Bagadó,Chocó,2027,13170,0,0,1499556674,...,1035652406,4168363643,765346942,9109808671,0,1055975030,29875980543,pesos corrientes colombianos,asignacion/proyeccion SGP; no ejecucion,"DNP/SGP, hoja SGP_2027_SGP"

In [3]:
df09.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 25 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   divipola                            31 non-null     int64
 1   municipio                           31 non-null     object
 2   municipio_homologado                31 non-null     object
 3   municipio_fuente                    31 non-null     object
 4   departamento                        31 non-null     object
 5   anio                                31 non-null     int64
 6   poblacion_proyectada_2027           31 non-null     int64
 7   alerta_sgp_2027                     31 non-null     int64
 8   sgp_2027_poblacion_atendida         31 non-null     int64
 9   sgp_2027_calidad_gratuidad          31 non-null     int64
 10  sgp_2027_calidad_matricula          31 non-null     int64
 11  sgp_2027_regimen_subsidiado         31 non-null     int64
 12  sgp_2027_salud_publica              31 non-null     int64
 13  sgp_2027_subsidio_a_la_oferta       31 non-null     int64
 14  sgp_2027_agua_potable               31 non-null     int64
 15  sgp_2027_poblacion_menor_que_25mil  31 non-null     int64
 16  sgp_2027_pobreza_menor_que_25_mil   31 non-null     int64
 17  sgp_2027_poblacion_general          31 non-null     int64
 18  sgp_2027_pobreza_general            31 non-null     int64
 19  sgp_2027_riberenos                  31 non-null     int64
 20  sgp_2027_alimentacion_escolar       31 non-null     int64
 21  sgp_total_asignado_2027             31 non-null     int64
 22  unidad_monetaria                    31 non-null     object
 23  magnitud                            31 non-null     object
 24  fuente_principal                    31 non-null     object
dtypes: int64(18), object(7)
memory usage: 6.2+ KB

auditoría cuantitativa

In [4]:
# Variables monetarias
variables_sgp = [
    col for col in df09.columns
    if col.startswith("sgp_2027_")
]

print("Variables SGP:")
for col in variables_sgp:
    print(col)

print("\nCantidad:", len(variables_sgp))

Variables SGP:
sgp_2027_poblacion_atendida
sgp_2027_calidad_gratuidad
sgp_2027_calidad_matricula
sgp_2027_regimen_subsidiado
sgp_2027_salud_publica
sgp_2027_subsidio_a_la_oferta
sgp_2027_agua_potable
sgp_2027_poblacion_menor_que_25mil
sgp_2027_pobreza_menor_que_25_mil
sgp_2027_poblacion_general
sgp_2027_pobreza_general
sgp_2027_riberenos
sgp_2027_alimentacion_escolar

Cantidad: 13

In [5]:
# Estadísticos descriptivos de las variables monetarias
df09[variables_sgp].describe().T

,count,mean,std,min,25%,50%,75%,max
sgp_2027_poblacion_atendida,31.0,6.661700e+09,3.709078e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.065127e+11
sgp_2027_calidad_gratuidad,31.0,1.131882e+09,1.197672e+09,2.430660e+08,4.436912e+08,7.300519e+08,1.419063e+09,6.641891e+09
sgp_2027_calidad_matricula,31.0,1.314764e+09,1.772471e+09,1.597647e+08,4.418393e+08,7.156761e+08,1.593570e+09,9.834056e+09
sgp_2027_regimen_subsidiado,31.0,8.133889e+09,1.195986e+10,2.163501e+09,3.262256e+09,5.847601e+09,7.334844e+09,6.941254e+10
sgp_2027_salud_publica,31.0,8.394120e+08,5.554238e+08,4.289781e+08,5.531212e+08,7.041929e+08,9.302296e+08,3.475822e+09
sgp_2027_subsidio_a_la_oferta,31.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sgp_2027_agua_potable,31.0,3.698493e+09,3.008997e+09,1.261104e+09,2.205058e+09,3.034627e+09,4.024446e+09,1.794554e+10
sgp_2027_poblacion_menor_que_25mil,31.0,6.882010e+08,5.103011e+08,0.000000e+00,3.408142e+08,7.014031e+08,1.004789e+09,1.735134e+09
sgp_2027_pobreza_menor_que_25_mil,31.0,2.409463e+09,1.500039e+09,0.000000e+00,1.598087e+09,2.902052e+09,3.382488e+09,4.529156e+09
sgp_2027_poblacion_general,31.0,1.144096e+09,1.469913e+09,1.998564e+08,5.099355e+08,7.384273e+08,1.217568e+09,8.480110e+09
sgp_2027_pobreza_general,31.0,7.457254e+09,2.068801e+09,3.178947e+09,6.309546e+09,7.248298e+09,8.899391e+09,1.195538e+10
sgp_2027_riberenos,31.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
sgp_2027_alimentacion_escolar,31.0,7.830452e+08,1.103142e+09,8.732250e+07,2.143094e+08,3.992297e+08,9.549106e+08,6.065557e+09

In [8]:
resumen_sgp = df09[
    [
        "municipio",
        "poblacion_proyectada_2027",
        "sgp_total_asignado_2027"
    ]
].copy()

resumen_sgp["sgp_per_capita_2027"] = (
    resumen_sgp["sgp_total_asignado_2027"]
    / resumen_sgp["poblacion_proyectada_2027"]
)

resumen_sgp.sort_values(
    "sgp_total_asignado_2027",
    ascending=False
)

,municipio,poblacion_proyectada_2027,sgp_total_asignado_2027,sgp_per_capita_2027
0,Quibdó,144859,337773811203,2.331742e+06
14,Istmina,37434,45599647845,1.218135e+06
25,Riosucio,30460,42700002819,1.401839e+06
2,Alto Baudó,29550,38146547567,1.290915e+06
9,Carmen del Darién,21842,32431055807,1.484802e+06
28,Tadó,19632,31905009482,1.625153e+06
6,Bajo Baudó,35411,31421393463,8.873343e+05
7,Bojayá,13393,30854519232,2.303780e+06
4,Bagadó,13170,29875980543,2.268488e+06
16,Lloró,10572,29746952635,2.813749e+06
18,Medio Baudó,17926,28459288656,1.587598e+06
11,Condoto,12585,26671783046,2.119331e+06
13,El Litoral del San Juan,28293,25940677135,9.168585e+05
19,Medio San Juan,11374,24188999179,2.126692e+06
21,Nuevo Belén de Bajirá,30832,22962809049,7.447720e+05
22,Nuquí,19139,22429848012,1.171945e+06
29,Unguía,12334,22278575817,1.806273e+06
1,Acandí,16651,21919018789,1.316379e+06
24,Río Quito,8478,21504721333,2.536532e+06
17,Medio Atrato,11408,20213678900,1.771886e+06
15,Juradó,9009,18865033334,2.094021e+06
20,Nóvita,10100,18429433876,1.824696e+06
30,Unión Panamericana,7370,18025390072,2.445779e+06
12,El Carmen de Atrato,8832,16313853958,1.847130e+06
10,Cértegui,6125,16286500890,2.659021e+06
5,Bahía Solano,11026,15953874547,1.446932e+06
8,El Cantón del San Pablo,6628,15642661131,2.360088e+06
3,Atrato,6567,14948959123,2.276376e+06
27,Sipí,3400,14828924312,4.361448e+06
23,Río Iró,5902,14806860797,2.508787e+06
26,San José del Palmar,5143,11002366582,2.139290e+06

In [9]:
resumen_sgp.sort_values(
    "sgp_per_capita_2027",
    ascending=False
)

,municipio,poblacion_proyectada_2027,sgp_total_asignado_2027,sgp_per_capita_2027
27,Sipí,3400,14828924312,4.361448e+06
16,Lloró,10572,29746952635,2.813749e+06
10,Cértegui,6125,16286500890,2.659021e+06
24,Río Quito,8478,21504721333,2.536532e+06
23,Río Iró,5902,14806860797,2.508787e+06
30,Unión Panamericana,7370,18025390072,2.445779e+06
8,El Cantón del San Pablo,6628,15642661131,2.360088e+06
0,Quibdó,144859,337773811203,2.331742e+06
7,Bojayá,13393,30854519232,2.303780e+06
3,Atrato,6567,14948959123,2.276376e+06
4,Bagadó,13170,29875980543,2.268488e+06
26,San José del Palmar,5143,11002366582,2.139290e+06
19,Medio San Juan,11374,24188999179,2.126692e+06
11,Condoto,12585,26671783046,2.119331e+06
15,Juradó,9009,18865033334,2.094021e+06
12,El Carmen de Atrato,8832,16313853958,1.847130e+06
20,Nóvita,10100,18429433876,1.824696e+06
29,Unguía,12334,22278575817,1.806273e+06
17,Medio Atrato,11408,20213678900,1.771886e+06
28,Tadó,19632,31905009482,1.625153e+06
18,Medio Baudó,17926,28459288656,1.587598e+06
9,Carmen del Darién,21842,32431055807,1.484802e+06
5,Bahía Solano,11026,15953874547,1.446932e+06
25,Riosucio,30460,42700002819,1.401839e+06
1,Acandí,16651,21919018789,1.316379e+06
2,Alto Baudó,29550,38146547567,1.290915e+06
14,Istmina,37434,45599647845,1.218135e+06
22,Nuquí,19139,22429848012,1.171945e+06
13,El Litoral del San Juan,28293,25940677135,9.168585e+05
6,Bajo Baudó,35411,31421393463,8.873343e+05
21,Nuevo Belén de Bajirá,30832,22962809049,7.447720e+05

In [10]:
componentes_sgp = [
    col for col in df09.columns
    if col.startswith("sgp_2027_")
    and col != "sgp_total_asignado_2027"
]

df09["sgp_suma_componentes"] = df09[componentes_sgp].sum(axis=1)

df09["diferencia_sgp"] = (
    df09["sgp_total_asignado_2027"]
    - df09["sgp_suma_componentes"]
)

df09[
    [
        "municipio",
        "sgp_total_asignado_2027",
        "sgp_suma_componentes",
        "diferencia_sgp"
    ]
].sort_values("diferencia_sgp", key=abs, ascending=False)

,municipio,sgp_total_asignado_2027,sgp_suma_componentes,diferencia_sgp
0,Quibdó,337773811203,337773811203,0
16,Lloró,29746952635,29746952635,0
29,Unguía,22278575817,22278575817,0
28,Tadó,31905009482,31905009482,0
27,Sipí,14828924312,14828924312,0
26,San José del Palmar,11002366582,11002366582,0
25,Riosucio,42700002819,42700002819,0
24,Río Quito,21504721333,21504721333,0
23,Río Iró,14806860797,14806860797,0
22,Nuquí,22429848012,22429848012,0
21,Nuevo Belén de Bajirá,22962809049,22962809049,0
20,Nóvita,18429433876,18429433876,0
19,Medio San Juan,24188999179,24188999179,0
18,Medio Baudó,28459288656,28459288656,0
17,Medio Atrato,20213678900,20213678900,0
15,Juradó,18865033334,18865033334,0
1,Acandí,21919018789,21919018789,0
14,Istmina,45599647845,45599647845,0
13,El Litoral del San Juan,25940677135,25940677135,0
12,El Carmen de Atrato,16313853958,16313853958,0
11,Condoto,26671783046,26671783046,0
10,Cértegui,16286500890,16286500890,0
9,Carmen del Darién,32431055807,32431055807,0
8,El Cantón del San Pablo,15642661131,15642661131,0
7,Bojayá,30854519232,30854519232,0
6,Bajo Baudó,31421393463,31421393463,0
5,Bahía Solano,15953874547,15953874547,0
4,Bagadó,29875980543,29875980543,0
3,Atrato,14948959123,14948959123,0
2,Alto Baudó,38146547567,38146547567,0
30,Unión Panamericana,18025390072,18025390072,0

In [11]:
componentes_sgp = [
    col for col in df09.columns
    if col.startswith("sgp_2027_")
    and col != "sgp_total_asignado_2027"
]

participacion_componentes = pd.DataFrame({
    "componente": componentes_sgp,
    "total_departamental": [
        df09[col].sum() for col in componentes_sgp
    ]
})

participacion_componentes["participacion_pct"] = (
    participacion_componentes["total_departamental"]
    / df09["sgp_total_asignado_2027"].sum()
    * 100
)

participacion_componentes.sort_values(
    "total_departamental",
    ascending=False
)

                            componente  total_departamental  participacion_pct
3          sgp_2027_regimen_subsidiado         252150554469          23.740125
10            sgp_2027_pobreza_general         231174872953          21.765252
0          sgp_2027_poblacion_atendida         206512707226          19.443294
6                sgp_2027_agua_potable         114653276029          10.794674
8    sgp_2027_pobreza_menor_que_25_mil          74693346747           7.032423
2           sgp_2027_calidad_matricula          40757694736           3.837361
9           sgp_2027_poblacion_general          35466991395           3.339238
1           sgp_2027_calidad_gratuidad          35088332379           3.303587
4               sgp_2027_salud_publica          26021770975           2.449965
12       sgp_2027_alimentacion_escolar          24274400823           2.285449
7   sgp_2027_poblacion_menor_que_25mil          21334231402           2.008631
5        sgp_2027_subsidio_a_la_oferta                    0           0.000000
11                  sgp_2027_riberenos                    0           0.000000

In [12]:
print(
    "SGP total Chocó 2027:",
    f"${df09['sgp_total_asignado_2027'].sum():,.0f}"
)

participacion_componentes

SGP total Chocó 2027: $1,062,128,179,134

                            componente  total_departamental  participacion_pct
0          sgp_2027_poblacion_atendida         206512707226          19.443294
1           sgp_2027_calidad_gratuidad          35088332379           3.303587
2           sgp_2027_calidad_matricula          40757694736           3.837361
3          sgp_2027_regimen_subsidiado         252150554469          23.740125
4               sgp_2027_salud_publica          26021770975           2.449965
5        sgp_2027_subsidio_a_la_oferta                    0           0.000000
6                sgp_2027_agua_potable         114653276029          10.794674
7   sgp_2027_poblacion_menor_que_25mil          21334231402           2.008631
8    sgp_2027_pobreza_menor_que_25_mil          74693346747           7.032423
9           sgp_2027_poblacion_general          35466991395           3.339238
10            sgp_2027_pobreza_general         231174872953          21.765252
11                  sgp_2027_riberenos                    0           0.000000
12       sgp_2027_alimentacion_escolar          24274400823           2.285449

distribución y concentración

In [14]:
eda_sgp = df09[
    [
        "municipio",
        "poblacion_proyectada_2027",
        "sgp_total_asignado_2027"
    ]
].copy()

eda_sgp["sgp_per_capita_2027"] = (
    eda_sgp["sgp_total_asignado_2027"]
    / eda_sgp["poblacion_proyectada_2027"]
)

eda_sgp["participacion_poblacion_pct"] = (
    eda_sgp["poblacion_proyectada_2027"]
    / eda_sgp["poblacion_proyectada_2027"].sum()
    * 100
)

eda_sgp["participacion_sgp_pct"] = (
    eda_sgp["sgp_total_asignado_2027"]
    / eda_sgp["sgp_total_asignado_2027"].sum()
    * 100
)

eda_sgp["ratio_sgp_poblacion"] = (
    eda_sgp["participacion_sgp_pct"]
    / eda_sgp["participacion_poblacion_pct"]
)

eda_sgp.sort_values(
    "ratio_sgp_poblacion",
    ascending=False
)

,municipio,poblacion_proyectada_2027,sgp_total_asignado_2027,sgp_per_capita_2027,participacion_poblacion_pct,participacion_sgp_pct,ratio_sgp_poblacion
27,Sipí,3400,14828924312,4.361448e+06,0.561570,1.396152,2.486157
16,Lloró,10572,29746952635,2.813749e+06,1.746154,2.800693,1.603921
10,Cértegui,6125,16286500890,2.659021e+06,1.011653,1.533384,1.515722
24,Río Quito,8478,21504721333,2.536532e+06,1.400292,2.024682,1.445900
23,Río Iró,5902,14806860797,2.508787e+06,0.974820,1.394075,1.430084
30,Unión Panamericana,7370,18025390072,2.445779e+06,1.217286,1.697101,1.394167
8,El Cantón del San Pablo,6628,15642661131,2.360088e+06,1.094732,1.472766,1.345321
0,Quibdó,144859,337773811203,2.331742e+06,23.926038,31.801605,1.329163
7,Bojayá,13393,30854519232,2.303780e+06,2.212092,2.904971,1.313224
3,Atrato,6567,14948959123,2.276376e+06,1.084657,1.407453,1.297603
4,Bagadó,13170,29875980543,2.268488e+06,2.175260,2.812841,1.293106
26,San José del Palmar,5143,11002366582,2.139290e+06,0.849458,1.035879,1.219459
19,Medio San Juan,11374,24188999179,2.126692e+06,1.878618,2.277409,1.212279
11,Condoto,12585,26671783046,2.119331e+06,2.078636,2.511164,1.208083
15,Juradó,9009,18865033334,2.094021e+06,1.487996,1.776154,1.193655
12,El Carmen de Atrato,8832,16313853958,1.847130e+06,1.458762,1.535959,1.052920
20,Nóvita,10100,18429433876,1.824696e+06,1.668194,1.735142,1.040132
29,Unguía,12334,22278575817,1.806273e+06,2.037179,2.097541,1.029630
17,Medio Atrato,11408,20213678900,1.771886e+06,1.884234,1.903130,1.010028
28,Tadó,19632,31905009482,1.625153e+06,3.242574,3.003876,0.926386
18,Medio Baudó,17926,28459288656,1.587598e+06,2.960797,2.679459,0.904979
9,Carmen del Darién,21842,32431055807,1.484802e+06,3.607594,3.053403,0.846382
5,Bahía Solano,11026,15953874547,1.446932e+06,1.821140,1.502067,0.824795
25,Riosucio,30460,42700002819,1.401839e+06,5.031010,4.020231,0.799090
1,Acandí,16651,21919018789,1.316379e+06,2.750209,2.063689,0.750375
2,Alto Baudó,29550,38146547567,1.290915e+06,4.880708,3.591520,0.735861
14,Istmina,37434,45599647845,1.218135e+06,6.182890,4.293234,0.694373
22,Nuquí,19139,22429848012,1.171945e+06,3.161146,2.111784,0.668044
13,El Litoral del San Juan,28293,25940677135,9.168585e+05,4.673092,2.442330,0.522637
6,Bajo Baudó,35411,31421393463,8.873343e+05,5.848756,2.958343,0.505807
21,Nuevo Belén de Bajirá,30832,22962809049,7.447720e+05,5.092453,2.161962,0.424542

Dataset 09 — estado definitivo
31 municipios
31 DIVIPOLA únicas
0 duplicados
0 nulos
25 variables
13 componentes SGP
sgp_total_asignado_2027 consistente con la suma de sus componentes.
DIVIPOLA homologado correctamente contra el universo IOT.
Se excluyó el agregado departamental 27000.
Se conservaron municipio, municipio_homologado y municipio_fuente.
Los valores monetarios se conservaron en pesos corrientes.
No se imputaron valores ni se transformaron ausencias en ceros.
SECOP fue revisado pero no incorporado porque no permitía una territorialización confiable.
No se incorporaron PIIP/SGR porque no estaban disponibles en RAW.
Semántica provisional: asignaciones/proyecciones SGP 2027; no ejecución de inversión.

Y dejamos para la fase de análisis cosas como:

SGP per cápita.
Diferencias entre peso poblacional y peso presupuestal.
Composición del SGP.
Relación con pobreza, población, salud, educación, capacidad institucional, etc.
Identificación de patrones territoriales.

# Exploración y auditoría inicial de fuentes
## Índice de Oportunidades Territoriales (IOT) — Chocó

---

## 1. Objetivo de la exploración

Esta etapa tiene como objetivo realizar la exploración, identificación, limpieza inicial y evaluación de disponibilidad de las fuentes utilizadas para construir el Índice de Oportunidades Territoriales (IOT) del departamento del Chocó.

La exploración inicial no busca establecer relaciones causales, construir el índice ni interpretar los resultados territoriales. Su propósito es determinar qué información contienen las fuentes, cuál es su unidad de observación, qué tan bien pueden ser homologadas al universo municipal del IOT y cuáles pueden convertirse posteriormente en variables comparables.

El universo territorial de referencia está compuesto por **31 municipios del departamento del Chocó**.

Esta etapa constituye la frontera entre la exploración de las fuentes y la fase posterior de análisis metodológico del IOT.

---

## 2. Universo territorial

El universo territorial utilizado durante toda la construcción del proyecto corresponde al universo municipal definido para el IOT.

**Características del universo:**

- Departamento: Chocó
- Municipios: 31
- DIVIPOLA únicas: 31
- Unidad territorial objetivo: municipio

La DIVIPOLA constituye el identificador territorial preferente para integrar las diferentes fuentes.

Los nombres municipales homologados al universo IOT se utilizan como referencia descriptiva, mientras que los nombres originales de las fuentes se conservan cuando resulta relevante para garantizar trazabilidad.

---

## 3. Inventario general de las fuentes

Durante la exploración inicial se trabajó con diez datasets correspondientes a diferentes dimensiones de información territorial.

Los datasets fueron explorados individualmente antes de ser considerados para la construcción del IOT.

La clasificación general de cada fuente debe considerar:

- tema
- fuente original
- unidad de observación
- nivel territorial
- cobertura municipal
- temporalidad
- naturaleza de la información
- disponibilidad de DIVIPOLA
- necesidad de homologación
- posibilidad de agregación
- existencia de valores faltantes
- limitaciones metodológicas
- posibilidad de construir variables comparables

El inventario consolidado de los diez datasets se documenta a partir de los archivos de metodología, auditoría y cobertura generados durante la construcción de cada dataset.

---

## 4. Unidad de observación

Una de las primeras decisiones de la exploración fue identificar qué representa una fila en cada fuente.

La unidad de observación no se asumió automáticamente como municipal.

Dependiendo de la fuente, una fila puede representar:

- un municipio
- un municipio-año
- una institución
- una sede
- un evento
- un contrato
- un registro administrativo
- un documento
- un caso
- u otra unidad específica de la fuente.

Esta distinción es fundamental porque una fuente con múltiples registros por municipio no puede agregarse automáticamente sin comprender primero qué representa cada registro.

Por esta razón, antes de construir variables municipales se evaluó la unidad de observación de cada fuente.

---

## 5. Homologación territorial

La homologación territorial constituye una regla transversal del proyecto.

La prioridad utilizada es:

1. DIVIPOLA
2. código municipal oficial
3. combinación de departamento y municipio
4. nombre municipal
5. otros identificadores territoriales explícitos de la fuente

Cuando una fuente contiene DIVIPOLA, esta se utiliza como identificador principal.

Cuando no existe DIVIPOLA, se realiza homologación mediante nombres municipales u otros identificadores disponibles, conservando el valor original de la fuente.

Cuando resulta necesario normalizar texto para realizar la homologación, se pueden considerar diferencias como:

- mayúsculas y minúsculas
- tildes
- espacios
- abreviaciones
- nombres con paréntesis
- nombres de cabeceras municipales
- variaciones ortográficas

Sin embargo, la normalización utilizada para comparar nombres no debe alterar el valor original de la fuente.

No se considera que una mención territorial sea equivalente automáticamente a una observación municipal.

Asimismo, no se utilizan coincidencias difusas cuando puedan generar falsos positivos.

Toda homologación territorial relevante debe poder ser rastreada hasta el valor original de la fuente.

---

## 6. Cobertura territorial

Para cada dataset se evaluó, cuando fue posible:

- número de municipios del universo IOT
- municipios encontrados en la fuente
- municipios homologados
- municipios sin registro
- registros fuera del universo
- registros ambiguos
- registros supramunicipales
- registros departamentales
- registros que no pueden asignarse de forma confiable a un municipio

La ausencia de un registro no se interpreta automáticamente como ausencia del fenómeno.

Debe distinguirse entre:

**cero observado**

y

**ausencia de información o registro**.

Esta distinción es especialmente importante para las fuentes administrativas.

---

## 7. Tratamiento de datos faltantes

Durante la exploración se adoptaron las siguientes reglas generales.

### No se realizó:

- imputación automática de valores
- conversión de `NA` a `0`
- eliminación silenciosa de registros
- sustitución arbitraria de valores
- eliminación automática de valores extremos
- inferencia de ausencia a partir de ausencia de registro

### Sí se realizó:

- identificación explícita de valores faltantes
- distinción entre cero observado y ausencia de registro
- documentación de nulos estructurales
- conservación de valores faltantes cuando la fuente no permite completarlos
- registro de limitaciones de cobertura

Los valores faltantes deben interpretarse de acuerdo con la naturaleza de cada fuente.

---

## 8. Tipología general de las fuentes

A partir de la exploración, las fuentes pueden clasificarse conceptualmente en diferentes grupos.

### A. Fuentes cuantitativas municipales

Fuentes que permiten construir variables directamente comparables entre los municipios del universo IOT.

### B. Fuentes administrativas

Fuentes construidas a partir de registros institucionales, eventos, establecimientos, contratos u otras unidades administrativas que pueden requerir agregación o interpretación antes de convertirse en variables municipales.

### C. Fuentes con limitaciones territoriales

Fuentes que contienen información relevante pero que no permiten construir directamente una variable municipal completa debido a cobertura, unidad de observación o estructura territorial.

### D. Fuentes cualitativas

Fuentes documentales, históricas o de casos que pueden aportar contexto y evidencia cualitativa, pero que no deben convertirse automáticamente en indicadores cuantitativos comparables.

El Dataset 10 corresponde principalmente a esta última categoría.

---

## 9. Reglas de transformación

Las transformaciones realizadas durante la construcción de los datasets deben ser reproducibles y estar documentadas.

Cuando una variable original fue transformada, debe poder identificarse:

- columna original
- transformación aplicada
- columna resultante
- razón de la transformación

No se construyeron indicadores derivados únicamente porque fueran matemáticamente posibles.

Una transformación que implique una decisión analítica debe quedar para revisión metodológica posterior.

---

## 10. Variables categóricas

Las variables categóricas se conservaron en su forma original siempre que fue posible.

No se transformaron automáticamente categorías en valores numéricos.

Por ejemplo, no se asumió que:

- alto = 3
- medio = 2
- bajo = 1

a menos que la propia fuente definiera explícitamente esa escala o existiera una justificación metodológica documentada.

Las variables que pueden parecer ordinales pero cuya estructura no está suficientemente documentada se mantienen como categóricas y quedan sujetas a revisión posterior.

---

## 11. Variables numéricas

Las variables numéricas fueron revisadas considerando:

- tipo de dato
- unidad de medida
- escala
- valores nulos
- valores extremos
- valores imposibles
- duplicados
- consistencia matemática cuando correspondía

Los valores extremos no fueron eliminados únicamente por su magnitud.

Los valores cero explícitos de la fuente se conservaron como cero.

Los valores faltantes no fueron convertidos automáticamente en cero.

---

## 12. Agregación

No se realizó ninguna agregación sin identificar previamente la unidad de observación.

Cuando una fuente contiene múltiples registros asociados a un municipio, primero debe determinarse qué representan esos registros.

Una fuente puede tener estructuras como:

- municipio × categoría
- municipio × año
- municipio × institución
- municipio × evento
- municipio × registro

La agregación solamente se realiza cuando existe una justificación metodológica y la operación conserva el significado de la fuente.

---

## 13. Trazabilidad

Una prioridad transversal del proyecto fue conservar la trazabilidad.

Cuando resulta pertinente, los datasets finales mantienen:

- DIVIPOLA
- municipio homologado
- municipio de la fuente
- fuente original
- unidad de medida
- año
- metadatos
- observaciones metodológicas

Esto permite reconstruir posteriormente cómo se pasó de la fuente RAW a la variable procesada.

---

## 14. Decisiones metodológicas transversales

### Regla 1 — Universo territorial

El universo territorial del IOT es fijo y está compuesto por 31 municipios del Chocó.

### Regla 2 — DIVIPOLA

La DIVIPOLA es el identificador territorial preferente cuando está disponible.

### Regla 3 — Nombre original

Cuando una fuente proporciona un nombre municipal diferente al nombre homologado, se conserva el nombre original para garantizar trazabilidad.

### Regla 4 — Homologación

La homologación territorial no debe modificar el valor original de la fuente.

### Regla 5 — Ceros y faltantes

Un cero observado no es equivalente a un valor faltante.

### Regla 6 — Agregación

No se agregan registros sin comprender primero la unidad de observación.

### Regla 7 — Construcción de indicadores

La posibilidad matemática de calcular una variable no implica que dicha variable sea metodológicamente válida para el IOT.

### Regla 8 — Fuentes externas

Si una variable requiere información que no se encuentra disponible en RAW, la ausencia debe documentarse antes de incorporarla.

### Regla 9 — No invención

No se deben inventar, imputar o inferir silenciosamente datos que no estén respaldados por la fuente.

---

## 15. Consideraciones específicas del Dataset 08

El Dataset 08 corresponde a capacidad institucional y fue construido a nivel municipal para los 31 municipios del universo IOT.

La información disponible permitió integrar:

- información de Policía
- información de Ejército cuando estuvo disponible
- información de salud mediante número de IPS

Sin embargo, la fuente del Ejército no contenía registros utilizables para los 31 municipios en esta etapa, por lo que las variables correspondientes quedaron como información faltante y fueron documentadas como tal.

No se interpretó la ausencia de registros del Ejército como ausencia de presencia institucional.

---

## 16. Consideraciones específicas del Dataset 09

El Dataset 09 quedó construido a partir de asignaciones/proyecciones del Sistema General de Participaciones (SGP) para 2027.

La base final contiene los 31 municipios del universo IOT, con DIVIPOLA única y sin duplicados.

El dataset contiene componentes relacionados con:

- educación
- salud
- agua potable
- propósito general
- alimentación escolar
- otros componentes de la asignación SGP

La variable `sgp_total_asignado_2027` corresponde a la suma de los componentes municipales disponibles en la fuente.

Este dataset representa **asignaciones/proyecciones SGP y no ejecución de inversión pública**.

La fuente SECOP fue inspeccionada, pero no se incorporó a la base municipal debido a la falta de información territorial confiable para asignar los contratos.

Asimismo, no se incorporaron fuentes PIIP, SGR u otras fuentes de inversión municipal que no estuvieran disponibles en RAW.

Por lo tanto, el Dataset 09 debe interpretarse como una medida de recursos/asignaciones SGP disponibles para los municipios, y no como una medición completa de inversión pública, infraestructura u obras ejecutadas.

---

## 17. Consideraciones específicas del Dataset 10

El Dataset 10 corresponde a una biblioteca de historia y evidencia cualitativa del Chocó.

Su unidad de observación es un documento, investigación o caso cualitativo.

No representa:

- municipio
- municipio-año
- proyecto
- indicador cuantitativo

La fuente contiene información territorial heterogénea.

En la exploración:

- el universo IOT contiene 31 municipios
- 8 municipios fueron mencionados literalmente en el texto territorial
- 23 municipios no tuvieron mención literal
- únicamente 2 registros permitieron una asignación municipal única
- 5 registros tuvieron alcance supramunicipal, multmunicipal o no pudieron homologarse a un solo municipio

La ausencia de mención de un municipio no debe interpretarse como ausencia de evidencia histórica, cultural o social sobre dicho municipio.

El dataset se conserva como fuente de **contextualización y evidencia cualitativa**, pero no se incorpora actualmente como componente cuantitativo del IOT.

No se construyó automáticamente un score de "evidencia histórica", "riqueza cultural" o similar, debido a que ello requeriría una metodología específica de codificación cualitativa.

---

## 18. Limitaciones generales encontradas

La exploración inicial permitió identificar varias limitaciones transversales:

1. Algunas fuentes no están diseñadas originalmente a nivel municipal.
2. Algunas requieren homologación territorial.
3. Algunas presentan cobertura municipal incompleta.
4. La ausencia de registro no necesariamente representa ausencia del fenómeno.
5. Algunas fuentes representan registros administrativos y no resultados territoriales.
6. Algunas variables representan asignaciones o recursos y no ejecución.
7. Algunas fuentes presentan temporalidades diferentes.
8. No todas las variables son directamente comparables entre municipios.
9. Algunas fuentes cualitativas no pueden convertirse directamente en indicadores cuantitativos.
10. La disponibilidad de una variable en una fuente no implica automáticamente que sea válida para formar parte del IOT.

Estas limitaciones deberán ser consideradas durante la selección y transformación de variables en la siguiente etapa.

---

## 19. Estado general de los datasets

La exploración individual de los diez datasets permitió cerrar cada fuente de acuerdo con su nivel de disponibilidad y sus limitaciones.

Los estados posibles utilizados fueron:

- **Cerrado:** la fuente pudo ser procesada y documentada sin limitaciones críticas para su uso previsto.
- **Cerrado con limitaciones:** la fuente puede utilizarse, pero existen restricciones que deben ser consideradas metodológicamente.
- **Bloqueado:** la información disponible no permite construir correctamente el dataset sin una fuente o decisión externa.

El estado definitivo de cada dataset se encuentra documentado en sus respectivos archivos de metodología, auditoría y cobertura.

Los Datasets 08, 09 y 10 presentan limitaciones específicas que deben conservarse durante la fase de análisis.

---

## 20. Qué no se ha realizado todavía

La exploración inicial **no constituye todavía el análisis del IOT**.

Hasta esta etapa no se han realizado:

- ponderaciones definitivas
- normalización definitiva de indicadores
- construcción del índice compuesto
- análisis causal
- interpretación causal de relaciones
- ranking definitivo de municipios
- identificación de determinantes de las oportunidades territoriales
- selección definitiva de todas las variables
- construcción de dimensiones finales del IOT
- conclusiones sobre qué municipios tienen mayores o menores oportunidades

Estas actividades corresponden a la siguiente etapa metodológica.

---

## 21. Frontera entre exploración y análisis

La exploración inicial responde principalmente a las siguientes preguntas:

**¿Qué contiene cada fuente?**

**¿Qué representa cada fila?**

**¿A qué territorio puede asignarse la información?**

**¿Qué tan completa es la cobertura?**

**¿Qué variables existen?**

**¿Qué transformaciones son necesarias para hacerlas comparables?**

**¿Qué limitaciones tiene cada fuente?**

La etapa de análisis responderá posteriormente preguntas diferentes:

**¿Qué variables representan adecuadamente las oportunidades territoriales?**

**¿Cómo deben normalizarse?**

**¿Cómo deben combinarse?**

**¿Qué dimensiones debe contener el IOT?**

**¿Qué diferencias existen entre municipios?**

**¿Qué patrones territoriales aparecen?**

Por tanto, se mantiene una separación explícita entre la **auditoría de las fuentes** y la **interpretación de los resultados**.

---

## 22. Conclusión de la exploración inicial

Con la revisión de los diez datasets se completa la etapa de exploración inicial de las fuentes disponibles para el IOT del Chocó.

El principal resultado de esta etapa no es todavía un índice, sino una estructura de datos documentada y trazable que permite conocer:

- qué información está disponible
- qué información puede compararse territorialmente
- qué fuentes requieren transformación
- qué fuentes presentan limitaciones
- qué variables pueden ser candidatas para el IOT
- qué información no puede utilizarse directamente
- qué decisiones deberán tomarse durante la fase metodológica

La exploración también permitió establecer reglas comunes para la homologación territorial, tratamiento de datos faltantes, agregación, conservación de valores originales y documentación de las fuentes.

A partir de este punto, el proyecto pasa de la pregunta:

> **¿Qué datos tenemos y qué tan confiables son?**

a la pregunta:

> **¿Qué variables son metodológicamente adecuadas para medir oportunidades territoriales y cómo deben integrarse en el IOT?**

---

## 23. Próxima etapa

La siguiente etapa corresponde al **análisis y selección metodológica de variables**.

En esta etapa se evaluará cada variable candidata según:

- pertinencia conceptual
- relación con la dimensión del IOT
- unidad territorial
- cobertura
- temporalidad
- comparabilidad
- calidad de la fuente
- riesgo de sesgo
- posibilidad de normalización
- interpretabilidad
- redundancia con otras variables

Solo después de esta evaluación se definirá qué variables entrarán finalmente al Índice de Oportunidades Territoriales.

**La construcción del índice no debe comenzar hasta completar esta evaluación.**